### ISSUE TITLE
Messaging section

### ISSUE THREAD

**Issue by acoburn** [fcrepo/fcrepo-specification#102]

**Comment by ajs6f** [comment]
Which specific statements would you like to remove?

On a semi-related note, I think "Messages MUST NOT be emitted until after any changes have been persisted to durable storage." might better read "Messages MUST NOT be emitted until after any changes have been made durable." That's a bit more agnostic to implementation details.

**Comment by acoburn** [comment]
I was thinking that the entire section 7.2 could be reduced to:

> Any operation that causes the state of a resource to durably change must make a notification available with a corresponding resource identifier.

**Comment by ajs6f** [comment]
I wouldn't agree with that. I think that the non-normative note (" Non-normative: consumers of these messages should not expect a strict ordering of the events... ") is very important clarification.

More importantly, I don't think that the remark "Any operation that causes contained resources to change MUST trigger corresponding events for those resources." follows from your changed text, nor does the remark "Any operation on an LDPR that results in a change to the containment or membership triples of a distinct other LDPR MUST also trigger an event for that other LDPR.", nor does "A failed operation (HTTP 4xx or 5xx) MUST NOT emit any messages.", so you are changing the meaning of the spec a good deal.

I would actually be in favor of getting rid of "A failed operation (HTTP 4xx or 5xx) MUST NOT emit any messages." but that's a separate issue.

Changing the other remarks... wouldn't that open the door to a messaging impl that would be not be very usable for indexing? I'm not suggesting that indexing is somehow a benchmark for the spec, just that how much indexing tech would have to change is a good measure in perspective for the size of the change you are suggesting.

**Comment by acoburn** [comment]
A more correct replacement would be:

> Any operation that causes the state of one or more resources to durably change must make available one or more notifications corresponding to the changed resources.

Even the current language falls short on the case of non-contained membership triples changing.

**Comment by ajs6f** [comment]
I'm getting a bit mixed up (which is normal for me). Can you put your more correct replacement replacement in the context of the larger change? How would 7.2 read in entirety?

**Comment by acoburn** [comment]
Honestly, it would be easier to discuss this in the context of a pull request. @awoods gave me the distinct impression that PRs that make substantive changes are not acceptable until after an issue has been discussed to satisfaction. Is that not the case?

**Comment by ajs6f** [comment]
I can't speak for @awoods. I would be very happy to see a PR and I agree that it would make discussion both easier and more fruitful.

**Comment by acoburn** [comment]
Resolved via #106
