### ISSUE TITLE
Are DELETEs optional?

### ISSUE THREAD

**Issue by acoburn** [fcrepo/fcrepo-specification#107]

**Comment by ajs6f** [comment]
I believe that the absence of `DELETE` was an oversight, but it is possible to imagine a useful "no-`DELETE`" server that just accretes change. For example, as a container for audit events.

**Comment by acoburn** [comment]
FWIW, the way Trellis works at present, is that `DELETE` operations will result in a `410 Gone` in the HTTP interface, but the data are still all present and can be retrieved via a memento time-gate interaction. So internally, `DELETE`s don't actually remove information -- they append (in RDF-Patch fashion) the "deletion" of certain triples, such that the state of the resource is "gone".

**Comment by acoburn** [comment]
...which is to say: ideally, I wouldn't have to implement DELETE at all -- that would make the resource interaction quite a bit more clear.

**Comment by ajs6f** [comment]
Not sure I follow "I wouldn't have to implement DELETE at all"-- you mean below the HTTP layer? You mean you wouldn't actually have to move or remove bits down below?

**Comment by acoburn** [comment]
What I mean is this: I have been experimenting with the idea of "persistent repository data" -- data that is never truly deleted (i.e. resources imagined as a commit log), such that it is possible to retrieve the resource state at any point in time, even across deletes. For a preservation system, this is an appealing concept.

At present, the `HTTP DELETE` operation simply reduces the state of the resource (internally) to a `ldp:Resource` with the type [`trellis:DeletedResource`](https://acdc.amherst.edu/ns/trellis#DeletedResource) and no triples -- though Audit triples continue to accrue. Requests for that resource would encounter a `410 Gone` response until such point in time that a new resource is created in its place. Whether that is more understandable than simply not allowing `HTTP DELETE` in the first place is an open question. In the end, I will very likely implement `HTTP DELETE` anyway, but it would be helpful to know if it is required or not.

**Comment by ajs6f** [comment]
Given this conversation, I would be in favor of leaving it out of the spec, which would allow the simplest behavior, your behavior, and other behaviors.

**Comment by acoburn** [comment]
OK, I'll leave this issue open for a few days in case there are other comments. Absent further comment, I'll close it sometime early next week.

**Comment by dannylamb** [comment]
@acoburn I'm curious as to the reasoning of returning something in the 4xx range when the operation has completed successfully (despite not _actually_ deleting).  If you don't return an entity within the response, is 204 not more appropriate?

**Comment by acoburn** [comment]
@dannylamb I really don't understand your comment above. How did anything I wrote imply that a 4xx response code would correspond to a successful delete operation?

**Comment by ajs6f** [comment]
@acoburn 
>  FWIW, the way Trellis works at present, is that DELETE operations will result in a 410 Gone in the HTTP interface

could be interpreted that way, but my understanding is that you really meant:

> Requests for that resource would encounter a 410 Gone response until such point in time that a new resource is created in its place.

**Comment by acoburn** [comment]
@ajs6f is correct: what I meant earlier was that a DELETE operation would respond with a `204 No Content`; subsequent requests to that resource would respond with a `410 Gone` (not that the DELETE operation would, itself, respond with at 410)

**Comment by dannylamb** [comment]
@acoburn Thanks for the clarification.  I read the following as "DELETEs will return 410"

> FWIW, the way Trellis works at present, is that DELETE operations will result in a 410 Gone in the HTTP interface

**Comment by dannylamb** [comment]
So if Trellis will use DELETEs, then is it ok to require it in the spec?  We'll have to specify behaviour around AuthZ if that's the case.

**Comment by acoburn** [comment]
I'm 👍  on leaving the spec silent on DELETEs. If the spec isn't silent on DELETEs.

**Comment by dannylamb** [comment]
I'm ok with them being optional, but I'm pretty uncomfortable with how wildly behaviour may vary between implementations that choose to provide DELETE operations.  If the scope of this issue is for them to remain optional, then I'm fine to close it and I'll raise my concerns in a separate issue.

**Comment by acoburn** [comment]
@dannylamb fine by me to close this.
