### ISSUE TITLE
Is the External content proposal a requirement of all Fedora servers? (edited) 

### ISSUE THREAD

**Issue by acoburn** [fcrepo/fcrepo-specification#112]

**Comment by dannylamb** [comment]
@acoburn I think we just have our wires crossed between the Confluence wiki, which allows for comments, and Github wikis. It certainly wasn't an intentional move to make this issue exclusive.

Thanks for raising the issue here.

**Comment by dannylamb** [comment]
FWIW in previous discussions I've simply been focused on how to do External Content, and not the strict requirement of it.  And I haven't given consideration to supporting all access types in IANA and would probably just stick to local-file unless someone _really_ wants to use a mail server as a storage engine.

**Comment by ajs6f** [comment]
@dannylamb How will that work in distributed situations in which the server answering the request doesn't know whether a bitstream is "local", or even whether there is an actual file on a traditional filesystem behind it? I am looking forward to a Trellis backend that uses Apache Spark. None of that situational context will be available.

**Comment by acoburn** [comment]
@dannylamb just so you know, _requiring_ `local-file` will automatically exclude just about any possible distributed implementation of Fedora. And it will most definitely exclude Trellis from even _possibly_ being compliant.

**Comment by zimeon** [comment]
@acoburn I think support for `local-file` _has_ to be optional (as @dannylamb suggests above; would otherwise be a rather strong statement on system architecture)

**Comment by acoburn** [comment]
@zimeon is `url` _required_?

**Comment by escowles** [comment]
I think `url` is the only access-type value that I would consider requiring.

**Comment by ajs6f** [comment]
@escowles `url` is for HTTP URIs only?

**Comment by acoburn** [comment]
Why would it be a requirement? What is the justification for it? In other words, how is this substantially different than simply linking to an external resource: 

    <> ore:aggregates <http://example.com/external-resource.tiff>

**Comment by escowles** [comment]
@ajs6f I'm not sure if `url` is restricted to HTTP — but given that the other `access-type` values largely correspond to other URI schemes, I think it might be.  Do you have other URI types that don't correspond to other `access-type` values?

**Comment by acoburn** [comment]
My point is this: if the semantics of Fedora are intended to be in line with LDP, why encourage a non-LDP pattern for an interaction model that LDP already supports?

**Comment by escowles** [comment]
@acoburn The main way that it's different is in having the server proxy access to a resource that's not otherwise accessible to the client.  @barmintor's use case was referring to files on locally-managed NAS servers — the server can access them over HTTP, but the clients external to the local network cannot.

**Comment by ajs6f** [comment]
@escowles If it's not limited to HTTP, what does my impl do when it receives an URI protocol it doesn't know how to dereference?

**Comment by acoburn** [comment]
@escowles is that use case sufficiently well understood to require support for _all_ Fedora implementations?

**Comment by escowles** [comment]
@ajs6f I would expect a 4xx response if the server doesn't understand a URI protocol, or has any other problems parsing the URI.

**Comment by ajs6f** [comment]
So it should be possible to "implement" this function by simply returning 4xx for every usage.

**Comment by escowles** [comment]
@acoburn My attitude about this has changed quite a bit recently, as it's become increasingly clear to me that a lot of people were using external content functionality in Fedora 3, and are using it now in Fedora 4.  So I think it's important to specify how it should behave so that different implementations implement it in the same way.

Proxying content from a HTTP URI seems like a much lower bar for implementations than supporting internally-managed LDP-NRs.  But it's an open question about exactly which of those should be required of all implementations.  I would be open to the idea that an implementation should either support internal content or external content, but need not support both of them, for example.

**Comment by barmintor** [comment]
@acoburn one difference in saying that a LDP-NR *is* a URI versus *aggregates* a URI is the ability to describe it with an associated LDP-R; that too is an implementation restriction to date, but it's another place where these specification interrelate. I'm also not certain that `ore:aggregates` conveys much information about what that resource is in its relationship to the LDP-R being represented, but obviously a universe of predicates awaits.

I'm sympathetic to @escowles's suggestion that maybe implementations would choose between internal and external content, and I don't know that such an approach would even depart too strongly from LDP, excepting that the current `MUST` for PUT to update LDP-NR content.

**Comment by barmintor** [comment]
@ajs6f the Spark implementation is an interesting consideration here- your cluster could all mount common storage (or something that looks like storage (edit: like hdfs)); it's a common integration pattern. It's incumbent on the sender of a `type=local-file` message to know it will be sensible to receiver, right?

**Comment by ajs6f** [comment]
@barmintor It's not clear to me that `local-file` has any real meaning when the server receiving that message will not know what is local or when there may be _no_ local storage.

A cluster _could_ arrange storage in lots of ways-- that is not something I want in any way controlled by HTTP considerations. I want that to stay comfortably in the hands of the data scientists and researchers who manage it very capably now. It is far more likely that the servers managing storage will not even be the same machines at all as those answering HTTP requests.

**Comment by barmintor** [comment]
@ajs6f it is always within bounds for a server to say that `local-file` is inappropriate, sure. Isn't outlining a pattern of reference necessary for storage to be managed separately? That's the use case that I see in this.

**Comment by acoburn** [comment]
@barmintor the example with ORE is perhaps confusing the issue. I am simply suggesting that, rather than creating a "proxy" IRI at, say </fedora/resource1> which proxies/redirects to <http://example.com/external-resource.tiff>, one would link to it directly. I.e this:

    <> ex:prop <http://example.com/external-resource.tiff>

instead of:

    <> ex:prop </fedora/resource1>

**Comment by ajs6f** [comment]
@barmintor That begs the question of whether "managing storage" is in any way the province of this specification, which in theory is RESTful and should discuss _only_ representations.

Frankly, if I can deal with this by just throwing 4xx for every case, I'll probably just do that. That, after all, is what I imagine every other LDP impl will do.

**Comment by acoburn** [comment]
If, throwing a 4xx error means "conformance", that's certainly what Trellis will do.

**Comment by barmintor** [comment]
@acoburn it seems to me that what you're describing aligns with this type of proposal in ways similar to the way that eg `rdf:type` and `Link` headers do. The particulars of `local-file` here may be a distraction, since a file path is really just another URI that the server can resolve but any given client may not be able to.

I'm not interested in universal implementation here, myself. But not taking the subject up at all is effectively suggesting that LDP-NR content is locally managed, and all other content of interest to the client is resolvable in common by URI; that just doesn't line up with implementation in my experience.

**Comment by ajs6f** [comment]
@barmintor From my POV, `local-file` is just an URI with a very problematic protocol.

**Comment by acoburn** [comment]
A big reason I raise this issue has to do with a very serious discomfort with conflating "user-managed" resources with "repository-managed" resources. If a `local-file` (or `url`) reference is proxied through Fedora, what happens if that file is moved? It is "user-managed" after all, and one would really need to expect that user-managed files get moved around. This concern is entirely independent of my concern about the fact that a distributed implementation may not be able to work with `local-file` references at all.

And even if `local-file` isn't _required_, but `url` _is_ required, the same issue applies if the remote content has been removed. What happens to the metadata/description stored for that resource? And what if the remote resource isn't removed, but just changed in some considerable way -- what are the requirements of a server to handle those cases? I would anticipate that many of the issues that were encountered with the (no longer supported) modeshape-based federation feature will apply to proxied content.

I understand that @barmintor is expecting to use this feature to support binary content in Cavendish, but I am entirely unconvinced that this is a feature that should be required of all Fedora repositories.

To @escowles' point about people already using this feature in Fedora4, one has to also remember that the feature in Fedora4 is "redirect", not "proxy". This proposal is about proxy, which is arguably quite different. So I don't agree that "lot of people ... are using it now in Fedora 4". Plus, there are a lot of features from Fedora3 that have been dropped (storing an audit trail with a resource is a big one).

**Comment by acoburn** [comment]
@barmintor yes, I am definitely suggesting that LDP-NR content is managed by the repository. There is already a mechanism for working with content that is not managed by the repository: links.

**Comment by barmintor** [comment]
@acoburn links are what we're talking about, aren't they?

**Comment by acoburn** [comment]
Yes, but proxied content obscures that. Redirected content conflates it.

**Comment by ajs6f** [comment]
@barmintor There is a real difference between a link that is manipulable as such (by presentation as an RDF triple inside an LDP API) and a link that appears momentarily as part of an interaction and is then only available from one side of any future interaction.

**Comment by barmintor** [comment]
@acoburn I hope it's clear that I don't think "required of all Fedora repositories" is of interest to me, but "I store my binaries in hdfs/irods/an hsm/netapps/etc. and describe them over here, but I don't want all the clients to have unmediated access to that device" seems like a use case worth talking about.

@ajs6f in the context of limited resolvability, there is a pretty slim difference between describing the location with a header and describing it with a predicate with special meaning. I can't believe I'm typing this, but I think this might be a use case for a Content-Location response header.

**Comment by barmintor** [comment]
@ajs6f  that is to say, `Content-Location` has seemed irrelevant to pushing a reference to Fedora, since it is supposed to accompany a representation that would have been available at the URI (unlike external-body), but it is an indicator of what we're talking about here: "this is the URI I used for this representation I'm sending you".

None of this addresses the `Want-Digest` problem, but I'm not convinced that it too isn't something the implementations you and @acoburn describe wouldn't support?

**Comment by ajs6f** [comment]
@barmintor My point was not to the limitations on resolvability-- it was, as I said, to the limitations on _manipulation_. As the document itself says "Should the client be able to retrieve the original reference to the external content? If so, how?"

It's true that I have not much more interest right now in `Want-Digest` than in this function, but I would like a coherent spec and it is certainly possible that `Want-Digest` will become more interesting in the future.

I'm not sure I understand what you mean about `Content-Location`-- can you please explain that more? Are you suggesting that clients would be able to retrieve the original URI from a `Content-Location` header?

**Comment by ajs6f** [comment]
@barmintor I think that use case is important, but it's not clear to me that it should be resolved directly within the spec. I think a good argument could be made that such a responsibility better rests with some layer of middleware, upon the existence of which I think it's not unfair to assume, given the history of Fedora usage.

**Comment by acoburn** [comment]
@barmintor if this is not of the category of "required of all Fedora repositories", the question I have is whether this is something that belongs in the core specification or should it be part of a sidecar document? I think it can be acknowledged that there are many valid repository use cases that are not described in the core specification.

> "I store my binaries in hdfs/irods/an hsm/netapps/etc. and describe them over here, but I don't want all the clients to have unmediated access to that device" seems like a use case worth talking about.

Yes, it is certainly a use case worth talking about, and from my perspective, this is precisely the sort of use case that API-X is designed to handle.

**Comment by acoburn** [comment]
@barmintor w/r/t `Want-Digest` (not to take this conversation on a diversion), but that feature is, generally speaking, extremely easy to implement, it has a clear purpose that fits well with the Fedora's proposed use of it and it poses no particular underlying restrictions on an implementation. I fully expect to implement that (even static-ldp implements Want-Digest).

**Comment by barmintor** [comment]
@ajs6f yes, what I'm suggesting is that a LDP-NR could advertise that it is proxied content by responding to, e.g.,  OPTIONS:

HTTP/1.1 200 OK
Allow: OPTIONS, GET, HEAD, PUT
Accept: message/external-body;type=url
Content-Location: `<wherever>`

edit: "original" is maybe an awkward term here, it's the current URI

@acoburn I'm definitely amenable to a sidecar spec. API-X seems like far too much for this, and has even more portability concerns.

**Comment by ajs6f** [comment]
+1 to taking this off to the side of the spec.

**Comment by ajs6f** [comment]
@barmintor Doesn't `Content-Location` necessarily take an URI?

**Comment by acoburn** [comment]
I understood `Content-Location` to require the full content of the resource on `PUT` or `POST` operations.

**Comment by barmintor** [comment]
@ajs6f From my POV, `local-file` is just an URI with a very problematic protocol.

**Comment by ajs6f** [comment]
@barmintor Right. For an impl in which the "location" of bits is (say) a Java API call, there is no URI. There is no URI to put anywhere. The assumption behind part of this conversation seems to be that content always has an URI. It doesn't.

EDIT: That wasn't well phrased-- what I should have said was " It doesn't necessarily have any other URI than the one by which it is to be addressed in the Fedora API."

**Comment by barmintor** [comment]
I feel more comfortable saying that content references need to be representable as a URI than I am saying that the client receiving the message should be able to resolve the URI. I presume that if you get the content from an internal API, that's just locally managed content (and wouldn't be representing itself that way).

**Comment by ajs6f** [comment]
@barmintor I am _extremely_ uncomfortable saying either "content references need to be representable as a URI" or "the client receiving the message should be able to resolve [an arbitrary] URI".

**Comment by ajs6f** [comment]
If this function is partitioned off into a separate, non-core spec, then I'm pretty much happy with that outcome.

**Comment by birkland** [comment]
In the Fedora 3 days, foxml contained details relevant to the persistence
and exposure of datastreams (managed, redirect, inline, URIs, internal
opaque IDs, etc).  I think the basic principle is sound.

In LDP, persistence is opaque, or at least not addressed by the spec.  The
implementation just does whatever it needs to do, and doesn't have to let
anybody reason about it.

In the external content proposal, the external message body contains stuff
that *some* clients and the server need to reason about in order to achieve
a particular effect.  The effect (proxying, redirect) exists so that
*other* clients do not have to reason about the persistence details and can
just access its content with plain ol' GET. Essentially all information
behind the scenes in order to make this happen has to be conveyed the URI
within the external message body  document.  The collision of these needs
is the most pressing issue with the proposal, in my mind.

I tend to agree that RDF is the best venue in which to express (and
manipulate) the persistence-related details in order to allow a mediation
layer (the impl itself, API-X, or whatever) to achieve the desired http
exposure.  A separate spec or ontology might be the best home for sort of
effort.

**Comment by barmintor** [comment]
@birkland I'm really reluctant to punt this to an ontology, if only for the fact that we are pretty much always sorry for investing predicates and/or URI patterns with behavior later. I offer as testimony to this that when I implemented the versioning spec, the least annoying approach I could think of was to put the timemaps in a completely external tree to the LDP resources.

**Comment by barmintor** [comment]
@ajs6f can you offer an example of  reference to external content that is not representable as a URI?

**Comment by ajs6f** [comment]
@barmintor Suppose a server is answering LDP requests and a "nearby" server is storing bitstreams. They do not and cannot share a filesystem space. The LDP-server can make remote calls on some process on the storage-server to get bits under various names. Those names are not URIs. The client knows a name for a piece of content on the storage server (e.g. this might be by ownership of some kind) and that name, as said, is not an URI and is not meaningful outside a particular set of applications that don't and can't have an HTTP exposure.

In any event, I want to emphasize that no one (to my glance) has objected to slicing this off into a "sidecar" spec. @birkland mentioned "a separate _spec_ or ontology" (my emphasis).

**Comment by barmintor** [comment]
@acoburn having established that implementations uninterested in supporting references to external content will return a HTTP status in the 4xx range, can we close this issue?

**Comment by acoburn** [comment]
@barmintor I think there is still an open question about whether `message/external-body` support  will be part of a sidecar document or not. Either way, I'd suggest keeping this issue open until the current spec document is updated to reflect the discussion here.

**Comment by barmintor** [comment]
@acoburn I updated @escowles proposal. Since there is a well-established convention in LDP of returning HTTP 415 in the event that a media-type is unsupported, and this relies on Content-Type, I think that we can safely defer the question of whether it's an auxiliary spec or not so long as we don't presume support is a `MUST`- between 415 and `Accept-Post`, there's discoverability mechanisms. I'll open separate issues for the other questions from the document.

**Comment by barmintor** [comment]
@acoburn with the language merged, can this ticket be closed?
