### ISSUE TITLE
How to evaluate header behavior of referenced content LDP-NRs?

### ISSUE THREAD

**Issue by barmintor** [fcrepo/fcrepo-specification#113]
Can we reasonably require the other header behaviors (Digest/Content-Size/Last-Modified/etc.) for non-file reference URIs? Can we require that the proxied URI support them in HEAD and return 4xx on update if not?

**Comment by acoburn** [comment]
In addition to the header fields mentioned already, the LDP spec states: 

> 4.2.1.3 LDP server responses `MUST` use entity tags (either weak or strong ones) as response ETag header values, for responses that contain resource representations or successful responses to HTTP HEAD requests.

If the referenced (non-file) URI does not itself provide an ETag header, generating one reliably may prove difficult, especially if such header fields as `Content-Length`, `Last-Modified`, etc are not required by HTTP (the relevant HTTP RFCs use `should` for those headers).

**Comment by ajs6f** [comment]
I don't see how these responsibilities can reliably be shifted to servers that might be anywhere and which (so far) haven't even been restricted to HTTP.

**Comment by barmintor** [comment]
Exactly- reiterating the requirement as a condition of the referenced content URI seems necessary. Up to the impl to sort out whether that's via HEAD, file system access, etc.

**Comment by ajs6f** [comment]
And when it is not possible at all?

**Comment by acoburn** [comment]
Or when a `HEAD` request to the Fedora server requires _reading_ all of the content from the remote HTTP server? That seems very problematic.

**Comment by barmintor** [comment]
It's up to the impl to determine whether it can use the URL appropriately to its API requirements, and reject if not.

**Comment by barmintor** [comment]
@acoburn if that's problematic, then it seems like 1) that thing should not be on the web, or 2) your impl should care about how it proxies, doesn't it? Otherwise it seems like we're talking about the citizenship ethics of linking.

**Comment by ajs6f** [comment]
@barmintor, it is absolutely not the case that "that thing should not be on the web" simply because its `HEAD` response doesn't include all the headers you demand above. It's increasingly clear to me that the simple solution here is just to throw 4xx on every use of this function and have done with it.

**Comment by escowles** [comment]
I agree with @barmintor — if the external content resource is a file URI or a well-behaved HTTP URI, then the requirements seem easy to meet.  If it isn't one of those, then the implementation will probably either refuse it as an external content resource, resort to caching the resource, or use some other strategy that allows it to fulfill its obligations.

**Comment by barmintor** [comment]
@ajs6f I thought I was clear enough that I was responding to @acoburn :

> Or when a HEAD request to the Fedora server requires reading all of the content from the remote HTTP server? That seems very problematic.

When I said:

> @acoburn if that's problematic, then it seems like 1) that thing should not be on the web, or 2) your impl should care about how it proxies, doesn't it? Otherwise it seems like we're talking about the citizenship ethics of linking.

I apologize if I wasn't; I face the limitations of the medium here. But I also feel like your read of that comment was a little more ungenerous than I deserved: I'll admit that "citizenship of linking" was kind of obscure, but I don't think it suggested that all of the world should be LDP. On the other hand, I've gone to some pains to make sure that the ways an implementation could reject such requests were clear, so throwing 4xx on all of these is fine (the authors of the `Accept-Post` proposal recommend HTTP 415).

**Comment by ajs6f** [comment]
Yes, and my comment applies exactly there ("simply because its `HEAD` response doesn't include all the headers you demand above").

In any event, it seems we are agreed that just throwing 4xx (and 415 sounds fine to me) is the simplest way forward. It essentially makes this capability optional.

**Comment by barmintor** [comment]
Let me reiterate that I meant, pursuant to @acoburn's comment, that if merely servicing a `HEAD` request requires an expensive read, the problem is not that the resource was linked to, but that it should not be available for linking. It had nothing to do with the headers returned by `HEAD`, except that I am contending that 1) if the reference is a URL and that URL does not provide a satisfactory `HEAD` response to participate in a specified interaction, then 2) the implementation ought to return a 4xx rather than store the reference.

That is why I opened this issue:
> Can we require that the proxied URI support [the headers] in HEAD **and return 4xx on update if not?**

**Comment by ajs6f** [comment]
@barmintor To be clear, I am in no way trying to dismiss the validity or importance of the use case. My argument here starts by noting that it does not follow from the fact that the use case is important that it should be solved as a required part of the Fedora API.

This kind of proxying behavior made sense for Fedora 3, the purpose of which was to take the Fedora data model and put it on the Web. Fedora 4, by contrast, begins _from_ the Web, as no has argued with more vigor and acuity than yourself. Switching back and forth from and to proxying behavior on a per-URI basis seems confusing _at best_ and as we've seen already, is liable to result in variation of behavior that will raise the costs of integration severely.

As long as implementors have a straightforward "opt-out" for this (and I think we all agree that such is available in the form of 415-to-all) then at least this requirement doesn't have the damaging effect @acoburn noted elsewhere with respect to distribution, and unless this part of the spec can be parceled off into a "sidecar", I thin that's the best that can be done.

**Comment by awoods** [comment]
@barmintor : I believe this issue has been resolved with: https://github.com/fcrepo/fcrepo-specification/pull/121
If you agree, would you please close this issue?
