### ISSUE TITLE
Rename to Fedora Core API Specification?

### ISSUE THREAD

**Issue by zimeon** [fcrepo/fcrepo-specification#122]
I think that we should rename the [Fedora API Specification](http://fedora.info/spec/) to the **Fedora Core API Specification** (or similar) in order to help avoid confusion between features all implementations of this API will support, and additonal features that particular implementations support. We already have a separate [Fedora Batch Operations Specification](https://fcrepo.github.io/fcrepo-specification-atomic-operations/) and there are optional behaviors such as [PUT-to-create](https://github.com/fcrepo/fcrepo-specification/issues/43) and [LDP-NR with message/external-body](https://github.com/fcrepo/fcrepo-specification/issues/118). In particular, I think we have to be careful not to create confusion between the features of the Fedora community implementation (that some applications/frameworks might rely upon) and the requirements of this specification.

**Comment by ajs6f** [comment]
I'm very sympathetic to the motive. I do worry (as usual) about the implications for inference. Might naming a "core" and other specs lead to people supposing that the "core" is just one of the specs that an impl should meet to call itself Fedora? That would be the opposite of what was intended.

Maybe go the other way? Add some language to the titles of the _other_ specs to indicate that they are "extended" or "optional" or "bonus" or generally to be considered as selected cherries you can put or not put on top of your Fedora sundae.

**Comment by awoods** [comment]
@zimeon : I agree that clarifying the purpose and relationship between the various specification documents would help clarify the broader effort. Would it make sense to slightly broaden the scope of this GitHub issue to naming/defining *all* of the specification documents... along the lines of or rather informed by your [dependency diagram](https://github.com/fcrepo/fcrepo-specification/files/1045011/2017-04_fedora_dependencies.pdf)?

**Comment by acoburn** [comment]
I also think that clarifying the relationship between the different specifications would be a positive direction.

However, along the lines of what @ajs6f has already written, adding the word "core" to this specification's title may not lead to the this outcome. In my experience, a lot of the software I work with that has "core" in its name typically doesn't stand on its own: it is certainly core or central to the application, but it is not the complete package. If a server that implements the Fedora API specification `===` Fedora, then leaving the name as-is seems like the best approach.

I would be very supportive of adopting a word such as "extension" for the other specifications. That would also result in a clarification of the relationship between these various documents.

**Comment by escowles** [comment]
> If a server that implements the Fedora API specification === Fedora, then leaving the name as-is seems like the best approach.

Because the behavior in the specification is narrower than the behavior of the current Modeshape implementation (batch atomic operations being a significant thing that was split out).  So I agree it's important to be clear about that, to avoid confusion when something that implements the Fedora API spec doesn't do everything the Modeshape impl. does.

But I also agree with @acoburn's point that "core" might be interpreted as something too narrow.  I wouldn't want the spec name to give people the impression that it wasn't useful without other pieces.

**Comment by zimeon** [comment]
As I read comments here I wonder whether there is a decision or plan about branding the "Fedora ModeShape implementation" or "Fedora community implementation", and explaining its relation to the Fedora specifications (core, extension or other)? I note inconsistency even in how we refer to it now.

**Comment by acoburn** [comment]
When I use the word "Fedora", I mean the "idea of doing Fedora".
When I use the word "Fedora4", I mean the "modeshape-based implementation of Fedora"

**Comment by zimeon** [comment]
Closing this issue because there isn't agreement for such renaming. I think that we must just ensure that the community is happy with what the specification defines as a minimal Fedora, and keep this in mind while asking for feedback during the development process.
