### ISSUE TITLE
Process for amending the Fedora API specification

### ISSUE THREAD

**Issue by acoburn** [fcrepo/fcrepo-specification#125]
Even though the Fedora API specification has not yet reached public draft status, it would be helpful if the editors outline a process by which the API specification itself can be modified once it is published in its final form.

What is the process for making changes? Are a new group of editors selected? Who selects those editors? How are errata handled?

It would be nice if this process is defined _before_ the API specification is published in its final form.

**Comment by zimeon** [comment]
IMO this is out-of-scope

**Comment by ajs6f** [comment]
Perhaps it is not the job of the editors, but of the Leadership Group that selected them. In any event, a specification with no process for evolution has a very limited future.
