### ISSUE TITLE
What are the criteria for distinguishing between optional/core and optional/external

### ISSUE THREAD

**Issue by acoburn** [fcrepo/fcrepo-specification#127]

**Comment by ajs6f** [comment]
It will be extremely difficult to give an understandable rationale for this division without having an [understandable rationale for the core specification](https://github.com/fcrepo/fcrepo-specification/issues/95).

**Comment by acoburn** [comment]
I don't want this to be taken the wrong way, but I think it is really important to have a clearly defined vision behind Fedora. That vision would inform what features go into the specification (and what features do not belong). From my perspective, this vision is conspicuously absent.

Absent a vision, this specification is simply an (arguably) arbitrary collection of features and behaviors that have accumulated over the years. Some of those features might be of interest to me, and others might not. The key thing here is this:

Why would I (or my institution) care about Fedora?

Yes, Fedora has a long history, and there are a lot of people who have used the software and who continue to use it, but why should my institution care about this particular set of features? What is it about this particular set of repository functionality that is so important? As a note, the specification makes no mention of Audit records (arguably, a fundamental piece of any digital repository, and certainly something that my institution finds very important). And yet there is a lot of text in this specification devoted to features that we (i.e. at my institution) have absolutely no interest in.

If the Fedora API specification is a formalization of a vision of a particular repository architecture, that is something I can get behind. But if it is simply an arbitrary collection of features and functionality that may or may not be relevant, how can I justify that to my institution? Or, from another perspective, why should I (as an implementer of repository software) make that software conform to the Fedora API?
