### ISSUE TITLE
Distinguish ?s ldp:contains ?o triples and containment triples

### ISSUE THREAD

**Issue by barmintor** [fcrepo/fcrepo-specification#129]
The LDP spec defines containment triples as:

> A set of triples, maintained by the LDPC, that lists documents **created** by the LDPC but not yet deleted. These triples always have the form: ( LDPC URI, ldp:contains , document-URI ).

(emphasis mine)

However, like squares and rectangles, it's possible to read the definition backwards and observe that while all containment triples have the form `( LDPC URI, ldp:contains , document-URI )`, not all triples of that form are necessarily containment triples. In particular, implementations that separate user and server managed data may be able to support, eg, a DirectContainer that uses `ldp:contains` as its memberRelation.

As such, when the specification refers to `ldp:contains` as the axis along which inheritance of ACLs or other behavior is reckoned, it should be changed to instead refer to the axis of containment.

**Comment by barmintor** [comment]
As a corollary, implementations `should not` allow `ldp:contains` as a memberRelation if they cannot distinguish membership triples and containment triples (this should be a straightforward test to write with recourse to `Prefer`).

**Comment by no-reply** [comment]
> As a corollary, implementations should not allow ldp:contains as a memberRelation if they cannot distinguish membership triples and containment triples (this should be a straightforward test to write with recourse to Prefer).

I think this is probably a bug in most existing implementations. `RDF::LDP` almost certainly has this problem.

**Comment by dannylamb** [comment]
I'm :+1: for what you're suggesting @barmintor.

**Comment by barmintor** [comment]
Any restriction in 3.1.1. need to apply to IndirectContainers as well.

**Comment by zimeon** [comment]
I agree with @barmintor's assessment that, according to [LDP](https://www.w3.org/TR/ldp/#terms), while the notion of _containment_ is always indicated with triples of the form `<LDPC-URI>  ldp:contains <document-URI>`, not all triples of the form `<s> ldp:contains <o>` imply containment. Thus the spec should be changed to say something like "\[recursion|ACL inheritance\] ... must determined by following LDP containment relationships." (I think introducing "axis" is confusing and so have avoided it).

However, this is a subtle and confusing distinction which I think will be likely to trip up readers, so I think we should have a note explaining the distinction. Perhaps something along the lines of:

> Non-normative note: [LDP containment](https://www.w3.org/TR/ldp/#dfn-containment) relationships bind an LDPC to LDPRs whose lifecycle it controls and is aware of, and are expressed through [containment triples](https://www.w3.org/TR/ldp/#dfn-containment-triples) of the form `<LDPC-URI> ldp:contains <LDPR-URI>`. Implementations may allow the creation of other triples with the `ldp:contains` predicate, and thus triples with this predicate do not necessarily imply containment.

**Comment by acoburn** [comment]
I agree with the overall direction of this discussion, but I would urge caution about including a non-normative note such as what is suggested above, since it assumes that containment relationships are necessarily connected to the management of resource lifecycle. For a single-node, consistent implementation, this is a perfectly reasonable assumption. For a distributed, eventually consistent implementation, it is not. I am referring specifically to the text "LDP containment relationships bind an LDPC to LDPRs _whose lifecycle it controls and is aware of_, ...". (emphasis mine).

**Comment by zimeon** [comment]
@acoburn _"whose lifecycle it controls and is aware of"_ is verbatim from LDP

**Comment by acoburn** [comment]
I am only noting that the specification editors should make an effort to consider the implications of the specification text on potential distributed implementations of Fedora.

**Comment by barmintor** [comment]
It is worth noting that the _"whose lifecycle it controls and is aware of"_ is quoting a normative section of the LDP specification, though there is a little bit of wiggle room in the definition _"(through LDP-defined means)"_ (whether a resource that exists before its container exists to LDP at all, one must wonder).

I should have a PR together in the next day.
