### ISSUE TITLE
Redesign fixity proposal to focus on minimal verification rather than fixity as resource

### ISSUE THREAD

**Issue by barmintor** [fcrepo/fcrepo-specification#13]
Based on notes from the [December 8, 2016](https://wiki.duraspace.org/display/FF/2016-12-08+-+Fedora+Tech+Meeting) committer call, the subsequent [listserv discussion](https://groups.google.com/d/msg/fedora-tech/HMpD9n4273U/hOWX5WQ2CgAJ), and resulting [proposals](https://docs.google.com/document/d/1Nm-LFyUhCl-et4UsdePuMJ_Zu23Mot4FiEpEMke_JH4/edit).

**Comment by acoburn** [comment]
Addressed with https://github.com/fcrepo/fcrepo-specification/commit/525bc6ee7ec24c6d044b5fc7d300f46c549510ba
