### ISSUE TITLE
Test suite repo at fcrepo/fcrepo-tcks does not exist.

### ISSUE THREAD

**Issue by acoburn** [fcrepo/fcrepo-specification#131]

**Comment by barmintor** [comment]
@awoods can we create a stub repo there, with an appropriate readme?

**Comment by awoods** [comment]
https://github.com/fcrepo/fcrepo-tcks

**Comment by acoburn** [comment]
@awoods I appreciate that you created a git repository at this location and closed this ticket, but the mere existence of a repository in this location does not resolve the absence of a test suite, given that the specification refers to such a repository _as_ the Fedora specification test suite.

**Comment by awoods** [comment]
@acoburn : agreed, we will need to create such a test suite.

**Comment by acoburn** [comment]
@awoods I am sure that everyone agrees that such a test suite needs to be created. The issue I am raising is that the specification is asserting that the repository at https://github.com/fcrepo/fcrepo-tcks _is_ the test suite, which is absolutely not the case, given that there is no code there.

**Comment by barmintor** [comment]
@awoods noting from the charter:

> Define such interactions such that an implementation’s conformance is testable

Can we ask the SG to make the test suite a deliverable for the recommendation status? I don't see how we could satisfy the implementation requirements without one, and it would clarify how we plan to address these things.

**Comment by zimeon** [comment]
Agree that the test suite should be a deliverable for the recommendation status. I don't see any point in having temporary language in the draft to indicate that it isn't done yet.

**Comment by awoods** [comment]
@barmintor : We can certainly raise this with the SG... I am sure they will fully support the idea.
