### ISSUE TITLE
Restore ACL language to HTTP DELETE with Depth header

### ISSUE THREAD

**Issue by barmintor** [fcrepo/fcrepo-specification#134]
Previous objections about asynchrony in #126 made clear that further clarification between the HTTP DELETE issued and "request" in @dannylamb's original language:

> Implementations MUST reject any request regardless of <code>Depth</code> if there is an ACL for any affected resource that prohibits the operation.

This behavior is important on the initial HTTP DELETE, but the dispatch of actual deletion operations internally should be left to the implementation.

edit: clarified "initial DELETE" as the operation-originating HTTP DELETE

**Comment by acoburn** [comment]
@barmintor can you clarify what is meant by "initial DELETE"?

**Comment by barmintor** [comment]
the HTTP DELETE

**Comment by acoburn** [comment]
@barmintor let me be more clear.

Say a distributed repository contains a non-root container at `/foo`. That container contains 1 billion resources. If WebAC is in effect, the server will need to analyze the ACL on each of those billion resources. That will, in all likelihood, take a considerable amount of time. In all likelihood, a client will timeout long before the response code is provided.

If the resource at `/foo` is, itself, WebAC-restricted, yes, a server may provide an immediate 4xx response. But if one of those 1 billion contained resources is WebAC-restricted, it is entirely unreasonable for an implementation to follow this language:

> Implementations MUST reject any request regardless of Depth if there is an ACL for any affected resource that prohibits the operation.

With that in mind, an HTTP 202 response is much more appropriate, even if one of those contained resources is, in fact, WebAC-restricted.

Which is to say, I am 👎  on restoring the language included above.

**Comment by ajs6f** [comment]
The DRAS-TIC project is scaling into the 100s of millions of resources now. This is an eminently practical question.

**Comment by barmintor** [comment]
@acoburn I'd be happy to see the language changed to say "must not perform any delete operations ... 40x for synchronous, 202 for asynchronous", but I think there should be a stance about implementation ensuring that the resources in scope of the requested operations are allowed, and not deleting partial resources.

**Comment by acoburn** [comment]
@barmintor why not? Isn't that an implementation decision?

**Comment by ajs6f** [comment]
That need (loosely, atomicity) is better handled directly by use of the "sidecar" atomic operation specification. Putting it in here brings into play all of the reasons that spec was broken out of the "core" document.

**Comment by barmintor** [comment]
@acoburn I'm opening a ticket here for a use case I think is clear: A client should be able to know what was deleted. What is the use case for implementations not doing this?

**Comment by ajs6f** [comment]
The issue is not whether "A client should be able to know what was deleted." The issue is whether than should occur via HTTP response or via some other means, such as the event stream. The reason is that a recursive delete could take an essentially arbitrary amount of time.

**Comment by acoburn** [comment]
@barmintor for a resource-oriented (REST) server, operations on particular resources are well-defined. But in the case of operations on a single resource that may affect an arbitrary number of other resources (e.g. recursive delete), it is entirely possible that the time required to compute the appropriate response code is arbitrarily long. Given that fact, it is unreasonable to expect an HTTP response that describes what was changed.

**Comment by gregjan** [comment]
Let me chime in here to support the idea of splitting atomicity from permissions. If a client requests an atomic recursive DELETE, a repository like DRAS-TIC would have to say no, and might say no to all atomic requests, TBD. But if not atomic, we could return 202 and start to DELETE, leaving behind anything restricted or containing restricted resources.

Is there language around atomicity yet, this sidecar spec?
Also hello, it is good to be back.

**Comment by barmintor** [comment]
I think it's worth noting that advocates of the ACL language are presumably trying to know that this scenario:

> start to DELETE, leaving behind anything restricted or containing restricted resources

*won't* happen. There is an issue about atomicity of operations, but I don't think the disagreement here is really about atomicity.

Is it useful to think about `rm` as an analog? If you don't have permission to delete a descendant file, you don't zap the directory tree above it. Does that indicate a more precise way to talk about these things, that containers shouldn't be deleted unless they are empty?

**Comment by ajs6f** [comment]
The issue is synch/asynch. The recursive process being asked for here is not RESTful (it addresses many resources with one request) and because HTTP is synchronous, distributed operations over multiple resources of this kind have to be mapped into RESTful HTTP. HTTP 202 is exactly the means by which to do that. A server could offer 202 as a response with some header that points to a resource that can give an update on the progress of the operation. 

Keep in mind that a delete that affects very remote resources could take hours or days.

**Comment by barmintor** [comment]
If the issue is about asynchronicity, then we're discussing different places a client might be notified that that HTTP DELETE was rejected. If the issue is about the expected repository state, it's about evaluating ACLs.

It can be about both, but I feel like conversations along those two trajectories are sliding past each other here.

**Comment by ajs6f** [comment]
I don't think those two things are separable. That is in fact part of the reason that `Depth` is problematic-- it exactly tangles those two things.

**Comment by gregjan** [comment]
Hey @barmintor, I agree that the advocates of the ACL language probably want that guarantee, i.e. that partial recursive deletes will not happen. I suspect that not everyone wants that same guarantee. Though convenient for certain cases, it hardly helps one make progress on the task of DELETE over a large folder. The `rm` style does do that and leaves behind a trail to the remaining resources.
I'm off to try and read the Web ACL language on DELETE, pointers welcome.

**Comment by gregjan** [comment]
I suppose in some ways, `rm` style is more like calling the same HTTP DELETE operation on every resource in the tree, i.e. interpreting DEPTH as more like a "repeat HTTP operation on every contained resource to depth X".

**Comment by barmintor** [comment]
@gregjan is there a reason here to say "containers should not be removed if they have remaining contained resources", and leave aside the `Depth` header as one way that might be resolved (ie, the rm model)?

**Comment by acoburn** [comment]
@barmintor there is an issue with this suggestion:

> containers should not be removed if they have remaining contained resources

Here you are assuming a certain model of consistency such that in a distributed context you couldn't asynchronously remove nested containers unless those DELETE operations are strictly ordered. And assuming order in a set of async operations is wrong.

**Comment by acoburn** [comment]
@barmintor plus, there may be legitimate use cases for being able to remove a container and leave child resources in place. (I have such a use case)

**Comment by barmintor** [comment]
I'm not questioning the use case, but that's a behavior that you can't describe on LDP's terms, and I think that it would be fair to require that to happen via mechanisms external to the spec. Unintentionally disconnected resources seems like a thing we should be taking up here.

**Comment by ajs6f** [comment]
[LDP](https://www.w3.org/TR/ldp/#ldpc-mbrcntdiff) indicates that "contained LDPRs may be removed" but does not require it. It would seem that disconnected resources are ab initio permissible on LDP's terms.

**Comment by acoburn** [comment]
Here, as in other places, I am merely commenting on proposed language that may preclude the possibility of a distributed Fedora implementation. If it is the intention of the editors to make such a (distributed) implementation possible, then I would encourage you to be careful with language that has assumptions about consistency, atomicity and order.

**Comment by barmintor** [comment]
@ajs6f since the LDPC controls the lifecycle of its contained LDPRs, it is hard to read that as suggesting disconnected resources and not the rejection of the delete

@acoburn I'm not trying to preclude a distributed implementation, and I also am not trying to privilege the possibility of a particular type of distributed implementation over the chartered goals:

"This specification will:

1. Define the characteristics and expectations of how clients interact with Fedora implementations
2. Define such interactions such that an implementation’s conformance is testable
3. Enable interoperability by striving to minimize the need for modifications to client applications in order to work with different implementations of the Fedora API specification
"

I think the client expectations here are important - does trellis only offer the LDP resources as the an API? Would it be possible for it not to offer DELETE via the LDP API?

**Comment by ajs6f** [comment]
@barmintor In fact I read it as suggesting neither and intentionally leaving the question up to the impl. If the rejection of the `DELETE` was expected, that would not have been difficult to describe.

**Comment by acoburn** [comment]
What @ajs6f said is exactly how I read the LDP spec: it leaves these questions up to the implementation.

**Comment by acoburn** [comment]
@barmintor I don't understand your comment above. Trellis offers per-resource consistency over the standard HTTP operations: PUT, POST, DELETE, GET, PATCH, OPTIONS, HEAD in conformance with LDP. Trellis is not doing anything particularly bizarre with eventual consistency, and a standard LDP client should not have any trouble working with it.

**Comment by birkland** [comment]
Sorry for chiming late.  After reading the comments and the LDP spec, it seems apparent that a DELETE on a container has no specific consequence on members of that container; an impl can do whatever it wants.

The inclusion of `Depth` provides a mechanism for clients to be explicit in what they want.  For better or for worse, the only value for depth that is entirely clear to me is `depth=0`, which means "delete only this resource, and no others".  If the server won't allow orphan/disconnected members, then it can say "no" via a `400`.  

Specifying what happens with `Depth` > 0 gets hairy.  The ACL issue highlights that.  Irrespective of distributed vs non-distributed, my gut feeling is that "_MUST reject any request.. if there is an ACL for any affected resource that prohibits the operation_" would be prohibitively difficult to implement in just about every implementation.  

So at this point, I would advocate that the spec only address the error case of `Depth`> 0 (i.e. a `400` if unsupported), and leave the rest to the implementation.

**Comment by barmintor** [comment]
@birkland there is an issue about the language for `Depth` at https://github.com/fcrepo/fcrepo-specification/issues/135
