### ISSUE TITLE
Restrict Depth: to 0 and infinity on HTTP DELETE

### ISSUE THREAD

**Issue by barmintor** [fcrepo/fcrepo-specification#135]
From RFC4518:

> Methods that support the Depth header may choose not to support all
> of the header's values and may define, on a case-by-case basis, the
>  behavior of the method if a Depth header is not present.  For
>  example, the MOVE method only supports "Depth: infinity", and if a
>  Depth header is not present, it will act as if a "Depth: infinity"
>  header had been applied.

`Depth: 0` seems useful for clients who want confirm that only a single resource is deleted; `Depth: infinity` makes sense for expected recursion (and can be walked backwards if rejected). I don't see a case for `Depth: 1`. Maybe clarify that the spec only takes a stance on the other values?

**Comment by acoburn** [comment]
I have use cases for `Depth: 1` as well as the general case of `Depth: N` where N is a positive integer.

I also have use cases such that an absence of a `Depth` header does not imply `Depth: infinity`.

**Comment by barmintor** [comment]
"Depth: N" would be something we are inventing, no?

**Comment by ajs6f** [comment]
`Depth: 1` is not. I have use cases for it-- specifically in the context of multiple containment.

**Comment by barmintor** [comment]
This is another topic, but in the LDP spec there's no such thing as multiple containment - that would also be an invention.

**Comment by barmintor** [comment]
In any case, it seems like *adding* supported values for `Depth: N` also needs to be dealt with separately, even if this ticket is closed, since that behavior is not in RFC4918 unless I misremember.

edit: 4518 -> 4918, thanks!

**Comment by ajs6f** [comment]
To my understanding, there is no provision in LDP for _creating_ multiple containment. _Presenting_ it is as simple as putting the right triples in the right containers, and systems like https://github.com/trellis-ldp/static-ldp/ demonstrate the value of using LDP to publish RDF without using it to create that same RDF.

**Comment by ajs6f** [comment]
RFC4918?

**Comment by acoburn** [comment]
Depth: N is not part of RFC 4918. My request is only that the Fedora specification not explicitly _forbid_ a server from supporting arbitrary depth. In other words, if a server supports arbitrary depth, that should be allowed, but it would be behavior that is out of scope of the Fedora specification.

**Comment by ajs6f** [comment]
Agreed. It seems to me that this could be worded (based on the initial issue description) by "clarifying that the spec only takes a stance on the other values" and explaining that the spec doesn't forbid any other values or require them.

**Comment by barmintor** [comment]
I'm looking at the LDP definitions for containment:

> The relationship binding an LDPC to LDPRs whose lifecycle it controls and is aware of. The lifecycle of the contained LDPR is limited by the lifecycle of the containing LDPC; that is, a contained LDPR cannot be created (through LDP-defined means) before its containing LDPC exists.

containment triples:

> A set of triples, maintained by the LDPC, that lists documents created by the LDPC but not yet deleted.

and LDP-server-managed-triples:

> The portion of an LDP's triples whose behavior is constrained directly by this specification; for example, membership triples and containment triples. 

Because you can only create a resource once, and because singular pronouns are used in the definition of containment, I don't see a way to read multiple containment in the spec, at least not in a way that is navigable by containment triples. The ambiguities elsewhere suggest some room for the ldp:contains predicate in user data (assuming that data can be segregated), but that seems to be intentionally different than the containment definitions.

**Comment by barmintor** [comment]
If we take recourse to RFC4918, do we even have anything to say about other values? That spec defines the set of values, doesn't it?

**Comment by ajs6f** [comment]
We are reading those portions of specification differently. I see (again) that they govern particular `ldp:contains` triples and not all of them.

Regardless, there is another argument that obtains here; the fact that some may find `Depth: 1` (or `Depth: N`, for that matter) confusing or useless and some do not is a pretty good sign that the spec should be silent on it absent some overriding reason. What would that reason be, in this case?

**Comment by acoburn** [comment]
@barmintor I am making two points: (1) that we say nothing about other values and (2) that we do not further restrict the current set of values defined in RFC 4918.

Given the title of this issue, that second point is especially relevant.

**Comment by barmintor** [comment]
I am sensitive to the questions raised by @acoburn in https://github.com/fcrepo/fcrepo-specification/pull/126#issuecomment-306808635

As it seems that they would be resolved by the "infinity case" (the authorization can happen once, and descendant resources would fall under the remit of the delete) and the "0" case (you either support disconnected resources or you fail), but that the "1" case introduces unpredictability. But this conversation is also why I open the ticket.

**Comment by ajs6f** [comment]
Unpredictability would be one way to put it, but one with a pretty negative assumption on it. There are many different places in the spec now where we could find unpredictability, or simply that there is no strong reason to demand that all impls behave alike.

**Comment by dannylamb** [comment]
@barmintor closing this one since we're not requiring AuthZ denials be returned in the response for async implementations and use cases for arbitrary depths have been expressed.
