### ISSUE TITLE
Clarify PUT for large LDP-NR

### ISSUE THREAD

**Issue by acoburn** [fcrepo/fcrepo-specification#142]

**Comment by acoburn** [comment]
Given this text from the LDP specification:

> LDP only specifies the use of POST for the purpose of creating new resources, but a server can accept POST requests with other semantics. While "POST to create" is a common interaction pattern, LDP clients are not guaranteed, even when making requests to a LDP server, that every successful POST request will result in the creation of a new resource; they must rely on out of band information for knowledge of which POST requests, if any, will have the "create new resource" semantics.

it seems that using `POST` to replace LDP-NRs would be perfectly legit (the specification here doesn't forbid it) so long as `PUT` is also available, even if a given `PUT` operation may be `ldp:constrainedBy` some payload-size-related IRI.

**Comment by awoods** [comment]
@acoburn : limiting the scope of usage for `PUT` with `ldp:constrainedBy` seems right.
