### ISSUE TITLE
Checksum calculation on GET

### ISSUE THREAD

**Issue by awead** [fcrepo/fcrepo-specification#148]
In section 3.5.3:

> Given the use of checksums to validate content integrity, the digest values should be calculated instead of cached.

This seems to imply that every GET request to a non-RDF resource should include a checksum calculation. Are we saying it's better to do this all the time, but you don't have to?  I'm thinking of large binary resources and the resulting response time.

**Comment by escowles** [comment]
I was thinking that the ETag could use a cached value, but when the client sent a `Want-Digest` header, that would trigger calculating the checksum instead of using the cached value.

But this note definitely doesn't say that, so making that explicit would be good.

**Comment by awead** [comment]
@escowles thanks, yeah, I just read the section about `Want-Digest`. You could re-state something to that effect here if that helps to clarify it.

**Comment by awoods** [comment]
@awead : If you have time for creating a PR adding such text, that would be very appreciated.

**Comment by zimeon** [comment]
@awead : If you are in a PR mood you might also do one to add yourself as a contributor

**Comment by awead** [comment]
@zimeon thanks, I'm honored!

**Comment by awoods** [comment]
Resolved with: https://github.com/fcrepo/fcrepo-specification/pull/155
