### ISSUE TITLE
Creating content from external resources

### ISSUE THREAD

**Issue by awead** [fcrepo/fcrepo-specification#149]
I'm I'm interpreting section 3.8 correctly, external content would only be fetched and copied to the repository if there were an expiration parameter. Otherwise, it is linked a redirect or poxy. Is this correct?

**Comment by escowles** [comment]
Yes, adding the `expiration` parameter would trigger fetching the content, but otherwise an implementation would normally be expected to redirect or proxy the content (though I don't think there's anything in the spec that would stop you from always fetching the content if you wanted to).

**Comment by birkland** [comment]
Well, it *might* download content.  There's an email thread that suggests
that the server has the latitude otherwise "expire" the resource somehow,
which is quite the opposite effect.  I have a personal TODO to create a
couple tickets to hopefully narrow down and clarify the language in this
section.

**Comment by awoods** [comment]
@birkland : Once you create the mentioned tickets/issues... let's close this issue.

**Comment by dannylamb** [comment]
@birkland Do you feel that these issues still need to be created?  Otherwise we'll close this one out.

**Comment by birkland** [comment]
@dannylamb Ah, these dropped off my radar.  I'll create new tickets.  Feel free to close this one any time as far as I'm concerned.

**Comment by birkland** [comment]
@dannylamb I created #210 and #211

**Comment by zimeon** [comment]
Closing in favor of #210 and #211 (thanks @birkland)
