### ISSUE TITLE
Reconcile WAC and the possibility of uncontained resources in Fedora

### ISSUE THREAD

**Issue by zimeon** [fcrepo/fcrepo-specification#163]
The Web Access Control spec relies upon [all documents being contained](https://github.com/solid/web-access-control-spec#containers-and-inherited-acls) and [every root container must have an ACL resource](https://github.com/solid/web-access-control-spec#acl-inheritance-algorithm). The Fedora API spec allows for uncontained resources which creates situations where the WAC rules don't work. Options I can see include:

  * Say that every uncontained resource (that isn't itself an ACL) MUST have an ACL resource (implication for DELETE debate: if a DELETE zapped a parent the server would need to propagate ACL down to orphans)
  * Say that at the end of the WAC inheritance process some default should be used if no ACL was found (question about how that default is configured or set/adjusted)

**Comment by awoods** [comment]
I suspect a pattern similar to [what we currently do](https://wiki.duraspace.org/display/FEDORA4x/Default+Filesystem-based+Policy) could be used even in the case of uncontained resources.

**Comment by zimeon** [comment]
I suspect that the "some default should be used" == [what we currently do](https://wiki.duraspace.org/display/FEDORA4x/Default+Filesystem-based+Policy) option is best but then we need to:

  1. explain the use of a default as it alters the [WAC spec ACL Inheritance Algorithm](https://github.com/solid/web-access-control-spec#acl-inheritance-algorithm)
  2. explain whether this default policy should be transparent, does it [get exposed in Link: rel="acl"](https://github.com/solid/web-access-control-spec#acl-resource-location-discovery) -- I think it should

I think we could reasonably say that where a default ACL is located (and even whether there might be more than one), how it can be changed etc. is implementation specific. From a client perspective you still end up with an ACL for every resource so it would look like WAC.

**Comment by awoods** [comment]
Sounds right, @zimeon .
Next step is to create a PR addressing your points 1 and 2.

**Comment by zimeon** [comment]
Discussion in call: re bullet 2 above there is editors' agreement that there will be always be a `Link: rel="acl"` -- either following WAC inheritance or using default
