### ISSUE TITLE
Requiring acl:defaultForNew?

### ISSUE THREAD

**Issue by awoods** [fcrepo/fcrepo-specification#164]
[acl:defaultForNew](https://github.com/solid/web-access-control-spec#default-inherited-authorizations) - we currently use an assumed inheritance. Is the Fedora spec requiring a change to this other pattern? 

Extracted from: https://github.com/fcrepo/fcrepo-specification/issues/145

**Comment by acoburn** [comment]
`defaultForNew` is another predicate that didn't exist when Fedora's WebAC module was written. Personally, I really like what this offers over an assumed inheritance algorithm. I would note, however, that supporting `defaultForNew` doesn't contradict the use of inheritance in the absence of an ACL.

**Comment by escowles** [comment]
Reading https://github.com/solid/web-access-control-spec#default-inherited-authorizations, it sounds like creating a resource in a container with an `acl:defaultForNew` would apply that ACL to the newly-created resource.

Is that how others are reading it? That seems like an alternative to using inheritance, in that the new resource would have an ACL attached and you would not need to go inspect the container to figure out which ACL to use.

**Comment by acoburn** [comment]
@escowles my reading of this is that, given the triple

    </resource> acl:defaultForNew </some/acl/resource>

That resource would provide a hint to a server implementation such that whenever a child resource is created via POST that new resource would be assigned a triple such as:

    </resource/child> acl:accessControl </some/acl/resource>

Of course if the contents of the POST assigns an ACL, the `acl:defaultForNew` would not apply.

**Comment by awoods** [comment]
@escowles : my reading is slightly different in that no new ACLs are created for resources created under a container with `acl:defaultForNew`, but rather while looking for an effective ACL through the inheritance hierarchy, if an `acl:defaultForNew` is found in that search, the found ACL is used.

The following section offers the specific search algorithm: https://github.com/solid/web-access-control-spec#acl-inheritance-algorithm-example

**Comment by escowles** [comment]
@awoods OK, so if a container has multiple ACLs, the `acl:defaultForNew` triple would mark the one that should apply to child resources?

**Comment by acoburn** [comment]
@awoods I agree that no new ACL resources would be created, but I disagree about applying acl:defaultForNew in the search for an effective ACL. For instance, given this parent resource:

```
</resource> acl:accessControl </acls/private> ;
    acl:defaultForNew </acls/public> .
```

what happens when a client creates a child resource (`/resource/child`) via POST? What is the effective ACL? is there an `acl:accessControl` triple assigned to the child resource?

Or another way to think about this, what if five child resources are created and then the parent resource is PATCHed to contain the triple `</resource> acl:defaultForNew </acls/mixed>` and then five more resources are created? Is the effective ACL different in the first set from the second set?

**Comment by awoods** [comment]
@escowles : correct, and as noted in step 2 of the [algorithm](https://github.com/solid/web-access-control-spec#acl-inheritance-algorithm-example) more than one Authorization may be flagged as `acl:defaultForNew`.

**Comment by zimeon** [comment]
@awoods - I agree that that more than one `acl:defaultForNew` may apply.

@acoburn - I think WAC is silent on creation of new ACL resources for newly created resources, it just says how to find ACL resources from parent containers for resources that don't have their own. Thus, in your example, unless some child resource had an ACL created for it directly (allowed but not specified), all 10 children would see the inherited (at access time) subset of current permissions of the parent container marked `acl:defaultForNew`. (I suspect this confusion is the  reason that the _`acl:defaultForNew` predicate will soon be renamed to `acl:default`, both in the specs and in implementing servers_ ... perhaps a bit of history showing there)

**Comment by zimeon** [comment]
Have asked about [Status of planned `acl:defaultForNew` to `acl:default` change](https://github.com/solid/web-access-control-spec/issues/20) and note that `default` is not currently defined in the ACL vocabulary http://www.w3.org/ns/auth/acl

**Comment by zimeon** [comment]
This has been resolved in the [ACL vocabulary](http://www.w3.org/ns/auth/acl) which now says:

```
    <rdf:Property rdf:about="http://www.w3.org/ns/auth/acl#default">
        <comment>A directory for which this authorization is used for new files in the directory.</comment>
        <domain rdf:resource="http://www.w3.org/ns/auth/acl#Authorization"/>
        <label>default access for things in this</label>
    </rdf:Property>

    <rdf:Property rdf:about="http://www.w3.org/ns/auth/acl#defaultForNew">
        <comment>THIS IS OBSOLETE AS OF 2017-08-01.   See 'default'.
        Was: A directory for which this authorization is used for new files in the directory.</comment>
        <domain rdf:resource="http://www.w3.org/ns/auth/acl#Authorization"/>
        <label>default access for new things in the object</label>
    </rdf:Property>
```

so we should use `acl:default`. Because the WAC spec has not yet been updated I think we need a non-normative note (at least for now) pointing out that we use `acl:default` instead of `acl:defaultForNew`, with the same semantics, in https://fcrepo.github.io/fcrepo-specification/#inheritance. I'll make a PR.
