### ISSUE TITLE
Requiring WebIDs?

### ISSUE THREAD

**Issue by awoods** [fcrepo/fcrepo-specification#166]
The [Solid spec](https://github.com/solid/web-access-control-spec#overview) requires to use of WebIDs.
[We currently support strings and URIs for acl:Agent objects](https://wiki.duraspace.org/display/FEDORA4x/WebAC+Authorization+Delegate#WebACAuthorizationDelegate-Authorizations).

Do we want to change this to WebIDs?

**Comment by acoburn** [comment]
The use of strings for agents is problematic for many reasons. Using IRIs is the right approach here (WebIDs are simply an example -- a good one at that -- for the use of IRIs for referring to agents).

**Comment by dannylamb** [comment]
Is the WebID anything other than an IRI for a profile page?  We have our own in Islandora and don't require one from Fedora per se.

Does this imply that authorization would be done against this IRI which may or may not represent a user account in Fedora?

**Comment by awoods** [comment]
Here is the brief description of [WebID](https://www.w3.org/2005/Incubator/webid/spec/identity/):

> A WebID is an HTTP URI which refers to an Agent (Person, Organization, Group, Device, etc.). A description of the WebID can be found in the Profile Document, a type of web page that any Social Network user is familiar with.
> 
> A WebID Profile Document is a Web resource that must be available as text/turtle [turtle], but may be available in other RDF serialization formats (e.g. [RDFA-CORE]) if requested through content negotiation.
> 
> WebIDs can be used to build a Web of trust using vocabularies such as FOAF [FOAF] by allowing people to link together their profiles in a public or protected manner. Such a web of trust can then be used by a Service to make authorization decisions, by allowing access to resource depending on the properties of an agent, such that he/she is known by some relevant people, works at a given company, is a family member, is part of some group, etc..

I am not sure we can commit to full WebID... but at least require user-URIs.

**Comment by zimeon** [comment]
I think that from a Fedora spec p.o.v., all we need to agree is that there will be agent-URIs that are used to match against these [URIs in WAC](https://github.com/solid/web-access-control-spec#describing-agents). Only in the case of `acl:agentGroup` is there an expectation to be able to resolve that agent-URI to a document describing the group.

Unless there is a compelling reason to continue support strings I would let that go and align with WAC. An implementation could use some unresolvable URI pattern to migrate from strings if necessary.

**Comment by dannylamb** [comment]
:+1: to removing support for strings and expecting URIs
