### ISSUE TITLE
Requiring acl:agentGroup?

### ISSUE THREAD

**Issue by awoods** [fcrepo/fcrepo-specification#167]
The [Solid spec](https://github.com/solid/web-access-control-spec#groups-of-agents) requires 'acl:agentGroup' to reference groups, [whereas we use 'acl:agentClass'](https://wiki.duraspace.org/display/FEDORA4x/WebAC+Authorization+Delegate#WebACAuthorizationDelegate-Authorizations) that references a document of type 'foaf:Group' containing 'foaf:member(s)'

Do we want to change this approach to use 'acl:agentGroup'?

**Comment by acoburn** [comment]
The use of `agentGroup` makes much more sense for referring to groups. `agentClass` seem inappropriate for use with a defined group. (n.b. this predicate did not exist when Fedora's WebACL module was implemented). I would also note that SOLIDWEB uses vcard for groups, not foaf.

**Comment by dannylamb** [comment]
+1 to `acl:agentGroup` for referring to groups.

**Comment by zimeon** [comment]
:+1: to using `acl:agentGroup`

**Comment by dannylamb** [comment]
Is there action required for this issue?  By following SOLIDs recommendations there shouldn't be anything to add to the spec.  Can we just make sure this winds up in the delta document instead?

**Comment by zimeon** [comment]
:+1: agree we don't need anything in spec as we are just following SOLID, should be in delta doc

**Comment by dannylamb** [comment]
Closing for now since this change is included int he delta document and no further action should be required.
