### ISSUE TITLE
Predicate for public access

### ISSUE THREAD

**Issue by awoods** [fcrepo/fcrepo-specification#169]
The [Solid spec](https://github.com/solid/web-access-control-spec#public-access-all-agents) uses 'acl:agentClass foaf:Agent' for public access content whereas we currently use 'acl:agent foaf:Agent'.

Do we want to change?

**Comment by acoburn** [comment]
In my reading of SOLID and WebAC, the correct formulation would be `<> acl:agentClass foaf:Agent`. The use of `<> acl:agent foaf:Agent` does not make a lot of sense.

**Comment by escowles** [comment]
I agree with @acoburn here — I think the `<> acl:agentClass foaf:Agent` usage is a special case to denote anyone, not an indication that we should do something different when we have a particular user or group in mind (in which case we'd continue to use `<> acl:agent <user_or_group_URI>`).

**Comment by dannylamb** [comment]
I agree to this change as well.

**Comment by zimeon** [comment]
Me too, WAC use of  `<> acl:agentClass foaf:Agent` seems like a good approach and I don't see a reason to deviate.

**Comment by awoods** [comment]
Closing this issue as no action is required beyond following the SOLID specification.
