### ISSUE TITLE
Require acl:Append and acl:Control

### ISSUE THREAD

**Issue by awoods** [fcrepo/fcrepo-specification#170]
The [Solid spec](https://github.com/solid/web-access-control-spec#modes-of-access) requires the use of 'acl:Append' and 'acl:Control'. 

Do we want to require the same support?

**Comment by acoburn** [comment]
acl:Append makes sense for cases such as adding membership and/or containment predicates. And acl:Control is very useful for manipulating ACLs themselves.

**Comment by zimeon** [comment]
:+1: to requiring support for `acl:Append` and `acl:Control`. I think we will need text explaining what counts as `acl:Append`, which I think should be any POST/PUT/PATCH that has the net effect of adding (only) to the controlled resource.

**Comment by barmintor** [comment]
I agree with @acoburn about the applicability, and with @zimeon about the necessity of explaining the use of the terms, but I need to think a little about how I would recommend defining `acl:Append` here.

**Comment by escowles** [comment]
👍  to @barmintor's comment — I think POSTs to containers are clearly acl:Appends, but it may be hard to tell if PATCHes and PUTs are.

**Comment by escowles** [comment]
After reading the SOLIC Modes of Access section, I don't think we need to say anything more about `acl:Control` — our usage of it seems to be the same as SOLID's.  So I've just added a note about `acl:Append` with some examples of append operations.
