### ISSUE TITLE
Clarify algorithm for finding authorizations 

### ISSUE THREAD

**Issue by zimeon** [fcrepo/fcrepo-specification#172]
Adding this as a placeholder for possible clarification based on resolution of:

  * Algorithm for finding authorizations in an ACL document - https://github.com/solid/web-access-control-spec/issues/19
  * Default ACLs - https://github.com/fcrepo/fcrepo-specification/issues/163

**Comment by zimeon** [comment]
Per #163 we have resolved the issue of [Inheritance and Default ACLs](https://fcrepo.github.io/fcrepo-specification/#inheritance). By this means we can find the ACL resource for any given resource, which will be an LDP-RS yielding an RDF document containing all the authorization statements necessary to authorize or deny access (though there may be a need to access other resources to expand group ids).

There is no advice in [WAC Representation Format](https://github.com/solid/web-access-control-spec#representation-format), or a response to https://github.com/solid/web-access-control-spec/issues/19, on how to find the set of authorizations in the ACL resource. I don't like the idea of specifying a URI pattern (e.g. following the `#auth1` hash pattern used in the WAC examples) so I propose the following rule:

> ### 5.4 ACL Representation and Interpretation
> 
> ACL resources are represented as described in \[SOLIDWEBAC] [Representation Format](https://github.com/solid/web-access-control-spec#representation-format). Implementations MUST inspect the ACL RDF for authorizations identified by type definition triples of the form `authorization_N rdf:type acl:Authorization`, where `authorization_N` is an authorization. Implementations MUST NOT attempt to resolve `authorization_N` but instead use only statements associated with the authorization in the ACL RDF. The authorizations MUST be examined to see whether they grant the requested access to the controlled resource. If none of the authorizations grant access then the request MUST be denied.

**Comment by escowles** [comment]
@zimeon That sounds good to me.  The only thing I'd like to add is how an implementation can effectively disable access control.  Some options:
1. Not having a root ACL
2. Root ACL doesn't contain any acl:Authorization descriptions
3. Root ACL contains an acl:Authorization that allows all access:
```
<#auth> a acl:Authorization ;
    acl:agentClass foaf:Agent ;
    acl:accessToClass ldp:Resource ;
    acl:mode acl:Read, acl:Write, acl:Append, acl:Control .
```

**Comment by bseeger** [comment]
Can you explain more what this sentence means? `Implementations MUST NOT attempt to resolve authorization_N but instead use only statements associated with the authorization in the ACL RDF`? I'm not clear on what it's saying, but I may not be looking at it from the proper perspective.

**Comment by zimeon** [comment]
@bseeger - I was intending to mean that the server should just the the RDF it got from the ACL resource, even if the authorization is given a URI that is not a local hash URI or bnode (maybe, for some silly reason, it was called `http://example.org/auth1`)

**Comment by zimeon** [comment]
@escowles I lean toward the last of your three suggestions in https://github.com/fcrepo/fcrepo-specification/issues/172#issuecomment-330856391 for disabling access control. I think that would be a non-normative note following some variant of the text I proposed in https://github.com/fcrepo/fcrepo-specification/issues/172#issuecomment-330853850, with modifications to clarify and hopefully address @bseeger 's https://github.com/fcrepo/fcrepo-specification/issues/172#issuecomment-330879492

**Comment by escowles** [comment]
@zimeon That sounds good to me — using the existing conventions for allowing anyone access to any resource seems like a good way to explicitly say that you don't want any access control enforcement.

**Comment by zimeon** [comment]
@escowles - I feel uncomfortable putting in the spec an example that disables access control for write/append/control. How would you feel about making the example disable access control on read for everything, and saying that rules could also be added for other modes?

**Comment by escowles** [comment]
@zimeon I'd be fine with that — though I'll point out that the default fcrepo4 artifact ships without access control of any kind right now...

**Comment by awoods** [comment]
@escowles : Maybe fcrepo4 should include whatever non-normative example you provide in the text... that disables read access?

**Comment by escowles** [comment]
@awoods I thought the webac module had been incorporated into fcrepo4, and it would therefore provide "real" webac functionality out-of-the-box now.   Or are you talking about 4.7.x?

**Comment by awoods** [comment]
@escowles : Yes, webac is now in the core codebase. I was suggesting that the default authorization in the codebase could be aligned with a non-normative example in the spec.

**Comment by escowles** [comment]
@awoods OK, that makes sense.  I'd be 👍 to having the default ACL be what's in [my comment](https://github.com/fcrepo/fcrepo-specification/issues/172#issuecomment-330856391), i.e., completely open, or modified version of what's in the spec that also included a user who could do CRUD.

**Comment by awoods** [comment]
Here is the current [default root Authorization](https://github.com/fcrepo4/fcrepo4/blob/master/fcrepo-auth-webac/src/main/resources/root-authorization.ttl):
```
<> a acl:Authorization ;
   rdfs:label "Root Authorization" ;
   rdfs:comment "By default, all non-Admin agents (foaf:Agent) are denied access (no acl:mode is specified) to all resources." ;
   acl:agent foaf:Agent ;
   acl:accessToClass fedora:Resource .
```
By omitting any `acl:mode` triples, we effectively disable all actions. My suggestion is to potentially align the default root ACL in the codebase with the non-normative example in the spec.

In reading @zimeon's comment, it sounds like the suggestion is to disallow `acl:Read`. However, ACLs grant access. They do not explicitly forbid access.

Therefore, it is not clear to me how to represent @zimeon's suggestion of "disabling read" in any other way than by either disabling everything (as in the current default above), or explicitly enabling `acl:Write, acl:Append, acl:Control` while leaving out `acl:Read`... which seems odd.

Maybe our current default makes sense... unless we would like to change to "all can read, but do nothing else"... which could also be a good non-normative example.

**Comment by escowles** [comment]
@awoods The non-normative example in #320 is exactly what you describe: https://github.com/fcrepo/fcrepo-specification/pull/320/files#diff-eacf331f0ffc35d4b482f1d15a887d3bR1055

I would be fine with that as the default ACL for fcrepo4, too.

**Comment by awoods** [comment]
The circle is complete. Thanks for your patience, @escowles . 
https://jira.duraspace.org/browse/FCREPO-2668
