### ISSUE TITLE
Add ACL to terminology section?

### ISSUE THREAD

**Issue by zimeon** [fcrepo/fcrepo-specification#174]
In [Resource Authorization](https://fcrepo.github.io/fcrepo-specification/#resource-authorization) we talk about ACLs alot -- I think it would be worth adding to terminology. Would mean we also have to reference WAC in the intro sentence.

Additionally, I think we should change the bibliography anchor SOLIDWEBAC to WAC, the spec is called simply [Web Access Control (WAC)](https://github.com/solid/web-access-control-spec#web-access-control-wac) even if its origins are SOLID.

**Comment by acoburn** [comment]
👍  for adding this to the terminology

For the bibliography anchor, however, if you change SOLIDWEBAC -> WAC, that would affect how respec dereferences the anchor `[[SOLIDWEBAC]]` and adds references to the appendix. There is no WAC entry in the respec database: http://www.specref.org/?q=wac, which would mean that the value wouldn't be added to the references section. Which is to say, you're stuck with SOLIDWEBAC as a bibliography anchor.

**Comment by awoods** [comment]
Resolved with: https://github.com/fcrepo/fcrepo-specification/pull/183
