### ISSUE TITLE
Should we say default ACL MUST be resolvable?

### ISSUE THREAD

**Issue by zimeon** [fcrepo/fcrepo-specification#175]
Raised in discussion of #173 with @acoburn:

> If a server MUST supply a default ACL for controlled resources that don't have an ACL defined in the relevant hierarchy, it follows that the server MUST also provide a link to that ACL in the HTTP response headers. Does that imply that the default ACL must be dereferencable?

I think the answer is yes and it seems that this is testable so would be OK to say _MUST_.

**Comment by acoburn** [comment]
One consideration here is the question: how would this differ from or clarify the existing SOLIDWEBAC statement that the root container must have a configured ACL.

**Comment by dannylamb** [comment]
By virtue of an ACL being an LDP-RS, does that not imply it is resolvable?

**Comment by zimeon** [comment]
Given discussion on #198 I no longer agree with my original https://github.com/fcrepo/fcrepo-specification/issues/175#issue-244418219 that ACL _MUST_ be resolvable. However, given the different interpretation of WAC on this issue I think we need to clarify that `rel="acl"` will always point the individual resource ACL (and not one found by inheritance). I have an idea for how to do this so will make a PR to discuss the text.
