### ISSUE TITLE
Versioning is optional: implementations MAY support server-managed or client-managed versioning

### ISSUE THREAD

**Issue by zimeon** [fcrepo/fcrepo-specification#185]
By my read of the current [versioning section](https://fcrepo.github.io/fcrepo-specification/#resource-versioning), support for versioning is _OPTIONAL_. A server _MAY_ support server-managed versioning or it _MAY_ support client-managed versioning -- I don't think that a combination of client and server-managed would make any sense (am I missing a scenario?). Given that I don't think we'd want to mandate support for both server- and client-managed, implementations supporting one will end up incompatible with apps wanting the other, so no support at all might as well be allowed.

I suggest something like the following intro:

> Implementations _MAY_ support resource versioning. Supporting implementations _MUST_ follow the recommendations of the Memento specification [RFC7089] with the additional requirements of this section. All resources involved, including TimeGate and TimeMap resources, are <a>LDPR</a>s.

**Comment by acoburn** [comment]
I do like the idea of requiring some form of resource versioning, but you are correct that, given the current spec language, versioning is, effectively, optional.

I suspect that it would be possible to have a combination of client- and server-managed versioning schemes in a single server implementation, but that does seem somewhat unlikely. FWIW, Trellis is strictly server-managed when it comes to versioning; versioning cannot be disabled and versions cannot be deleted. As such, using Memento TimeGates, a client can access the state of a resource at any moment in time.

**Comment by dannylamb** [comment]
We would need to say that you MUST support at least one of the methods.  

And I could see an implementation providing both by allowing system managed versioning to be switched on through configuration, otherwise it would provide client managed versioning.
