### ISSUE TITLE
How can a client tell if an implementation supports client-managed versioning?

### ISSUE THREAD

**Issue by zimeon** [fcrepo/fcrepo-specification#186]
Does it just have to try a request with an appropriate Link header (see #130, but still will be hard to know whether failure was versioing support something else), know via unspecified means, or should there be some specified means?

This and other discussions of capability discovery (e.g. https://github.com/fcrepo/fcrepo-specification/issues/93#issuecomment-295253188) make me wonder whether we should specify elements of a structured `"...#constrainedBy"` document (of course allowing open-ended extension).

**Comment by acoburn** [comment]
If some form of Versioning is required by the spec, a client can do the following:

1. Create a resource.
2. Perform a HEAD request on that resource
3. If the response headers contain memento headers, then the versioning scheme is server-managed; otherwise, the versioning scheme is client-managed.

If versioning is not required, then a client would need to perform a 4th step (assuming the resource versions aren't server-managed):

4. Try to create a version with the defined link header
5. Perform a HEAD request and inspect the headers (as above).

**Comment by escowles** [comment]
You should be able to do an OPTIONS request on the TimeMap to know whether you can create a version explicitly or not.

**Comment by zimeon** [comment]
I like the [OPTIONS](https://tools.ietf.org/html/rfc7231#section-4.3.7) idea for two reasons:

  1. `OPTIONS *` is explicitly about server-wide capabilities so might be a nice hook for things about "the implementation"
  2. It seems a very clean way to ask about capabilities

BUT, what response headers would indicate support for versioning or not? It seems we'd have to invent something (another Link perhaps?) as I don't think anything currently in the Fedora or Memento specs would cover this (or am I missing something?)

**Comment by acoburn** [comment]
I also like @escowles' suggestion about using an OPTIONS request on a TimeMap resource.

To @zimeon's questions, I don't think there is a need to invent any new headers or Link IRIs. For example, an OPTIONS request to an entirely server-managed TimeMap should respond with something like:

    Allow: GET, HEAD, OPTIONS

And an OPTIONS request to the Memento (LDPRm) would be:

    Allow: GET, HEAD, OPTIONS

While an OPTIONS request to a client-managed TimeMap should respond with either:

    Allow: GET, HEAD, OPTIONS, POST, DELETE, PATCH

or

    Allow: GET, HEAD, OPTIONS, POST, DELETE

depending on whether PATCH is supported on LDPCv resources. Presumably, the client-supported versioning would also respond with an `Accept-Post` header and (if PATCH is supported) an `Accept-Patch` header. That should be sufficient to signal to a client that the TimeMap resource can be manipulated.

Furthermore, if the LDPRm allows `DELETE` when an OPTIONS request targets that resource, that, too, should signal to a client that a resource's versions are client-managed.
