### ISSUE TITLE
Process: Add bullet specifying more relaxed process for minor edits

### ISSUE THREAD

**Issue by escowles** [fcrepo/fcrepo-specification#192]
I agree with @acoburn's [point](https://github.com/fcrepo/fcrepo-specification/pull/191#issuecomment-322059302) about process.  I propose that we update the process document by adding a new bullet at the end:

* Minor updates, such as those that affect only syntax, whitespace, grammar, fix typos, etc. may be merged when a majority of editors have responded with 👍/+1, and no editors have responded with 👎/-1, without waiting for 72 hours.

**Comment by awoods** [comment]
Thanks for the text, @escowles.
https://github.com/fcrepo/fcrepo-specification/wiki/Issue-Resolution-Process/_compare/d606caec9749fb595066d67f4c4668920da4e665...07c4d8b0e6db8d3a473205a85c14efd3fdd95fca

**Comment by zimeon** [comment]
:+1: -- I guess since we are changing the constitution here we should have buy-in from all eds... @dannylamb @barmintor

**Comment by barmintor** [comment]
Syntax changes in normative sections can change the meaning of a requirement, and need to be reviewed as substantive changes I think. Changes that are strictly formatting or whitespace I'm ok with.

**Comment by awoods** [comment]
@barmintor : what do you have in mind regarding "syntax changes in normative sections" changing meaning? Do you happen to have an example in mind?

We can change the new bullet in the [process](https://github.com/fcrepo/fcrepo-specification/wiki/Issue-Resolution-Process/_compare/d606caec9749fb595066d67f4c4668920da4e665...07c4d8b0e6db8d3a473205a85c14efd3fdd95fca) to remove `syntax`... it that makes sense.

**Comment by escowles** [comment]
Based on editors call 8/16: removed "syntax" and "etc": https://github.com/fcrepo/fcrepo-specification/wiki/Issue-Resolution-Process/_compare/d606caec9749fb595066d67f4c4668920da4e665...eccd5ab8118e6fa00a098ee31311c3bbf9a05946
