### ISSUE TITLE
Clarification of interaction model changes

### ISSUE THREAD

**Issue by acoburn** [fcrepo/fcrepo-specification#20]

**Comment by ajs6f** [comment]
My thought here would be to introduce a new constraint that `PATCH` follows the same rules about changing the interaction model as `PUT`. Would that suit?

**Comment by acoburn** [comment]
@ajs6f yes, that would work for me.

**Comment by ajs6f** [comment]
PRs welcome. :)

**Comment by zimeon** [comment]
I agree that constraints on `PATCH` should be same as `PUT` -- as if one were to implement `PATCH` as `GET`-->apply-changes-->`PUT`
