### ISSUE TITLE
Group URIs must be dereferencable

### ISSUE THREAD

**Issue by escowles** [fcrepo/fcrepo-specification#200]
Related to #166, the editors decided that group URIs must be dereferencable, and must be RDF, and must link to member URIs with `vcard:hasMember`.  These are the minimum requirements for clients and servers to be able to figure out which users are included in a group.

**Comment by acoburn** [comment]
Is this requirement different than what SOLID already requires for agent groups?

**Comment by escowles** [comment]
@acoburn No, I don't think it is — but I also think it's helpful to be specific about what functionality we think is essential for performing authorization, since we don't think all of WebID functionality is required.  So I've opened #207 to add a non-normative note saying that, instead of portraying it as diverging from SOLID.
