### ISSUE TITLE
Clarify intent of external content expiration parameter

### ISSUE THREAD

**Issue by birkland** [fcrepo/fcrepo-specification#210]
The current specification draft says that the server SHOULD respect the expiration parameter by copying content.  The external content is explicitly ephemeral in this case, and may disappear.  In general, what sort of guarantee does the repository provide when it returns a successful response to such a request?  Is it the intent of the specification that the repository must make this content durable, and therefore accessible after its expiration date?  Would it be reasonable (and consistent with the intent of the spec) for a repository to remove the corresponding LDP-NR (so that it produces a 410) once the content expires, as an alternative to the copying that it SHOULD do?

**Comment by zimeon** [comment]
ref: last paragraph of https://fcrepo.github.io/fcrepo-specification/#external-content

**Comment by escowles** [comment]
@birkland I think there are two different things going on here:
1. Registering external content to be proxied (where the expiration parameter might just be guidance about how long the content will exist)
1. Ingesting external content by giving the server the URL and expecting it to be retrieved and preserved (where the expiration parameter is used to trigger this behavior).  I'm not sure if this is a good use of the expiration parameter — maybe this should be handled some other way?

**Comment by birkland** [comment]
@escowles I agree with the two different possibilities, and would add that there really isn't any mechanism for the client to express its intent on what strategy the server employs (proxying, copying, redirects, etc).  So the client doesn't know whether the server picks (1) or (2), (or something else) until it happens.  And if the server decides not to include `Content-Location`, then the client might not ever know.   

So the options would be re-cast as:

1. The client provides expiring external content.  The server decides to proxy it, and use the provided expiration data as guidance about how long it will exist.
2.  The client provides expiring external content.  The server decides to retrieve and preserve it.

I believe (2) is a confusing and unintuitive use of the expires header... though acceptable if worded clearly and unambiguously.  The problem is that it's currently ambiguous what the repository will end up doing.

**Comment by dannylamb** [comment]
My reading of that paragraph leads me to believe 2 is the only interpretation because it says the content must be copied.

> Fedora servers receiving requests that would create or update an LDP-NR with a message/external-body content type SHOULD respect the expiration parameter, if present, by copying content.

I'd remove saying the content is copied so that really leaves us with scenario 1, which I think is more in line with the intent of that section.  And it doesn't exclude the content being copied, per se.

**Comment by zimeon** [comment]
I agree with the previous three comments. I think we should clarify the [External Content](https://fcrepo.github.io/fcrepo-specification/#external-content) section to not talk about the upload-by-reference case, case 2, as @dannylamb suggests: https://github.com/fcrepo/fcrepo-specification/issues/210#issuecomment-330258703

I then think we should describe upload-by-reference in the POST and PUT sections with a clearly distinct mechanism, and not think or talk about that case as "external content". (I had thought that we might use `Content-Location` in the request to indicate upload-by-reference but such use would be clearly against the [HTTP definition](https://tools.ietf.org/html/rfc7231#section-3.1.4.2))

**Comment by zimeon** [comment]
Ingest-by-reference choice of request header split out into #236

**Comment by zimeon** [comment]
We have gone round the bush and back on this one now. My sense is that the text in https://fcrepo.github.io/fcrepo-specification/#proxied-vs-copied is now explicit that the presence of the `expiration` parameter means copy or fail:

>  Fedora servers receiving requests that would create or update an LDP-NR with a `message/external-body` content type SHOULD respect the `expiration` parameter, if present, by copying content. If the server is unable to copy the external content, the request MUST be rejected with a 4xx or 5xx status code. 

I propose closing. @birkland ?

**Comment by birkland** [comment]
I dislike the use of `expiration` for this purpose (as it carries unwanted semantics), but at least the text is more clear as of #269 to mean "copy or fail", which is the important part!
