### ISSUE TITLE
Clarify responses to external content requests with expiration date

### ISSUE THREAD

**Issue by birkland** [fcrepo/fcrepo-specification#211]
The specification mentions that the repository SHOULD respect the expiration parameter by copying content.  Presumably, this could be a long-running process (for large resources), or could fail.  In this case, a `202` 'Accepted' response is most appropriate.  Does the specification provide any guidance as to the information provided by the repository in such a response?  For example, how do clients determine whether a request ultimately succeeds or fails?  If the request intends to create an LDP-NR by POSTing to a container, how does the client discover the URI of the newly created resource, if the operation ultimately succeeds?

**Comment by dannylamb** [comment]
> For example, how do clients determine whether a request ultimately succeeds or fails?

@birkland I'm extremely interested in understanding how this would be achieved.  Certainly a message will be emitted for each successful operation, but I have no idea how an implementation would/could line that up with the specific request that kicked off an asynchronous process.

**Comment by escowles** [comment]
[RFC 7231](https://tools.ietf.org/html/rfc7231#section-6.3.3) says:
> The representation sent with this   response ought to describe the request's current status and point to (or embed) a status monitor that can provide the user with an   estimate of when the request will be fulfilled.

So, maybe this would be the URI where the resource will be created, so the client can poll it to see if it's been created (200), not been created yet (404) or failed (409? 500?).

Otherwise, it seems like a client would need to wait for a message to be emitted to know if the request succeeded, and would otherwise have no way of knowing if it had failed or not.

**Comment by zimeon** [comment]
Though there has be significant work on the [External Binary Content](https://fcrepo.github.io/fcrepo-specification/#external-content) section, I do not think this issue is resolved yet

**Comment by awoods** [comment]
As mentioned above, a 202 response for asynchronous processes seems both appropriate and well-documented in [RFC 7231:6.3.3](https://tools.ietf.org/html/rfc7231#section-6.3.3)

It seems out of scope for the Fedora specification to define how implementations should handle asynchronous processes.

I would be inclined to close this issue, deferring to the HTTP specs.
