### ISSUE TITLE
Creating versions with PUT

### ISSUE THREAD

**Issue by escowles** [fcrepo/fcrepo-specification#215]
These lines from the LDPRv PUT section:
https://github.com/fcrepo/fcrepo-specification/blob/master/index.html#L614-L632

Are verbatim copies of these lines from the LDPRv GET section:
https://github.com/fcrepo/fcrepo-specification/blob/master/index.html#L581-L599

Is the intention to say that if a client includes the `Accept-Datetime` header in a PUT request, that the server may handle the PUT operation as usual, and also create a version?

**Comment by bbpennel** [comment]
Also of note is that for this PUT request, Accept-Datetime is potentially being used to provide a timestamp for the new memento.  Meanwhile Memento-Datetime is used for the same purpose in POSTs against LDPCv's.  
https://fcrepo.github.io/fcrepo-specification/#ldpcvpost  

bseeger pointed out that in the specification, Memento-Datetime is noted as a response header while Accept-Datetime is a request header, so it may make sense to switch headers for POSTs.
https://tools.ietf.org/html/rfc7089#section-2.1.1

**Comment by bseeger** [comment]
It would be great to have some clarification on this as it will start to hold us up soon.  It isn't clear based on these paragraphs exactly how to trigger versioning on a LDPRv, so it would be good to understand the intentions here.   ( https://github.com/fcrepo/fcrepo-specification/blob/master/index.html#L603-L612  as well as what @escowles links to above)

**Comment by zimeon** [comment]
I agree with @bbpennel that we need to be consistent about what request header is used to indicate the datatime for a LDPRm created. Since use in [LDPRv PUT](https://fcrepo.github.io/fcrepo-specification/#httpput)/LDPCv POST is not covered by the Memento spec., I think it would be legitimate to use either `Accept-Datetime` or `Memento-Datetime` but neither are perfect.

  * pro `Accept-Datetime` - defined in Memento spec as a request header, whereas `Memento-Datetime` is defined as a response header
  * pro `Memento-Datetime` - more consistent semantics of "this is the exact time for this Memento" (whether read or created) which is different from the conneg semantics of `Accept-Datetime` on read

I think I lean slightly towards `Memento-Datetime` for PUT/POST.

**Comment by zimeon** [comment]
To @bseeger's https://github.com/fcrepo/fcrepo-specification/issues/215#issuecomment-329491574 , I agree it isn't clear. My sense is that the intention is that in the server-managed model it is a (hidden) server config that means a Memento is created on PUT, there is no client request indication needed. In the client-managed model I think there is a need to flag whether or not the old version becomes a Memento (with timestamps all automatically handled) or whether with a given `Memento-Datetime` (or `Accept-Datetime`) header a specifically timestamped Memonto is written into history. (I see server-managed and client-managed as either/or, I don't see how they would sensibly mix, but I'm not sure whether there is general agreement on this)

**Comment by birkland** [comment]
Quoting @zimeon: 
> (I see server-managed and client-managed as either/or, I don't see how they would sensibly mix, but I'm not sure whether there is general agreement on this)

If I recall correctly from the early days of the spec drafting (when it was still a google doc), the concern was import/export.  So the use case was importing a versioned resource (i.e. all past versions) into system where it is typically server-managed.

**Comment by escowles** [comment]
I also think the old version of the Modeshape impl was nice (a bit confusing, but nice): versioning was client-managed by default.  But a client could add a mixin to a resource to turn on server-managed versioning for that resource.

**Comment by zimeon** [comment]
@birkland - I think for the import use case one might want to be able to switch the server from one mode to the other (turn off server managed versions for the import, turn then on going forward)?

**Comment by birkland** [comment]
@zimeon  I'm not sure.  I believe it was Rob Sanderson who brought it up.  I don't remember the use cases.

In any case, the API alignment sprinters had a meeting today, and it became apparent that POSTing to an LDPCv is probably the canonical way to do it.  That would eliminate interaction with the LDPRv entirely and render the question moot, I believe.

**Comment by barmintor** [comment]
The client managed models, as I recall them:

HTTP POST to LDPCv, no entity: mint a new version as of current date time
HTTP PUT to LDPRv, with entity: create a retrospective version as of date time indicated in URI
[none]: the server manages versions, we the possibility of mixin interaction models to indicate this

I am of @zimeon's mind about the headers I think: `Accept-Datetime` on GET/HEAD requests, `Memento-Datetime` on POST/PUT requests.

**Comment by birkland** [comment]
@barmintor There were some concerns questions/over `PUT` to an LDPRv at a recent sprinters meeting.   It seemed `POST` to an LDPCv _with_ an entity body would be a more straightforward way to create an explicitly-provided version.  Thinking about it from a web architecture perspective, it (`POST`, an unsafe method) would end up invalidating any caches for the LDPCv (ince its representation will change, having added a new containment member)... which is exactly what one would want to happen.  `PUT` on the LDPRv (to create a version) doesn't change the state of the LDPRv; so it's a little bit odd in that respect.

**Comment by birkland** [comment]
Also, PUT to an LDPRv is a bit problematic for creating a memento because:

> 4.2.4.1 If a HTTP PUT is accepted on an existing resource, LDP servers must replace the entire persistent state of the identified resource with the entity representation in the body of the request.

So it would not only create the retroactive version as a memento (what we want), but also change the state of the LDPRv itself (not what is wanted)

**Comment by barmintor** [comment]
I was thinking PUT to create (ie, to the prospective URI), but it's clear y'all are on top of this issue - I just wanted to clarify the intentions!

**Comment by dannylamb** [comment]
I can throw up a PR to attempt this with POST and `Memento-Datetime` if we want to push this forward.

**Comment by csarven** [comment]
I also thought that `Memento-Datetime` would be more appropriate in the request of a write operation. It is a "request" after all, and needless to say the server is not obligated to retain that value. The response of the request may use that value or return a different value - perhaps even something that's close to the requested date.
