### ISSUE TITLE
Create non-normative text suggesting Cache-Control for persistence fixity.

### ISSUE THREAD

**Issue by birkland** [fcrepo/fcrepo-specification#218]
When using `Want-Digest` for persistence fixity, the client wants the server to compute (or otherwise verifiably produce) a checksum.  The client ought to be advised that it `SHOULD` use `Cache-Control: no-cache` so that [no intermediate caches/proxies will return a cached response](https://tools.ietf.org/html/rfc7234#section-5.2.1.4).

**Comment by zimeon** [comment]
This seems like a sensible addition (though we can't use the suggested RFC `SHOULD` in the non-normative section)
