### ISSUE TITLE
License CC-BY 3.0 or 4.0 ?

### ISSUE THREAD

**Issue by zimeon** [fcrepo/fcrepo-specification#22]
Spec has 3.0, but the current CC-BY is 4.0 so would suggest updating unless there is a particular reason not to (detailed comparison at https://wiki.creativecommons.org/wiki/License_Versions#Detailed_attribution_comparison_chart )

**Comment by acoburn** [comment]
The CC statement is added automatically by `respec`. If you can figure out how to modify that value, I would be in favor of changing to 4.0: https://github.com/w3c/respec/wiki/User's-Guide

**Comment by acoburn** [comment]
It looks like overriding the copyright statement is configurable: https://github.com/w3c/respec/blob/develop/js/w3c/templates/headers.html#L127-L129
