### ISSUE TITLE
Intentions of resource versioning section

### ISSUE THREAD

**Issue by zimeon** [fcrepo/fcrepo-specification#222]
I think the current introduction to [resource versioning](https://fcrepo.github.io/fcrepo-specification/#resource-versioning) is inadequate:

> Implementations MUST provide resource versioning as per [RFC7089] with the following additional requirements:

I think it is OK to say that implementations MUST provide **access** to resource versions following [RFC7089], but we need also to say something about the Fedora API additions that specify an **LDP-based model** for versions and that specify options for **creation** of resource versions. Since the patterns for resource version creation are optional or left implementation defined, it seems that support for versions is effectively optional, but if done then the access and model aspects MUST be followed.

Here is a first stab at extending the intro to include the above elements and high-level view of the model (which may reveal that I don't understand it properly ;-) ):

> This section specifies an LDP-based model for resource versioning, and describes server-managed or client-managed [implementation patterns](https://fcrepo.github.io/fcrepo-specification/#implementation-patterns) to control the creation of resource versions. Each versioned resource (LDPRv) is contained within one or more version containers (LDPCv). Each LDPCv MUST contain only the LDPRv and zero or more Mementos (LDPRm) of that LDPRv.
> 
> Implementations MUST provide access to resource versions following the Memento specification \[RFC7089] with additional requirements outline below.

**Comment by bseeger** [comment]
LDPRv is synonymous with LDPR and cannot be w/in the LDPCv.   The LDPCv contains the LDPRm's for a LDPRv, but the LDPRv lives elsewhere.  That's at least how I understand it to be.

**Comment by zimeon** [comment]
Thanks @bseeger ! I think the current spec does read better with your interpretation so I agree was probably intended that way.

The approach of doing an empty POST to make a LDPRm copy makes much more sense in this interpretation but does seems oddly content-hashed-storage centric.

**Comment by zimeon** [comment]
I think the move of text from the LDPCv section to the top of the versioning section in #275 addresses this issue. Closing.
