### ISSUE TITLE
Server-managed versioning required?

### ISSUE THREAD

**Issue by escowles** [fcrepo/fcrepo-specification#231]
4.1.3.1 Versioned Resources / PUT / General says:
> An LDPRv may support PUT. An implementation receiving a PUT request for an LDPRv must both correctly respond as per [LDP] as well as create a new LDPRm contained in an appropriate LDPCv.

That sounds like we are requiring server-managed versioning when an LDPR has versions and receives a PUT request.  Should we change that to:
> An LDPRv may support PUT. An implementation receiving a PUT request for an LDPRv must correctly respond as per [LDP] and may also create a new LDPRm contained in an appropriate LDPCv.

**Comment by zimeon** [comment]
:+1: I'd go straight to PR...

**Comment by birkland** [comment]
Would that also extend to PATCH or POST?

**Comment by escowles** [comment]
@birkland There isn't the same language in the versioning section relating to PATCH and POST (which are required methods, unlike PUT).  But I could add a similar note for those methods.

**Comment by escowles** [comment]
Overcome by #225
