### ISSUE TITLE
Identifying LDPCvs

### ISSUE THREAD

**Issue by bbpennel** [fcrepo/fcrepo-specification#233]
Currently LDPRvs and LDPRms are identifiable by their headers, in the first case by the VersionedResource link header, and in the second case by memento headers.  It does not seem like there is currently a way for clients to identify an LDPCv as different from any other LDPC, except perhaps indirectly from its `Accept` header including `application/link-format`.

Given that LDPCvs have a number of interactions that are unique to them from other LDPRs, I wonder if it would make sense to require they respond with an interaction model or other Link header, in a similar way to `http://fedora.info/definitions/fcrepo#VersionedResource`?

**Comment by birkland** [comment]
This would be helpful for messaging too.  If a client receives a message, should/would there be an rdf type that distinguishes it as an LDPCv?

**Comment by bbpennel** [comment]
@birkland I don't think LDPRms would currently be identifiable from non-versionable LDPRs based on RDF types, although being able to do so when filtering messages on rdf type would be very helpful.

**Comment by bseeger** [comment]
@bbpennel  - just a point of clarification -  I don't think that LDPRv's have to return 
a link header containing `http://fedora.info/definitions/fcrepo#VersionedResource`.  They can and it's pretty useful, but I don't think one needs to via the spec.  Via the spec, the only indication that it's a LDPRv is that there's a timegate / timemap link in the headers.

**Comment by awoods** [comment]
Providing `Link: some-type; rel="type"` for the Memento-related resources (timemap, timegate, memento) seem like helpful additions.
...with the following types: http://mementoweb.org/ns.rdf

**Comment by zimeon** [comment]
I agree with @awoods above, adding type `http://mementoweb.org/ns#TimeMap` for the LDPCv would seem very clear.
