### ISSUE TITLE
Modeshape Impl: Why does F4 use 'sha1' instead of 'sha' for SHA-1 digests?

### ISSUE THREAD

**Issue by zimeon** [fcrepo/fcrepo-specification#235]
The [F4 docs](https://wiki.duraspace.org/display/FEDORA4x/RESTful+HTTP+API+-+Containers#RESTfulHTTPAPI-Containers-post-example4) use `sha1` as the digest name for SHA-1 digests. However, [RFC3230](https://tools.ietf.org/html/rfc3230#section-4.3.2) uses `SHA` (the value is case insensitive) and so does the [IANA registry](https://www.iana.org/assignments/http-dig-alg/http-dig-alg.xhtml) (`sha256` and `sha512` are also defined, there is no mention of `sha1`). If the Fedora API says "follow RFC3230" then I think that means using `sha`.

**Comment by awoods** [comment]
Good catch. We should be using `SHA` (https://tools.ietf.org/html/rfc3230#section-4.1.1)

**Comment by escowles** [comment]
This is an issue with the Modeshape implementation, not the spec.  I've created a JIRA ticket to track this issue: https://jira.duraspace.org/browse/FCREPO-2651
