### ISSUE TITLE
Use Location header for ingest-by-reference

### ISSUE THREAD

**Issue by escowles** [fcrepo/fcrepo-specification#236]
The Location header seems to be defined only for responses (https://tools.ietf.org/html/rfc7231#section-7.1.2), so we can use it for requests to indicate that the server should retrieve the URL and ingest it.

Separating this out from the external-content proxying use case should reduce confusion.

**Comment by zimeon** [comment]
I agree that we should clearly separate out the ingest-by-reference from the proxy cases. So far I think `Location` looks good, but if it turns out no to be then we should probably invest a new header for ingest-by-reference.

**Comment by barmintor** [comment]
Here's my worry here:
1. an implementation doesn't have to support this behavior, but
2. there's no such thing as `Accept-Location`

Should this be an implementation issue instead of a spec issue?

**Comment by barmintor** [comment]
Here are things that I think have consensus:
1. LDP-NR HEAD/GET response includes `Content-Location: foo` means the content is proxied
2. LDP-NR HEAD/GET response includes `Location: foo` means the content is redirected
3. LDP-NR HEAD/GET response includes neither `Content-Location` or `Location` means it is local as of the request
4. `Content-Type: external-body` is the only mechanism we've identified in HTTP 1.1 that allows the server to look elsewhere for the entity
5. the `expiration` parameter on `external-body` may be ambiguous as to whether copying or simply temporality of access is indicated
6. the `Expires` header indicates cache lifespan, and thus cannot be used to indicate actual end of availability

Given the above, would it be clearer to say the `expiration` parameter `SHOULD` result in copied content or an error (as an unsupported `Content-Type1), and advise with recourse to 1-3 above how a client should be able to identify the state of proxying/redirection/hosting in an informative note? As much as I would like to support temporary Location values in Cavendish with an automatic 410, I can't see a cache-friendly way to do that, so maybe the situation is less ambiguous than I've tried to claim.

**Comment by escowles** [comment]
I agree with the list of items in @barmintor 's [comment above](https://github.com/fcrepo/fcrepo-specification/issues/236#issuecomment-338410768).  I think that leaves us with two options:

1. Use `Content-type: message/external-body` with an `expires` parameter to indicate that content should be copied into the repository.  This overloads the mechanism for creating a reference to external content.
2. Use `Location` to indicate remote content that should be ingested.  This separates the two tasks, which I think might reduce confusion.  But it uses an undefined request header, which as we've seen with HTTP 1.1, might be defined to preclude our usage at any time.

So, given those options, I'm in favor of option 1.  I think we should be explicit about the `expires` parameter to address the concerns raised by @birkland, saying something along the lines of:

* If an `expires` header is present, the remote content should be retrieved and treated as though it were in the body of the request.  If the server cannot do this, it must fail the request, and include a constraints document if this is a policy/implementation issue (e.g., only accepting local content).
* In the absence of an `expires` header, the server may provide access to it by ingesting, caching, or proxying.

**Comment by barmintor** [comment]
@escowles does "ingesting" include redirect strategies for the actual content? This has authz implications.

**Comment by escowles** [comment]
@barmintor I don't know if there is a use case for redirecting instead of proxying the content.  If you can't proxy the content because of authz issues, could you get the Digest header you'd need to respond to a HEAD request?

More broadly, all of the remote content approaches have auth issues (and other related issues around the IP address, user agent, accept headers, etc., etc. differing from the client and possibly resulting in different responses from the external content than the client would get).

**Comment by barmintor** [comment]
@escowles here's my thinking:

> could you get the Digest header you'd need to respond to a HEAD request?

You might be deferring calculation, so maybe. But providing a checksum and serving the content are also different security considerations. If I only redirect to file URIs (essentially expecting a client treating NAS like FTP), then I'm less worried about what file paths are appropriate. If I'm proxying, then I have to make sure those paths are acceptable.

**Comment by zimeon** [comment]
I do not have very strong feelings for the choice between 1) `Content-type: message/external-body` with an `expires` parameter or 2) use of `Location` in request. While I'd previously beed inclined towards `Location` I find the caution in @escowles' https://github.com/fcrepo/fcrepo-specification/issues/236#issuecomment-341397277 quite persuasive.

I think we should keep this issue focused on the ingest header question, perhaps fork the discussion of proxy vs redirect and Digest issues around that?

**Comment by barmintor** [comment]
@zimeon I'm fine with splitting the conversation, but I don't want to lose the thread of redirection - one of the most strident points of opposition to external `file:` URIs in FCR3 was the necessity of authorization for Fedora itself around what were appropriate paths.
