### ISSUE TITLE
Require support for external content with access-type=URL

### ISSUE THREAD

**Issue by escowles** [fcrepo/fcrepo-specification#237]
* Strengthen requirement for external content to MUST, and also require support for access-type=URL
* Strengthen requirement for Want-Digest, etc. for external content to a MUST
* Non-normative note that an implementation may proxy, or copy, or otherwise make permanent external content

**Comment by barmintor** [comment]
If `access-type=URL` is a redirect, does the resulting LDP-NR need to support `Want-Digest`, or does the resource identified in the URL parameter need to support `Want-Digest`?

EDIT: that is to say, if I support this by returning the location in the request's `URL=` parameter as the subsequent response's `Location` header, which resource ought to provide these headers (`Digest`, `Content-Length`, etc)?

**Comment by awoods** [comment]
If you are proxying the content, then Fedora should be providing the `Digest` and `Content-Length` headers.

If you are "redirecting", I think it is fair to assume that Fedora can not guarantee that the external server will support the required headers and therefore, I would suggest that the required headers be the responsibility of the Fedora endpoint, not the external endpoint.

**Comment by escowles** [comment]
I would say in both cases that the Fedora response needs to include those headers.  If the original server provides them, I think they could be copied (that is, I don't think it's Fedora's responsibility to re-calculate the checksums).
