### ISSUE TITLE
Disabling Versioning while retaining Mementos

### ISSUE THREAD

**Issue by awoods** [fcrepo/fcrepo-specification#240]
One approach that has been discussed for disabling versioning on a resource is to delete the LDPCv (TimeMap), which has the effect of:
- Removing the TimeMap
- Removing all Mementos (LDPRm) associated with the original resource (LDPRv)
- Removing the `fcrepo:VersionedResource` Link header from the original resource

In the case where the client wants to disable versioning, while also retaining the original resource's mementos, a different approach is required.

The suggestion for addressing this use case discussed on the [2017-10-05 Fedora Tech call](https://wiki.duraspace.org/display/FF/2017-10-05+-+Fedora+Tech+Meeting) was to use WebAC to disable `write` access for all users (system or otherwise) on the TimeMap.

**Comment by awoods** [comment]
If there is @fcrepo/editors agreement on the WebAC approach to disabling versioning, we can move forward with a PR.

**Comment by escowles** [comment]
What does "disable versioning, while also retaining the original resource's mementos" mean? Preventing the creation of new versions?

**Comment by awoods** [comment]
I believe it means: no longer allowing the creation of new versions, but persisting the previously created versions.

The current approach to disabling versioning involves deleting the LDPCv, and by extension, all of the previously created versions.

**Comment by zimeon** [comment]
It seems reasonable to me that removing `write` access to the LDPCv would disable client managed versioning. 

In various possible server managed schemes I can imagine that there would never be client write access to the LDPCv or LDPRv so using such access as a flag for control would seem implementation specific.

**Comment by escowles** [comment]
I haven't heard about any use cases for disabling versioning, or retaining versions while doing so.  But using WebAC to disable POSTing to the LDPCv (as you could do for any LDPC) seems reasonable.  This seems like a natural outcome of being able to modify the ACL of the LDPCv, so I'm not sure if we need to specify anything here or not.

**Comment by awoods** [comment]
Nothing to be specified. In the case of client-managed versioning, removing `write` access to the LDPCv should do the trick.
