### ISSUE TITLE
Group and order subsections under Resource Versioning

### ISSUE THREAD

**Issue by csarven** [fcrepo/fcrepo-specification#247]
Editorial change:

I think readability can be improved by grouping and ordering subsections under "Resource Versioning" by first listing the read methods (`GET`, `HEAD`, `OPTIONS`), and then the write methods (`POST`, `PUT`, `PATCH`, `DELETE`).

**Comment by awoods** [comment]
@csarven : This sounds like a good suggestion. If you would be willing to provide a PR, that would be helpful.
Thanks!

**Comment by zimeon** [comment]
Subsumed in #274, closing.
