### ISSUE TITLE
Relationship to LDP

### ISSUE THREAD

**Issue by zimeon** [fcrepo/fcrepo-specification#25]
The (non-normative) abstract says this specification refines LDP, but I think there should be a _normative_ statement about what that means. Is it that "The Fedora API specification follows the LDP specification except where described in this document"?

It might also make sense to make a clear statement about the relation to versions of the LDP specification. The reference is to LDP 1.0 so I assume the statement is that this specification builds on and refines LDP 1.0 (and will still do so when LDP puts out their 1.1).

Various terms/acronyms in this document are used without definition which I assume means they are as defined in LDP. Should there be an explicitly linked statement along the lines of "Terms from LDP ([2 Terminology](https://www.w3.org/TR/ldp/#terms)) are used in this document."?

Finally, and I know this one is awkward: This specification would be about a zillion times easier to read/follow if the LDP section numbers references linked directly to the appropriate LDP sections. I understand the desire to do references the W3C way, but it really hampers usability. A compromise might be to keep the "\[LPD\]" linked to the references, but then link the actual section numbers to the points in the LDP spec?

**Comment by ajs6f** [comment]
This seems like a couple of diff issues, all good to raise. I'll break them out as I see them:

1. I'm fine with that. That _is_ what we want to say, to my understanding. I would be a little more concrete about it and combine the next point with it; "A Fedora server is a conforming LDP 1.0 server except as described in this document."
2. Yep. That would be good to say explicitly, see above.
3. That seems fine to me, but we should do that by making use of definition lists in the usual way, so as to add functionality and not just text.
4. No opinion. I don't find it hard to read, but I like to eat pickled herring with horseradish, so I'm not the best example.

**Comment by awoods** [comment]
1. Agreed. A clarifying, normative statement would be helpful.
2. Agreed. A clarifying statement relating this document with the LDP 1.0 spec makes sense. We would want to revisit this document as new versions of LDP are published.
3. @ajs6f, can you further describe what you have in mind here?
4. Agreed. Leaving the [LDP] references, but also adding direct links from the section numbers would be low-hanging and useful.

**Comment by ajs6f** [comment]
3. @zimeon offered the idea of a general statement. I'm saying that that would be good, and additionally we should put definitions in our lists for these LDP-sourced terms and in those definitions we should say, "This is from LDP section blah." Does that not make sense?

**Comment by awoods** [comment]
@ajs6f : If by "we should put definitions in our lists", you are saying we should include a "Terminology" section like: https://www.w3.org/TR/ldp/#terms redirecting to the LDP spec as appropriate, then, yes, that makes complete sense.

**Comment by ajs6f** [comment]
Sure.
