### ISSUE TITLE
Is there a use case for POST without request body into LDPCv?

### ISSUE THREAD

**Issue by csarven** [fcrepo/fcrepo-specification#251]
re https://fcrepo.github.io/fcrepo-specification/#ldpcvpost

> If an implementation does not support POST with a request body

What's the use case for `POST`ing to LDPCv with zero length body and why is this treated as a separate case to any request (with or without body)? I think the constraints on the LDPCv is orthogonal here. Needless to say, it applies to any situation where the request doesn't comply with the constraint.

See also issue #250

**Comment by escowles** [comment]
The main scenario for POSTing to the LDPCv without a body is to create a version that represents the current state of the versioned resource.  Support for POST with a body supports creating historical versions (either versions created outside the repository, or importing versions from another system, a backup, etc.).

**Comment by escowles** [comment]
@csarven We're clearing out old issues as we finalize the candidate recommendation — please feel free to open a new issue if your concerns aren't addressed in the draft.
