### ISSUE TITLE
Detach URI-R and URI-G from the same resource

### ISSUE THREAD

**Issue by csarven** [fcrepo/fcrepo-specification#252]
re https://fcrepo.github.io/fcrepo-specification/#terminology

> An LDPR that is simultaneously a Memento URI-R and a Memento TimeGate.

and https://fcrepo.github.io/fcrepo-specification/#LDPRv-general (emphasis on the "itself"):

> A versioned resource for this document provides a TimeGate interaction model as detailed in the Memento specification [RFC7089] and indicated by an HTTP header Link: rel="timegate" referencing **itself**.

Evidently, this follows Memento's "Pattern 1 - The Original Resource Acts as Its Own TimeGate" https://tools.ietf.org/html/rfc7089#section-4.1

In the LDP centric system, I think this overloads the affordances of a given LDPR (URI-R). Pragmatically speaking, an implementation will have to allow Datatime Negotiation on any given URI-R(=URI-G). Consequently this means URI-R (URI-G) has to allow `Vary: Accept, Accept-Datetime`. If the request has the `Accept-Datetime` header it'll respond as a URI-G, if not, a URI-R (LDPR) as usual. The out of the box requirement here is that, it enforces a system where URI-R and URI-G must reside on the same server. The other requirement here is to be able to differentiate between the representations that URI-R and URI-G gives back. While this can work out, it enforces a particular system with more complex architecture. That approach could instead be an implicit *MAY* if the following approach is favoured for simplicity (hence a *MUST*):

Memento's "Pattern 2 - A Remote Resource Acts as a TimeGate for the Original Resource" https://tools.ietf.org/html/rfc7089#section-4.2 , hence URI-R and URI-G are different LDPRs, and breaks away from the constraint on centralisation (ie. URI-G may or may not be on the same server, but there is at least that possibility) and overloading resources.

Proposal: detach URI-R from URI-G.

**Comment by zimeon** [comment]
We have, for the time being at least, not to detach URI-R from URI-G in the Fedora specification. This matches our desire to be concrete and make Fedora implementations as interoperable as reasonable.
