### ISSUE TITLE
Should we say datetime negotiation on TimeGate MUST use 302 not 200?

### ISSUE THREAD

**Issue by zimeon** [fcrepo/fcrepo-specification#258]
In discussion with @hvdsomp today we noted that the Memento spec is quite permissive on how one gets a Memento from datetime negotiation on a TimeGate. I think in the Fedora/Linked-Data world we would not want to have a 200 response with a Memento, I think we should thus be explicit and say that a 302 redirect is expected (would go in https://fcrepo.github.io/fcrepo-specification/#LDPRv-get-request).

**Comment by hvdsomp** [comment]
I think you should absolutely do that, especially if you decide to make URI-R and URI-G coincide.
