### ISSUE TITLE
Candidate Recommendation Release tasks

### ISSUE THREAD

**Issue by awoods** [fcrepo/fcrepo-specification#261]
* Push master branch of https://github.com/fcrepo/fcrepo-specification/blob/master/index.html to fedora.info
* Email community
  * Detail next steps
* ~~Configure SSL on fedora.info~~ (see #151)
* ~~Update https://github.com/fcrepo/fcrepo-specification/blob/master/README.md~~ (see #265)
  * ~~Add details on status and process for submitting suggestions~~

**Comment by zimeon** [comment]
I think this was done:
  * spec was updated: http://fedora.info/spec/ -> https://fedora.info/2017/11/27/spec/
  * email was sent: https://groups.google.com/forum/#!topic/fedora-tech/byNvqw_SSh8
