### ISSUE TITLE
Editorial guidelines for HTTP verb order and anchor style

### ISSUE THREAD

**Issue by escowles** [fcrepo/fcrepo-specification#274]
* Order HTTP verbs: GET HEAD OPTIONS POST PUT PATCH DELETE
* Anchor style: hyphenated-lower-case
* Add notes at the bottom of the README

**Comment by zimeon** [comment]
PR or PRs for both verb order and anchor renaming should be delayed until the current flock of PRs are merged -- else merges will fail
