### ISSUE TITLE
Link@rel - format and absolute URIs

### ISSUE THREAD

**Issue by zimeon** [fcrepo/fcrepo-specification#28]
Starting with [section 1.2](http://fcrepo.github.io/fcrepo-specification/#httpPATCH) there are `Link@rel="ldp:constrainedBy"` style mentions of Link headers. I think these should be written `Link: rel="http://www.w3.org/ns/ldp#constrainedBy"` etc. 

  * Maybe I'm missing something but I think the `Link@rel` style is just an xpath-like shorthand that originated when dealing with things like Atom, not the best way to describe HTTP link headers
  * There is no notion of URI prefixes in Link headers per [LDP](https://www.w3.org/TR/ldp/#ldpr-resource) or [RFC5988](https://tools.ietf.org/html/rfc5988#section-5.3) _"Note that extension relation types are REQUIRED to be absolute URIs in Link headers..."_. So I think any relation not in the [IANA Link Relations registry](http://www.iana.org/assignments/link-relations/link-relations.xhtml) should be an absolute URI.

**Comment by ajs6f** [comment]
+1 : you are quite right. This was a shorthand that escaped too far.
