### ISSUE TITLE
Messaging SPI - support required? and clarification

### ISSUE THREAD

**Issue by zimeon** [fcrepo/fcrepo-specification#29]
The start of [Section 6: Messaging SPI](http://fcrepo.github.io/fcrepo-specification/#messaging-spi) says "This section is non-normative." -- I assume this means just the intro paragraph and not the whole of section 6? If so then I'd move that paragraph into a 6.1 (like [5.1](http://fcrepo.github.io/fcrepo-specification/#atomic-operations-introduction) with that standard "This section is non-normative." line. That will make it clear that the SPI is still a required part of the overall specification.

The term "SPI" was new to me on reading this spec, I see from a little searching (e.g. http://stackoverflow.com/questions/2954372/difference-between-spi-and-api & https://en.wikipedia.org/wiki/Service_provider_interface ) that is comes from the Java world which perhaps explains why I didn't know it. I think it would be worth pointing out explicitly the intention here is to specify an pattern and a serialization, but that the actual interface will be implementation specific.

I'd be happy to propose a change if my understanding is correct.

**Comment by ajs6f** [comment]
All of this sounds right to me, but I'd like to hear from @acoburn just to make sure (he did most all of the work on that part).

**Comment by ajs6f** [comment]
Be aware that RESPEC has some functions for autolabelling things as "non-normative"-- you put an "informative" class on that element.

**Comment by acoburn** [comment]
To be honest, I think "SPI" is a misnomer here. @awoods started using that term, so maybe he has a comment on its use. I'd be in favor of dropping that and just calling the section "Messaging".

And yes, the non-normative part is just the paragraph that appears between 6 and 6.1. Perhaps adding a new "6.1 Introduction" and putting the non-normative language under that would clarify things. We definitely want the "Emitting Messages", "Message Data" and "Message Serialization" sections to be normative language.
