### ISSUE TITLE
Clarify response to unsupported algorithm given in Want-Digest: request header

### ISSUE THREAD

**Issue by sprater** [fcrepo/fcrepo-specification#307]
Per the Fedora API spec:

3.2.3:  "GET requests to any LDP-NR MUST correctly respond to the Want-Digest header defined in [RFC3230]."
and
3.3 (HTTP HEAD):  "The server MUST send the same Digest header in the response as it would have sent if the request had been a GET (or omit it if it would have been omitted for a GET)."

As I understand this, we just need to conform to RFC3230, and make sure HEAD Want-Digest: requests get back the same results as GET Want-Digest: requests.

But RFC3230 does not address what to do if requested algorithm(s) are unsupported.

So to test this:  do we just test that GET "Want-Digest:  BARF" and HEAD "Want-Digest:  BARF" return the same thing, even if the digest request is silently ignored?

I see this was discussed, but not resolved, in issue #27.  It may be that no resolution is necessary, just make sure the behavior is the same for HEAD and GET, but I'd like to clarify that.

**Comment by zimeon** [comment]
I think that, as the spec stands, the HEAD response should be the same as the GET response. The ignoring of the `Want-Digest` is not a change in the [payload headers which may differ between GET and HEAD](https://fcrepo.github.io/fcrepo-specification/#http-head) (i.e. omitted in HEAD)

**Comment by sprater** [comment]
OK, we can go with the assumption that as long as the two responses are the same, and match RFC3230 where the kind of response is mandated, the tests will pass.
A related question, more to the issue of crafting a test:  is there a way to see what digest types are supported, so that we can use them to set up tests?

**Comment by awoods** [comment]
@sprater : Per rfc-3230, section-4.3.2:
https://tools.ietf.org/html/rfc3230#section-4.3.2
>   A sender MAY send an instance-digest using a digest-algorithm without
   knowing whether the recipient supports the digest-algorithm, or even
   knowing that the recipient will ignore it.

This does not provide any guidance in determining which algorithms are supported. However, in the Fedora spec, sections [3.5.1](https://fedora.info/2017/11/27/spec/#http-post-ldpnr) and [3.6.1](https://fedora.info/2017/11/27/spec/#http-put-ldpnr) have `SHOULD` language suggesting that:
> An HTTP PUT request that includes an unsupported Digest type (as described in [RFC3230]), SHOULD be rejected with a 400 (Bad Request) response.

@fcrepo/editors : The current wording of the Fedora spec implies a client approach of "keep trying different digest algorithms until you find one that does not fail".
If there is no obvious response header that could communicate supported algorithms, would it make sense to require a human-readable message in the 400 (Bad Request) response that details supported algorithms?
Noting, this does not help @sprater to design tests that could be run against various Fedora implementations.

**Comment by escowles** [comment]
A constraints doc should be referenced by the 400 response — maybe we should recommend that should include a machine-readable list of supported algorithms?

**Comment by sprater** [comment]
Would a Warning header (HTTP 1.1 spec, section 14.46) be of use as a response header?  It’s mostly used for caching in the wild, but according to spec, it’s a general purpose header that can be used in various ways across implementations.

So a test could get the list of accepted algorithms by sending a “Want-digest: foobar” request, getting a 400 Bad Request back, and examining the contents of the custom Fedora Warning header for accepted algorithms.

**Comment by zimeon** [comment]
I think that asking to make the constraints document machine readable is too big a step.

The consensus so far is that we don't want to mandate any algorithm(s) to be supported, so a server might support only algorithms that any given validator doesn't implement. I think the best approach for validation is either:
  1. try all implemented (in the validator) algorithms and check correct behavior for each, noting which are supported and not supported, or
  2. take supported algorithms as an input parameter (like container types in the LDP validation suite) and test against them

**Comment by sprater** [comment]
I could see the validator combining those approaches:  using input parameters, if supplied, otherwise testing an internal set of validator-supported algorithms.  That should cover enough bases.

**Comment by awoods** [comment]
@sprater / @zimeon : sounds like a good plan.
As for the "internal set of validator-supported algorithms", I would suggest: `SHA-1`, `SHA-256` and `MD5`.

**Comment by sprater** [comment]
This works for me.  Does any language need to be changed in the spec, or can this issue be closed?

**Comment by awoods** [comment]
Recommend `close`

**Comment by sprater** [comment]
Closing the issue.  Thanks, everyone.
