### ISSUE TITLE
Clarify expectations around external body content and Accept-Post response header

### ISSUE THREAD

**Issue by sprater** [fcrepo/fcrepo-specification#308]
In the specification, there is this requirement:

> 3.9 External Body Content
> [...]
> Fedora servers MUST advertise support in the Accept-Post response header for each supported access-type parameter value of Content-Type: message/external-body. 

To which HTTP verbs does this requirement apply?  Is there any constraint in terms of type of resource acted upon, or headers sent with the request?  Or is Accept-Post expected in every response header?

**Comment by escowles** [comment]
I would expect the GET, HEAD, and OPTIONS methods for containers to include Accept-Post header. Would updating that section with this wording be clearer?

> GET, HEAD, and OPTIONS responses for LDPCs MUST advertise support in the Accept-Post response header for each supported access-type parameter value of Content-Type: message/external-body.

**Comment by awoods** [comment]
There seems to be some mixed guidance here. The IETF draft indicates `Accept-Post` only on `OPTIONS`:
https://tools.ietf.org/html/draft-wilde-accept-post-00#section-3
> Accept-Post SHOULD appear in the OPTIONS response for any resource that supports the use of the POST method.

However, the language in the LDP Spec broadens this slightly:
https://www.w3.org/TR/ldp/#h-header-accept-post-2

> The Accept-Post HTTP header SHOULD appear in the OPTIONS response for any resource that supports the use of the POST method. The presence of the Accept-Post header in response to any method is an implicit indication that POST is allowed on the resource identified by the Request-URI.

Further, in the examples in the LDP Spec, many (if not all) of the `GET` responses include `Accept-Post`.
https://www.w3.org/TR/ldp/#ldpc-ex-membership-full-liabcont

That said, I would be inclined to require (`MUST`) `Accept-Post` on `OPTIONS`, and suggest (`SHOULD`) on `GET`... noting that `HEAD` is implied with `GET`.

**Comment by escowles** [comment]
👍🏻 to MUST for OPTIONS, and SHOULD for GET/HEAD

**Comment by sprater** [comment]
Sounds good to me.  Shall we create tests on the assumption that the spec will updated accordingly?

**Comment by awoods** [comment]
@sprater : It probably makes sense to move forward based on this discussion. We will have full confidence in the informal consensus here once a PR is committed.

**Comment by zimeon** [comment]
In [HTTP](https://tools.ietf.org/html/rfc7231#section-4.3.7) and [LDP](https://www.w3.org/TR/ldp/#ldpr-HTTP_OPTIONS) it seems one would **not** normally expect the OPTIONS response to vary depending upon the value of the `Content-Type` header. Do we really want/need to do that? If we do then I think we need to spell it out, perhaps:

> Fedora servers MUST advertise supported document formats in the <code>Accept-Post</code> response header on <code>OPTIONS</code> requests for resources that allow <code>POST</code>. The <code>Accept-Post</code> response header MUST be tailored to the specific <code>access-type</code> parameter value of the <code>Content-Type: message/external-body</code> request header, if specified.

But I'm really not sure why a server would support a different set of POSTable document formats (media ranges per [LDP 7.1](https://www.w3.org/TR/ldp/#header-accept-post)) for request-body vs external-content requests. Do we have a use case for that? If we assume that the same set of document formats are POSTable via whatever means supported then I think the text can be simpler. Something along the lines of:

> Fedora servers MUST advertise supported document formats in the <code>Accept-Post</code> response header on <code>OPTIONS</code> requests for resources that allow <code>POST</code> with request entity or external content, per [LDP 4.2.8](https://www.w3.org/TR/ldp/#h-ldpr-http_options).

**Comment by escowles** [comment]
@zimeon My reading of #337 is that it requires OPTIONS to list the valid `access-type` values — not that it must vary the list depending on the `Content-type` header.

**Comment by zimeon** [comment]
@escowles - Perhaps I'm missing something obvious, but can you give an example of how valid `access-type` values would be listed? That doesn't seem specified -- all I see is how media types/ranges are specified in `Accept-Post`, e.g.:

```
Accept-Post: text/turtle, application/ld+json
```

or based on definition of media range from https://tools.ietf.org/html/rfc7231#section-5.3.2 something more complex with wildcards (note `q` weights note allowed per LDP):

```
Accept-Post: audio/*, text/turle
```

but I don't see how we add _"I support `access-type=URL` and `access-type=local-file`"_ to this.

**Comment by escowles** [comment]
That's true, this isn't great:
```
Accept-Post: audio/*, text/turtle, message/external-body; access-type=url, message/external-body; access-type=local-file
```

**Comment by zimeon** [comment]
Thanks @escowles -- now I see that values like `message/external-body; access-type=url` are valid as "media ranges" per https://tools.ietf.org/html/rfc7231#section-5.3.2 . However, it does seem a bit odd as these access types seem orthogonal to the actual media types. I think we need to add an example to make this clear. How about:

>  Fedora servers MUST advertise support for POST of external content by including the appropriate media range values, such as `message/external-body; access-type=URL`, in the `Accept-Post`  header in response to OPTIONS requests. These media range values are listed along with those supported for POST with content in the request entity. For example:
>
> `Accept-Post: text/plain, audio/*, message/external-body; access-type=URL, message/external-body; access-type=local-file`

I'm torn as to whether it would be good use `*/*` in the example -- it seems probably many servers won't care what the media type of a binary is, so would accept anything, but then `*/*` looks odd along with specific `message/external-body` types.

**Comment by awoods** [comment]
This issue should be closed as no-longer-relevant with the merge of: https://github.com/fcrepo/fcrepo-specification/pull/343

**Comment by awoods** [comment]
https://github.com/fcrepo/fcrepo-specification/pull/343 has been merged. This issue is no longer relevant.
