### ISSUE TITLE
Clarify HTTP PUT requirements around types, subtypes, and interaction models

### ISSUE THREAD

**Issue by sprater** [fcrepo/fcrepo-specification#309]
Concerning this requirement in the spec:

> 3.6 HTTP PUT
> 
> When accepting a PUT request against an existing resource, an HTTP Link: rel="type" header MAY be included. If the type in the Link header is a subtype of a current type of the resource, and has an interaction model assigned to it by [LDP], then the resource MUST be assigned the new type and the interaction model of the resource MUST be changed to the interaction model assigned to the new type by [LDP]. If that type is a value in the LDP namespace and is not either a current type of the resource or a subtype of a current type of the resource, the request MUST be rejected with a 409 (Conflict) response. 

1)  Do these requirements apply to any type and subtype, or just LDP types and subtypes?
2)  By "interaction model", do you mean the range of permissible requests and responses that apply to a given type or subtype?
3)  Can you provide an example of how this might be tested? (A sample type, a sample subtype, a change in the interaction model that could be verified)

**Comment by escowles** [comment]
The term "interaction model" comes from the LDP spec, but doesn't seem to be specifically defined there.  I would characterize it as the "primary type" of the resource, which determine the "range of permissible requests and responses that apply".  The requirements here apply to LDP and non-LDP types, though the requirement to return 409 Conflict is specific to LDP types.

For testing purposes, you could pick any type-subtype chain in the LDP type hierarchy (see https://www.w3.org/TR/ldp/#fig-ldpc-types), e.g., ldp:Resource -> ldp:RDFSource, ldp:Container, ldp:BasicContainer.  As long as the implementation supports both the type and subtype, you should be able to create a resource as the type, and then modify it to be the subtype.

Unfortunately, the Modeshape implementation is known to only support the leaf types, so there is no valid type-subtype combination.

**Comment by awoods** [comment]
Thanks, @escowles . 
Regarding:
> The requirements here apply to LDP and non-LDP types

Is there any reasonable way for a Fedora implementation to support checking valid inheritance of `non-LDP` types? ...without inferencing?
I am somewhat inclined to tighten this wording to just `LDP` types.

**Comment by escowles** [comment]
I think the types would have to be types the implementation knew about — I would not expect impls to do inferencing or otherwise have knowledge of arbitrary types.  Maybe there’s a principle that needs to be articulated here, essentially that interaction models shouldn’t be changed, only narrowed?

I would be 👍🏻 to rewording for clarity here, reserving the MUST language for LDP types.  Maybe we should also recommend the same principle should apply to any implementation-specific interaction models?

**Comment by escowles** [comment]
One other thing: I would expect an implementation to reject any unknown interaction type, since it wouldn’t know what behavior was required/expected.

**Comment by sprater** [comment]
I'm okay with MUST for LDP types, and SHOULD for implementation-specific types.  That "SHOULD" case would be difficult to test, however, without a way to find out from the implementation what types and sub-types it supports.  (This is similar to the problem of testing for appropriate behavior for "Want-Digest:" requests:  without knowing in advance what the implementation supports, it's hard to test for correct behavior in an abstract, implementation-independent way).

**Comment by awoods** [comment]
@sprater : Testing against the LDP types is probably adequate.
![ldpc-hierarchy](https://www.w3.org/TR/ldp/images/ldpc-hierarchy.png)
