### ISSUE TITLE
4.3.3 Not describing Accept-Post

### ISSUE THREAD

**Issue by awoods** [fcrepo/fcrepo-specification#310]
In 4.3.1, a statement indicates that 4.3.3 describes `Accept-Post`:
```
If an LDPCv supports POST, then it MUST include the Accept-Post header described in 4.3.3 HTTP POST. 
```
4.3.3 does not appear to provide any comment on `Accept-Post`.

**Comment by barmintor** [comment]
cf [LDP 5.2.3.13](https://www.w3.org/TR/ldp/#ldpc-post-acceptposthdr)

**Comment by zimeon** [comment]
[Fedora spec 4.3.3](https://fcrepo.github.io/fcrepo-specification/#ldpcv-post) is the description POST to an LDPCv --- I wonder whether in an earlier iteration it had an explicit description of LDP's `Accept-Post` requirement?

It seems that LDP is inconsistent in the requirements for `Accept-Post`. In [5.2.3.13](https://www.w3.org/TR/ldp/#ldpc-post-acceptposthdr) is says:

> LDP servers that support POST MUST include an Accept-Post response header on HTTP OPTIONS responses, ...

yet in [7.1.2](https://www.w3.org/TR/ldp/#header-accept-post-2) is says:

> The Accept-Post HTTP header SHOULD appear in the OPTIONS response for any resource that supports the use of the POST method.

I think we want to say MUST appear in [LDPCv OPTIONS](https://fcrepo.github.io/fcrepo-specification/#ldpcv-options), and reference 7.1.2 for details. The current descriptions of both `Accept-Post` and `Accept-Patch` under [LDPCv GET](https://fcrepo.github.io/fcrepo-specification/#ldpcv-get) should be moved into [LDPCv OPTIONS](https://fcrepo.github.io/fcrepo-specification/#ldpcv-options) and merely referenced along with the `Allow` header.
