### ISSUE TITLE
Clarify Location support on LDPCv POST

### ISSUE THREAD

**Issue by zimeon** [fcrepo/fcrepo-specification#311]
In https://fcrepo.github.io/fcrepo-specification/#ldpcv-post we say:

> As per \[[LDP](https://fcrepo.github.io/fcrepo-specification/#bib-LDP)], any resource created via POST, in this case an LDPRm, _SHOULD_ be advertised in the `Location` response header.

it seems that from <https://www.w3.org/TR/ldp/#ldpc-HTTP_POST> the use of `Location` is _MUST_:

> 5.2.3.1 LDP clients _SHOULD_ create member resources by submitting a representation as the entity body of the HTTP POST to a known LDPC. If the resource was created successfully, LDP servers _MUST_ respond with status code 201 (Created) and the Location header set to the new resource’s URL. Clients shall not expect any representation in the response entity body on a 201 (Created) response.

so I suggest revising as follows (also linking to the appropriate section of LDP):

> As per \[[LDP](https://fcrepo.github.io/fcrepo-specification/#bib-LDP)] [5.2.3.1](https://www.w3.org/TR/ldp/#h-ldpc-post-created201), the URI of the LDPRm created via POST _MUST_ be advertised in the `Location` response header.

**Comment by dannylamb** [comment]
@zimeon ^^
