### ISSUE TITLE
Editorial: reorder sub-sections in section 5. Resource Authorization 

### ISSUE THREAD

**Issue by zimeon** [fcrepo/fcrepo-specification#313]
I think [5.9 ACL linking on resource creation](https://fcrepo.github.io/fcrepo-specification/#link-acl-on-create) should be one of the earlier sections in [5](https://fcrepo.github.io/fcrepo-specification/#resource-authorization), certainly before the current [5.2 Cross-Domain ACLs](https://fcrepo.github.io/fcrepo-specification/#cross-domain-acls).

**Comment by awoods** [comment]
In support of this reordering, I would further suggest that the current [5.2 Cross-Domain ACLs](https://fcrepo.github.io/fcrepo-specification/#cross-domain-acls) and [5.7 Cross-Domain Group Listings](https://fcrepo.github.io/fcrepo-specification/#cross-domain-groups) should be next to one another towards the end of section-5.
