### ISSUE TITLE
What does it mean to create a Memento of an LDPC and its associated containment notions?

### ISSUE THREAD

**Issue by zimeon** [fcrepo/fcrepo-specification#315]
As currently written, [4. Resource Versioning](https://fcrepo.github.io/fcrepo-specification/#resource-versioning) allows any LDPR to be versioned, and thus we may have original and memento resources for a container. Any contained resource could be contained by the original and/or multiple mementos.

By my reading of [LDP](https://www.w3.org/TR/ldp/), each resource is expected to be contained by zero or one containers, not more. I didn't find an explicit statement saying that it isn't possible to have multiple containment, but language like _["Each resource created in the application or site is created within an instance of one of these container-like entities"](https://www.w3.org/TR/ldp/#ldpc-informative)_  suggests it.

Maybe the reconciliation of these issues is obvious but I'm not getting it (and perhaps other readers wouldn't so we should document it better).  Or maybe these is a real issue here about whether one needs to have ideas of containment/reference counting, whether 'containment' by a memento is somehow 'inactive', or...

**Comment by awoods** [comment]
On the implementation side of this, the Fedora/ModeShape project has been planning on capturing intra-repository links (e.g. members) as repository-relative URLs when creating mementos of an LDPC.
No cascading versioning is supported.

It may be helpful to incorporate some text in the specification to indicate that cascading versioning should not be expected.

**Comment by barmintor** [comment]
My approach to this in Cavendish was that the memento did not make statements about itself, but about the versioned resource.

**Comment by escowles** [comment]
A very rough proposal:

### 4.5.4 Versioning and Containment
> Non-normative note: [LDP] is not explicit, but implies that a resource may be contained by zero or one container (i.e., may not be contained by more than one container).  Implementations may want to take this implication into account when creating an LDPRm of a Container, to avoid having both the LDPRv and the LDPRm containing any members of the Container.  Alternatives include having the LDPRm's ldp:contains triples point to member LDPRms, or having the LDPRm return triples about the LDPRv, not the LDPRm itself.

**Comment by zimeon** [comment]
I like your [suggestion](https://github.com/fcrepo/fcrepo-specification/issues/315#issuecomment-382411415) @escowles.

Perhaps the first sentence could be simplified to _"[LDP] is not explicit, but implies that a resource may not be contained by more than one LDPC."_ and I think in general it is easier to read if one says LDPC instead of Container -- thus avoiding "contained by container" type language.

**Comment by awoods** [comment]
@escowles : Would you be willing to craft a PR?

**Comment by escowles** [comment]
@awoods Sure, I should be able to do that before next Wednesday.
