### ISSUE TITLE
Clarify or remove implied message constraint on successful recursive DELETE

### ISSUE THREAD

**Issue by sprater** [fcrepo/fcrepo-specification#316]
3.8.1, Recursive Delete:

> An implementation MUST NOT emit a message that implies the successful DELETE of a resource until the resource has been successfully removed.

What is the intended use of this constraint, can it be clarified or removed?  As it stands it seems to imply a constraint that a) is a natural language constraint, and subject to interpretation, b) is untestable  by machines, and c) is not matched by similar constraints on any other messages returned in response to other requests acted upon by the implementation.

Isn't this same purpose served in an API fashion by the preceding constraint, mandating that an implementation must not  return a HTTP success status code unless the whole recursive DELETE operation is successful?

Unless there's something I'm missing, I'd recommend removing this normative requirement.

**Comment by awoods** [comment]
I wonder if non-normative text would be helpful to clients and servers. If not, removal may be appropriate.

**Comment by birkland** [comment]
I think normative text is appropriate - it spells out a contract for messaging with regard to `DELETE`.  

The spec says:
> An implementation must not return a 200 (OK) or 204 (No Content) response unless the entire operation successfully completed.

What an implementation _can_ do is return a `202 (Accepted)`, which may be appropriate for a large recursive delete.  This is non-committal;  there is no defined mechanism in the HTTP part of the spec for conveying whether or not a resource has been deleted (or not) later on.  Recursive deletes can take a long time to finish, or may fail.  This is where the normative text is important:

> An implementation MUST NOT emit a message that implies the successful DELETE of a resource until the resource has been successfully removed.

The implication is that messaging can reliably be used to convey the deletion of resources in situations where the HTTP api cannot.   It sets the message semantics firmly and normatively as  as "this resource has been deleted", not "a delete request has been made for this resource".

**Comment by sprater** [comment]
Ah, that makes sense to me. That does make testing of that requirement implementation-specific, though;  I would need to know what the mechanism for requesting the state of a deleted resource would be, and what are the range of messages it returns, in order to test compliance.
So perhaps we let this section stand as-is, with the understanding that tests of that piece will have to be targeted to the specific implementation.

**Comment by awoods** [comment]
@sprater : Would you close this if you feel like it is resolved?

**Comment by zimeon** [comment]
Agree `close - no change necessary`. I think @birkland 's explanation based on [current text](https://fcrepo.github.io/fcrepo-specification/#http-delete-recursion) is good.
