### ISSUE TITLE
Clarify LDPNR creation via PUT

### ISSUE THREAD

**Issue by zimeon** [fcrepo/fcrepo-specification#317]
If an LDPNR is created via PUT, is it also required to create an associated LDPRS? This is not [currently specified](https://fedora.info/2017/11/27/spec/#http-put-ldpnr) but I think given it is a requirement for creation via POST then it should also be the case for PUT -- it doesn't make sense for the rules to be different.

**Comment by awoods** [comment]
Agreed. An LDPNR created via PUT should result in an associated LDPRS description.

**Comment by dannylamb** [comment]
Indeed.  In fact, I am relying on this behaviour.

**Comment by escowles** [comment]
👍 to making this explicit
