### ISSUE TITLE
Should anything be said about containment of non-containment of LDP-RS that describes LDP-NR?

### ISSUE THREAD

**Issue by zimeon** [fcrepo/fcrepo-specification#319]
When an LDP-NR is created via POST, is the associated LDP-RS that describes it uncontained, also created in the same container, or something else?  This isn't specified in the [current Fedora API draft](https://fcrepo.github.io/fcrepo-specification/#http-post) or in [LDP](https://www.w3.org/TR/ldp/#h-ldpc-post-createbinlinkmetahdr). In Fedora 4 [the describing LDP-RS is not in any container](https://gist.github.com/zimeon/a4b02fe70b4f3fba0f07681f2422021a). I suspect that we should remain silent on this but want to flag the question.

**Comment by escowles** [comment]
👍 to remaining silent on this — how to link between the LDP-NR and its description is specified, so you can find it, and different implementations could reasonably have different approaches to the containment issue.

**Comment by dannylamb** [comment]
:+1: to silence.  If you want to know where the associated LDP-RS is across implementations, you should check for the 'describes' link header.

**Comment by awoods** [comment]
:+1: Agreed. Silence in the spec seems appropriate.

**Comment by zimeon** [comment]
Thanks for input, closing.
