### ISSUE TITLE
Make PATCH/PUT optional for LDPCv

### ISSUE THREAD

**Issue by escowles** [fcrepo/fcrepo-specification#335]
Currently, we require that LDP-RSs support PATCH and PUT.

* https://fcrepo.github.io/fcrepo-specification/#http-patch:
> Any LDP-RS MUST support PATCH ([LDP] 4.2.7 MAY becomes MUST).

* https://fcrepo.github.io/fcrepo-specification/#http-put-ldprs:
> Any LDP-RS MUST support PUT to update statements that are not server-managed triples (as defined in [LDP] 2). [LDP] 4.2.4.1 and 4.2.4.3 remain in effect.

We explicitly say that LDPCvs don't need to support POST.  

* https://fcrepo.github.io/fcrepo-specification/#ldpcv-post:
> Although an LDPCv is both a TimeMap and an LDPC, it MAY disallow POST requests. 

We do say anything specific about PATCH/PUT for LPDCvs, so I think it is requried.  Do we want to add sections saying that PATCH/PUT support is not required for LDPCvs?

**Comment by zimeon** [comment]
I agree that LDPCv should not be required to support PUT and PATCH as well as POST
