### ISSUE TITLE
Prefer headers don't REQUIRE behaviors

### ISSUE THREAD

**Issue by zimeon** [fcrepo/fcrepo-specification#339]
Currently, the [Additional values for the Prefer header](https://fcrepo.github.io/fcrepo-specification/#additional-prefer-values) section says:

> * http://www.w3.org/ns/oa#PreferContainedDescriptions: Requires a server to include representations of any contained resources in the response, as defined in [annotation-vocab].
> * http://fedora.info/definitions/fcrepo#PreferInboundReferences: Requires a server to include triples from any LDP-RS housed in that server that feature the requested resource as RDF-object.

Per [RFC7240](https://tools.ietf.org/html/rfc7240#section-2) the `Prefer` header merely requests a behavior:

>  The Prefer request header field is used to indicate that particular server behaviors are preferred by the client but are not required for successful completion of the request.

so I think in both bullets **"Requires"** should be changed to **"Requests"**. I'd also be inclined to change the order of description of these two values, in order to put the SHOULD support one before the MAY support onn.

(Alternatively, if we want to enforce these within Fedora implementations then we would need to point out that departure from the RFC7240 of Prefer. I don't think that was the intention however.)

**Comment by escowles** [comment]
👍 to changing "requires" to "requests"
