### ISSUE TITLE
Persistence Fixity section should provide legal values for Want-Digest

### ISSUE THREAD

**Issue by mjordan** [fcrepo/fcrepo-specification#346]
In section 7.3 Persistence Fixity, it would be helpful to see a list of  hash algorithms  that are allowed as values for the `Want-Digest` header. Or is that list of allowed values implementation specific?

**Comment by awoods** [comment]
@mjordan : yes, the supported algorithms are implementation-dependent. See https://github.com/fcrepo/fcrepo-specification/issues/307

If that does not make sense, your input would be appreciated. Otherwise, please feel free to close this issue.

**Comment by mjordan** [comment]
The approach described in https://github.com/fcrepo/fcrepo-specification/issues/307#issuecomment-348814882 makes more sense to me than the approch suggested in https://github.com/fcrepo/fcrepo-specification/issues/307#issuecomment-350332667, which, if I understand it, means that the client has to guess at which type of algorithm supported until they get it right. The problem with this is that the string representing the algorithms may be expressed in a variety of ways (e.g., SHA, SHA1, sha-1, etc.), so even to hit an algorithm that is supported may take a couple of attempts.

At any rate, as the specification stands now, client implementers are left to figure out how all this should work. Regardless of the approach to answering the question "Can you supply a foo digest value for this resource please?", I think more specific guidance to client implementers should be provided in section 7.3.

**Comment by zimeon** [comment]
Per [RFC3230](https://tools.ietf.org/html/rfc3230#section-6) there is an [IANA registry of digest names](https://www.iana.org/assignments/http-dig-alg/http-dig-alg.xhtml) so I don't think there is any ambiguity in the name or format of these digests, modulo case insensitivity per [RFC3230 sec4.1.1](https://tools.ietf.org/html/rfc3230#section-4.1.1) (note use of `sha1` in Fedora4 is wrong: #235).

I agree that there is still the question of discovery. As currently specified one has to try known digests to work out what is supported, or use non machine-actionable means (constraints doc or out-of-band). We have quite a few things like that and I've gotten used to the idea that additional information is necessary to use a particular Fedora API compliant implementation. So far the community consensus has been to keep the spec general in this way. Given that, I'm not sure that inventing an efficient machine-actionable means of auto-discovery is justified.

**Comment by mjordan** [comment]
@zimeon OK, perhaps having implementations provide additional means of indicating which fixity algorithms they support is sufficient, whether by machine-readable response or documentation.
