### ISSUE TITLE
Audit service not described in API spec

### ISSUE THREAD

**Issue by mjordan** [fcrepo/fcrepo-specification#352]
I am curious about why the API spec doesn't describe or mention an audit service, given that it does cover notifications in some detail, and in particular says "For every resource whose state is changed as a result of an HTTP operation, there MUST be a corresponding notification made available describing that change." (section 6.2).

The reference implementation provides an [audit service](https://wiki.duraspace.org/display/FEDORA475/Audit+Events+for+External+Processes), so I assume that auditing was deemed to be out of scope for the spec and therefore implementation specific.

**Comment by escowles** [comment]
For external audit approaches, I think what's specified around messaging should be enough to implement that.  If you think there's anything missing or underspecified, @mjordan, I'd be interested to hear about that.

For internal auditing, I do think that's out of scope.  Though like Batch Atomic Operations, I think it could be a useful exercise to create a sidecar spec (if there are multiple implementations that want to implement internal auditing).

**Comment by mjordan** [comment]
Agreed, messaging should allow external auditing, and if internal auditing is out of scope for the spec, I'm willing to accept that. On the other hand, it strikes me as a little odd that a spec whose goal is to refine

> the semantics and interaction patterns of LDP in order to better serve the specific needs of those interested in implementing repositories for durable access to digital data

 is silent on auditing and only implicitly addresses what constitutes "durable" access (it is true that section 7 is relevant here).  But, scope is scope. Thanks for the clarification, will close.
