### ISSUE TITLE
Conformance does not require fixity services

### ISSUE THREAD

**Issue by mjordan** [fcrepo/fcrepo-specification#353]
Section 1 of the spec omits mention of section 7, "Binary Resource Fixity":

> A conforming Fedora server is a conforming [LDP] 1.0 server that follows the additional rules defined in sections 3. Resource Management, 4. Resource Versioning, 5. Resource Authorization, and 6. Notifications of this specification.

In addition, sections 7.2 and 7.3 use the key word `may`, which according to https://tools.ietf.org/html/rfc2119 is the equivalent of "truly optional." 

Is it safe to infer that an implementation may be conformant and not support any fixity services?

**Comment by escowles** [comment]
The reason that section 7 is omitted from the list is that it's all non-normative — it's mostly commentary on how fixity checking can be accomplished using the other, normative, parts of the spec:

* "GET requests to any LDP-NR MUST correctly respond to the Want-Digest header defined in RFC3230." https://fcrepo.github.io/fcrepo-specification/#http-get-ldpnr
* "An HTTP POST request that would create an LDP-NR and includes a Digest header (as described in RFC3230) for which the instance-digest in that header does not match that of the new LDP-NR MUST be rejected with a 409 (Conflict) response." https://fcrepo.github.io/fcrepo-specification/#http-post-ldpnr

There is some wiggle room in that we don't specify any digest algorithms that must be supported, so an implementation could simply not accept any algorithms (but that seems like a deliberately poor implementation choice to me).

**Comment by mjordan** [comment]
@escowles thanks for the clarification, I hadn't picked up on those normative sections of the spec. Closing this issue and linking to #346 since it's relevant to your comment.
