### ISSUE TITLE
External Content and 'expires'

### ISSUE THREAD

**Issue by bseeger** [fcrepo/fcrepo-specification#354]
In the current version of the specification, it says nothing of `expires` in regards to external message body.  Is the spec purposely silent on this or is `expires` functionality replaced by `copy`?

Thanks!

**Comment by escowles** [comment]
@bseeger Yes, we are no longer overloading `expires` to indicate the impl. should copy content, because we added the explicit `handling=copy`.

**Comment by bseeger** [comment]
Excellent, thanks!
