### ISSUE TITLE
Clarify that implementations MUST support creation of all three LDPC types

### ISSUE THREAD

**Issue by zimeon** [fcrepo/fcrepo-specification#386]
[3.1.1](https://fedora.info/2018/06/25/spec/#ldpc) says:

> Implementations _MUST_ support the creation and management of [LDP] Containers (LDPC).

I think we mean by this, and it is perhaps implied by the following comments about different container types, that implementations _MUST_ support the creation and management of [LDP] Containers (LDPC) with Basic, Direct and Indirect interaction patterns. Would seem clearer to spell that out.

**Comment by awoods** [comment]
Since the LDP spec does not require the implementation of the container types, and Fedora does... I agree, we should probably make that clear.

**Comment by barmintor** [comment]
It does? I wouldn't have said that off the top of my head.

**Comment by awoods** [comment]
That would be an initial point to gain common understanding on: 
- Should the Fedora API Specification require support for the creation of any or all of the LDP Container types (basic, direct, indirect)?

**Comment by barmintor** [comment]
From discussion: I would prefer the language to say "at least one", but I will not argue against limiting requirement to "Basic".

**Comment by zimeon** [comment]
Agreement on [2018-08-29 Editors' Call](https://wiki.duraspace.org/x/ZRURBg) that we will say "MUST support Basic containers and MAY support other LDP container types"
