### ISSUE TITLE
Rules for setting `ldp:membershipResource`,  `ldp:hasMemberRelation`, `ldp:insertedContentRelation`

### ISSUE THREAD

**Issue by zimeon** [fcrepo/fcrepo-specification#387]
By my reading, LDP is silent on how container properties are actually set and under what conditions they may be changed. I think we probably all have a working assumption that these values might be set by the RDF supplied on container creation (and I notice this is embodied in [tests such as 3.1.1-C](https://github.com/fcrepo4-labs/Fedora-API-Test-Suite/blob/3c4292c0f8c0ef94f2f0f271e9d31fd123561f50/src/main/java/org/fcrepo/spec/testsuite/crud/Container.java#L133-L137)). Do we need to spell that out? And what/when can changes be made?

**Comment by zimeon** [comment]
And related, what about `ldp:isMemberOfRelation` as inverse of `ldp:hasMemberRelation`? Does a Fedora implementation need to allow that as an alternative way to set up the container?

**Comment by awoods** [comment]
@zimeon : I am trying to understand your point here, recognizing that maybe I am too deep in the current assumptions of the community Fedora impl.

My understanding is that container properties are any properties that have the container's URI as the subject of a given triple.

Those properties can be set:
- in RDF on-creation
- in SPARQL-Update requests after a container have been created.

Beyond that, there are implementation-defined protected properties (server-managed triples), and non-protected user-defined properties.

With that context, are you suggesting there could be value in specifying how properties on a container are set? What would "spelling that out" look like?

**Comment by zimeon** [comment]
By my reading LDP doesn't actually say that servers must support setting and changing of these properties in via the two means you quote (happy to be shown otherwise but I've struggled to find clarity). The description of these properties is all about what values they can have, whether they must be serialized, and what behaviors they imply.

I think one could reasonably call these server-managed properties but that too isn't clear from LDP (_"The portion of an LDP's triples whose behavior is constrained directly by this specification; for example, membership triples and containment triples."_) The behaviors are constrained by the specification but they aren't the example triples mentioned.

**Comment by awoods** [comment]
My understanding is that there are no specified restrictions on setting the properties: `ldp:membershipResource`, `ldp:hasMemberRelation`, `ldp:insertedContentRelation`.
...but maybe I am missing your point.

Are you concerned with the rules under which the above properties can be created/modified, or the actual mechanics or such creations/modifications (which could be illustrated in non-normative examples)?

**Comment by zimeon** [comment]
Thanks for sticking with me to better understand this @awoods !

I agree that there are no specified RESTRICTIONS on setting the properties: `ldp:membershipResource`, `ldp:hasMemberRelation`, `ldp:insertedContentRelation` but there are also **no specified server implementation REQUIREMENTS on being able to set these properties**.

LDP is mostly a specification about read operations, create/update/delete functionality is all optional per LDP, but we make PATCH/POST/PUT support mandatory in Fedora. Support for container creation and update is optional in LDP, we make support for creation and update of all three container types (#386) mandatory in Fedora. LDP introduces some guidance on how the [container-type/interaction-model is set](https://www.w3.org/TR/ldp/#ldpc-post-createrdf) via link headers but it stops short of saying that an `rdf:type` in the body should be used if there isn't a type in the link header (hence a Fedora may or may not do that).

LDP specifies no rules about setting or updating the properties: `ldp:membershipResource`, `ldp:hasMemberRelation/ldp:isMemberOfRelation`, `ldp:insertedContentRelation`. As an example, [LDP 5.4.1.4](https://www.w3.org/TR/ldp/#ldpdc-containtriples) describes a requirement to _express_ the membership-predicate in representations, and the preceding [LDP 5.4.1.2](https://www.w3.org/TR/ldp/#h-ldpdc-mbrpred) recommends that _"LDP Direct Containers SHOULD use the `ldp:member` predicate as a LDPC's membership predicate if there is no obvious predicate from an application vocabulary to use."_ But nowhere does it say:

>  *  Implementations MUST allow the membership predicate to be set via either the `ldp:hasMemberRelation` or `ldp:isMemberOfRelation` property of the content RDF on container creation, or otherwise will default to an implementation defined value. It is RECOMMENDED that implementations use the default `<> ldp:hasMemberRelation ldp:member`.
> * Implementations MUST allow the membership predicate to be updated by subsequent PUT or PATCH requests that change either the `ldp:hasMemberRelation` or `ldp:isMemberOfRelation` property of the resource content (_and maybe some restrictions_).

I think it would be equally valid per LDP to implement a server that required the membership predicate to be set via link header and never be changed (not that I suggest that). I think we need text along the lines of the quote above to properly define the behavior of a Fedora implementation (and similarly for `ldp:membershipResource` and `ldp:insertedContentRelation`).

I note that neither the LDP spec, the [LDP primer](https://www.w3.org/TR/ldp-primer/), nor the [LDP guidelines](https://www.w3.org/TR/ldp-bp/) give an example request that creates an LDP-DC or LDP-IC.

**Comment by awoods** [comment]
Thanks for the clarification, @zimeon .
I support adding text along the lines of your quote above to make the usage of Direct and Indirect mechanics more clear.

**Comment by escowles** [comment]
👍 to the quoted text above, requiring implementations to support setting the membership relation in the RDF used to create and update containers.

**Comment by barmintor** [comment]
From a pragmatic view I am :+1: the first bullet (set on create), but prefer `MAY` on the second (as it is easy to imagine impls not wanting to change internal structure via the API).

**Comment by zimeon** [comment]
Agreement on [2018-08-29 Editors' Call](https://wiki.duraspace.org/x/ZRURBg) that we will adopt the bullets in https://github.com/fcrepo/fcrepo-specification/issues/387#issuecomment-401885677, the first MUST and the second as MAY (and change RECOMMENDED to SHOULD), and have similar text for `ldp:membershipResource` and `ldp:insertedContentRelation`. Because we are changing the second bullet to MAY, there is no need to enumerate other restrictions.
