### ISSUE TITLE
Repository Root ACL

### ISSUE THREAD

**Issue by dbernstein** [fcrepo/fcrepo-specification#398]
A point of clarification:  From https://fcrepo.github.io/fcrepo-specification/#inheritance, it sounds to me that if there is no acl defined for the root resource (e.g. http://localhost:8080/rest/) then whatever that resource presents as the `Link: <acl-uri>; rel="acl"` should return a 200 (assuming the user has sufficient privileges). Do I have that right? 

At the moment,  the community implementation returns 404 on a GET to the acl-uri.  There is however an internally defined (but not externally visible)  root acl.  As I started writing a Compatibility Test Suite Test for the the above referenced line in the spec,  I realized that there would be no way to test section 5.9 if the body of the root acl is not returned to the client.

**Comment by awoods** [comment]
With a fresh installation of fcrepo4, when I do a `HEAD` on `http://localhost:8080/rest/`, I see a `Link` header pointing to:
```
Link: <http://localhost:8080/rest/fcr:acl>; rel="acl"
```
If I do a `GET` on `http://localhost:8080/rest/fcr:acl` as `fedoraAdmin`, I get the [repository default ACL](https://github.com/fcrepo4/fcrepo4/blob/master/fcrepo-http-api/src/main/resources/root-authorization.ttl).
If I do a `PUT` to `http://localhost:8080/rest/fcr:acl` as `fedoraAdmin` with a new ACL, subsequent `GET` requests get the new ACL.
@dbernstein : Are you seeing something different?

**Comment by dbernstein** [comment]
My mistake.  There was a mistaken assumption in my test suite test.  I thought I was calling the root acl, but I was in fact grabbing a child of the root.
