### ISSUE TITLE
Clarify specification of external-body resources

### ISSUE THREAD

**Issue by birkland** [fcrepo/fcrepo-specification#40]
Pulled out of [#37](https://github.com/fcrepo/fcrepo-specification/issues/37#issuecomment-277297703)
- [ ] Decide on whether to specify [303](https://github.com/fcrepo/fcrepo-specification/issues/37#issuecomment-277093698)? [307](https://github.com/fcrepo/fcrepo-specification/issues/37#issuecomment-277089334)? or [3xx](https://github.com/fcrepo/fcrepo-specification/issues/37#issuecomment-277089969)?
- [ ] We text that "spells out what happens on HEAD", i.e. also redirect with 3?? (as decided above)
- [ ] Add non-normative clarifying text per: [#37 comment](https://github.com/fcrepo/fcrepo-specification/issues/37#issuecomment-277079418)

**Comment by awoods** [comment]
Based on the points above, I would suggest:
1. 303
2. Same as 1.
3. Yes, add non-normative text

**Comment by awoods** [comment]
@birkland : in light of: https://github.com/fcrepo/fcrepo-specification/pull/121
I believe this issue can be closed as "overcome by events".
If you agree, could you please close this issue?

**Comment by awoods** [comment]
Resolved with https://github.com/fcrepo/fcrepo-specification/pull/121

**Comment by birkland** [comment]
@awoods Sorry, I missed this.  Yes, I don't think this is relevant any more.  That being said, the external content section is not entirely comprehensible to me; At some point (after OR) I plan on opening tickets so that it can be clarified; albeit in a different way then this ticket.
