### ISSUE TITLE
LDP-NR Patching

### ISSUE THREAD

**Issue by whikloj** [fcrepo/fcrepo-specification#400]
Question related to the compatibility test suite

Section [5.7.3](https://fedora.info/2018/06/25/spec/#append-ldpnr) states
>  When a client is allowed to perform acl:Append but not acl:Write operations on an LDP-NR:
> *    All DELETE, POST, and PUT requests MUST be denied
> *    A PATCH request that deletes or modifies existing content MUST be denied
> *    A PATCH request that only adds content SHOULD be allowed

I'm unclear how (or if) we test for support of `PATCH`ing an LDP-NR. 

It seems that the LDP spec leaves open this possibility.
> 4.4.1.1 Each LDP Non-RDF Source MUST also be a conforming LDP Resource...

> 4.2.7
Per [RFC5789], this HTTP method is optional and this specification does not require LDP servers to support it....

The Fedora spec is silent on changing this so I am assuming we should check this... but maybe that is too obscure to worry about?

**Comment by escowles** [comment]
@whikloj Yes, we are deliberately silent on whether LDP-NRs need to support PATCH.  There's nothing stopping an implementation from doing this, but it's definitely not required.  For PATCHing an LDP-NR, I'm not sure how the client would specify the patch.  For a system that managed source code or other text files, I could imagine sending diff/patch output.  For other kinds of files, it seems harder.

So I guess the bottom line for me is that it's not really clear how PATCHing LDP-NRs would work, and the spec definitely doesn't require it, so I don't think the compatibility test suite needs to test it.

**Comment by whikloj** [comment]
Ok, thanks. I'll take the larger question of whether the CTS should fail if we hit such an implementation because we can't/aren't testing it the test suite.

**Comment by whikloj** [comment]
Sorry @escowles  just re-reading this and I may have been quick to close this. You said 
> So I guess the bottom line for me is that it's not really clear how PATCHing LDP-NRs would work, and the spec definitely doesn't require it, so I don't think the compatibility test suite needs to test it.

The spec doesn't require you to support PATCHing LDP-NRs but it **does** require that you are denied from doing some PATCHing of LDP-NRs based on certain WebAC permissions specifically:
> A PATCH request that deletes or modifies existing content MUST be denied

This seems to open the need to test any and all possible `Allow-Patch` formats to validate an implementation.

**Comment by escowles** [comment]
Closed by #405
