### ISSUE TITLE
whither WebIDs?

### ISSUE THREAD

**Issue by acoburn** [fcrepo/fcrepo-specification#403]
It seems that the section about WebIDs was removed in this [commit](https://github.com/fcrepo/fcrepo-specification/commit/6f2d5e0739cb99605c1adccf9ce31773f6374dfd). The associated issue here seems to address an issue of the order of various subsections but not the removal of the webid section.

There was an earlier [commit](https://github.com/fcrepo/fcrepo-specification/commit/35b96b95831619f3169037618746d867a76fc896) that added a clarifying statement about webids, but that appears to have been deleted in the commit mentioned above.

Was the removal of the WebID section intentional or inadvertent?

**Comment by zimeon** [comment]
The removal of the non-normative note about webids being a component of SOLID WAC was not accidental.

I don't recall the discussion well but, reviewing the change now, I think it was good to remove. The note didn't say anything that isn't covered better in the SOLID WAC spec, and didn't add any Fedora-specific information.

**Comment by acoburn** [comment]
It is fine with me to defer to SOLID on this. At which meeting was this discussed?

I'd note that this is at least ambiguous enough that the Fedora test suite assumes (incorrectly, according to SOLID) that `acl:agent` values can be string literals. See, for instance, https://github.com/fcrepo/Fedora-API-Test-Suite/issues/219

**Comment by awoods** [comment]
Noting that the Fedora test suite now expects URIs instead of string literals for user ids.
https://github.com/fcrepo/Fedora-API-Test-Suite/pull/260
