### ISSUE TITLE
Clarification of Section 3.1.2 LDP Direct Containers

### ISSUE THREAD

**Issue by awoods** [fcrepo/fcrepo-specification#407]
https://fedora.info/2018/11/22/spec/#ldpdc

The first bullet states:
> Implementations must allow the membership constant URI ([LDP] 2) to be set via the ldp:membershipResource property of the content RDF on container creation, or otherwise default to an implementation defined value. Implementations should use the LDPC's URI as the default property value.

The `LDPC` in the last sentence should be clarified to mean either:
- "...the newly created DirectContainer LDPC's URI...", or
- "...the containing LDPC's URI in which the new DirectContainer is created..."

**Comment by escowles** [comment]
I think the first option is what I think that means — the newly-created container should use itself as the membership resource, unless one is specified.

**Comment by zimeon** [comment]
I agree with @escowles , it was intended to mean the newly-created container URI should be the default membership resource

**Comment by dannylamb** [comment]
I'm also in agreement with our interpretation of that.
