### ISSUE TITLE
Proposal to use the Fedora API specification as an input document for a W3C WG charter

### ISSUE THREAD

**Issue by csarven** [fcrepo/fcrepo-specification#415]
Mic check. There is a charter proposal for a W3C WG that is originally based on the [Solid Protocol](https://solidproject.org/ED/protocol). Long story short, the proposal for the WG name is still being bikeshed, and the scope and deliverables are now broader (and not strictly about Solid) but generally around the same principles and ideas; individuals and communities controlling their data, in a nutshell. The charter is now framed to work towards a protocol specification, where there may be multiple input documents. As part of potential input documents, the Solid Protocol is one, and I've recently proposed that the Fedora API specification is added to the charter as well considering works being in the same neighbourhood, if not inspired in some areas. The PR for that in particular is being evaluated at https://github.com/solid/solid-wg-charter/pull/72 . To be clear, the idea is to not simply copy/paste or rubberstamp any input document or anything in particular necessarily from existing documents but to use them towards the deliverable. That said, there are some considerations around IPR/rights/licensing, joining forces or works, as well as participation. The Fedora/Lyrasis community is invited to chime in at the PR linked above; raise questions; or answer questions. Hope to see you there.

**Comment by Surfrdan** [comment]
@csarven Apologies that nobody responded to this. I'm afraid nobody was watching this repo at the time. It looks like this has been merged now at your end and I'm happy that our use-case was useful to you in putting your charter proposal together. I'll close this now as complete but do reach out if you need anything further.
