### ISSUE TITLE
ETags on resources in the context of Atomic Operations

### ISSUE THREAD

**Issue by awoods** [fcrepo/fcrepo-specification#57]
The community Fedora implementation does not include ETags on responses for resources within the context of Atomic Operations.
The specification is currently silent on the topic.
Do we want to include guidance within the specification or remain silent?

**Comment by acoburn** [comment]
I don't think [LDP 4.2.1.3](https://www.w3.org/TR/ldp/#ldpr-resource) is particularly ambiguous about ETags:

> LDP server responses must use entity tags (either weak or strong ones) as response ETag header values, for responses that contain resource representations or successful responses to HTTP HEAD requests.

Thus, from my perspective, it is clear how ETags should be handled (they need to be present), and there is nothing more the spec has to say about them.

There _could_ be some non-normative language about ETags and BatchOps (like: be careful), but I would advocate for remaining silent.

**Comment by awoods** [comment]
Works for me.
