### ISSUE TITLE
Consider renaming prefer headers

### ISSUE THREAD

**Issue by acoburn** [fcrepo/fcrepo-specification#62]

**Comment by ajs6f** [comment]
+1

**Comment by ajs6f** [comment]
"An IRI to signal the client prefers to receive the set of triples representing other repository resources which link to a given resource."

Is that right? Isn't it that the client wants "triples representing other repository resources which link to a given resource _and_ triples representing the given resource"?

**Comment by acoburn** [comment]
@ajs6f prefer headers can be combined. PreferInboundReferences would only signal whether the inbound refs would be added to a response -- other prefer headers would control other categories of triples.

**Comment by ajs6f** [comment]
Okay.
