### ISSUE TITLE
Define levels of API conformance?

### ISSUE THREAD

**Issue by dbrower** [fcrepo/fcrepo-specification#64]
Should the spec, or an auxiliary document, define levels of conformance to the API? The main use case in my mind is having a Read-Only level, that only supports search and access. There may be other use cases.

**Comment by acoburn** [comment]
You mean something like this: https://www.w3.org/2012/ldp/hg/tests/reports/ldp.html

Once a TCK/test suite is available, implementations would be able to submit conformance reports.

**Comment by acoburn** [comment]
In terms of "conformance", an implementation is either conforming or non-conforming based on the use of `MAY`, `SHOULD` and `MUST` as they are defined in https://tools.ietf.org/html/rfc2119.

If you have "levels of conformance", then `MUST` no longer means `MUST`. You can certainly have a partially conforming implementation which addresses a particular set of use cases, but it is still a partially conforming (read: non-conforming) implementation.

**Comment by dbrower** [comment]
@acoburn I mean, should subsets of the spec be named as shorthand for describing "un-conformance". e.g. This implementation supports the spec up to level 2, or some such. Level 2 would then says, sections of 1, 2, and 3 of the spec are implemented. The words `MUST`, `MAY`, etc keep their original meanings.

The particular use case in my head is supporting a Read-Only endpoint. Perhaps there are others.

**Comment by acoburn** [comment]
@dbrower there will always be use cases that are subsets of what is defined in a given specification.  But that doesn't make a given requirement (e.g. `MUST`) any less of a requirement. 

If there are sections that you think should be made "optional", then we should discuss removing those sections from the specification entirely. That is, a robust spec will contain no optional sections.

If there are certain required behaviors that you think should be changed from `MUST` to either `SHOULD` or `MAY`, now is the time to have that discussion. Likewise, if something is currently defined as `SHOULD` or `MAY` but which might better be defined with `MUST`, please open an issue for that.
