### ISSUE TITLE
Privacy/Security section?

### ISSUE THREAD

**Issue by acoburn** [fcrepo/fcrepo-specification#70]
ReSpec gives this warning:

> This specification doesn't appear to have any 'Privacy' or 'Security' considerations sections. Please consider adding one, see https://w3ctag.github.io/security-questionnaire/

Should such a section be added?

**Comment by whikloj** [comment]
That does raise a lot of good questions... Most of the data related ones would depend on the individual/organization using the implementation and not necessarily the implementation itself.

But the others might be worth a review however I'll also admit that some of the concepts are not clear to me.
