### ISSUE TITLE
Clarify LDP 5.5.1.2 (ldp:insertedContentRelation behavior)

### ISSUE THREAD

**Issue by acoburn** [fcrepo/fcrepo-specification#77]

**Comment by awoods** [comment]
From the perspective of compatibility of Fedora implementations, specifying the behavior one way or another seems constructive.

**Comment by ajs6f** [comment]
Do we have any sense at all of the choice from which real models of real data will better profit? If not (and I don't think we have anything _like_ the experience to make the choice) then making a decision, far from being constructive, is aimless and unhelpful.

**Comment by ajs6f** [comment]
+1 to remaining silent.

**Comment by awoods** [comment]
@ajs6f :In answer to your question:
> Do we have any sense at all of the choice from which real models of real data will better profit? 

..lots of installations use indirect containers, and none of them as far as I have heard use more than one triple with the `insertedContentRelation` triple. So, yes, the real models are showing one triple.

**Comment by ajs6f** [comment]
@awoods , no that shows what people are _doing_ (which is interesting of itself). I'm asking about what people _want_.

**Comment by awoods** [comment]
@ajs6f : Okay, ...noting that what people do is likely more informative than what they want (or think they want).

**Comment by ajs6f** [comment]
@awoods On the contrary, what people do is informed more than anything else by what they think possible, which may or may not have much to do with what they want. Especially when considering Fedora.

**Comment by acoburn** [comment]
@awoods given your comment above, I am not sure that I have been sufficiently clear in my description of this issue:

For instance, given a resource `/foo` that is an `ldp:IndirectContainer`:

```
</foo> a ldp:IndirectContainer ;
    ldp:insertedContentRelation dc:subject ;
    ldp:membershipResource </bar> ;
    ldp:hasMemberRelation ex:prop .
```

And a contained resource:

```
</foo/1> dc:subject <http://example.com/subject/1>, <http://example.com/subject/2> .
```

The question relates to the behavior of membership triples on `/bar`. Does it include _both_ `dc:subject` triples? Or only one? or is it left undefined?

```
</bar> ex:prop <http://example.com/subject/1>, <http://example.com/subject/2> .
```

FWIW, I'm fine with leaving it undefined.

**Comment by acoburn** [comment]
Closing this, as it is resolved to my satisfaction, and there seem to be no significant objections to keeping things as they are in this regard.
