### ISSUE TITLE
`Content-Type: message/external-body` description insufficient for conformance tests

### ISSUE THREAD

**Issue by kefo** [fcrepo/fcrepo-specification#80]
The description for `Content-Type: message/external-body` lacks the details to confidently write an API conformance test.  Quoting [3.4.1](http://fedora.info/spec/#httpPUTLDPNR):

> Implementations MUST support Content-Type: message/external-body extensions for request bodies for HTTP PUT to LDP-NRs. This content-type requires a complete Content-Type header that includes the location of the external body, e.g Content-Type: message/external-body; access-type=URL; URL=\"http://www.example.com/file\", as defined in [RFC2017]. 

As written, the header is noted to be an example, "e.g. Content-Type:..."  

Is `access-type=URL` the only supported type (assuming a restriction)?  Is [`access-type=local-file`](https://github.com/fcrepo/fcrepo-specification/issues/37#issuecomment-290537966) supported?  See [rfc2046.](https://tools.ietf.org/html/rfc2046#page-33)

Resolving https://github.com/fcrepo/fcrepo-specification/issues/40 is also needed.

**Comment by acoburn** [comment]
A HEAD request on the resource could supply the content type. It is worth noting that a Fedora impl SHOULD (not MUST) support this. (Note: as long as the language for this is for redirect and not proxy, I plan not to support this in the impl I'm working on.)

**Comment by awoods** [comment]
@kefo : I believe this issue has been resolved with: https://github.com/fcrepo/fcrepo-specification/pull/121
If you agree, would you please close this issue?

**Comment by awoods** [comment]
Resolved with https://github.com/fcrepo/fcrepo-specification/pull/121
