### ISSUE TITLE
Ordering Concerns

### ISSUE THREAD

**Issue by tpendragon** [fcrepo/fcrepo-specification#82]
First, I'm so sorry about this topic in general. Hopefully it can be resolved quick or we can decide it doesn't matter.

So one of Hydra's major use cases is ordering properties. Yesterday I spent a couple hours writing up a generic LDP persister which supported that use case (https://github.com/projecthydra-labs/valkyrie/pull/24.) Unfortunately, because there's no common agreement between LDP and the Fedora spec around how ordering of properties is done (largely because there's no specification around blank nodes), I'm pretty sure that only works on Derby. Modeshape Fedora skolemizes those nodes, at which point I have little way to know if I should go digging around for extra resources or not (and I really shouldn't have to - there's a huge efficiency concern there.)

I understand I can use Hash URIs to "solve" this, but that seems problematic - there are nice shortcuts in both TTL and JSON-LD for RDF::List which assumes blank nodes as the links, and as things stand I can't assume that will actually work.

Unfortunately I have no real suggestion here - I just want to be able to write a client that orders properties on Fedora and know that it will work, no matter which implementation I'm pointing it at.

**Comment by ajs6f** [comment]
No harm in bringing up the question, but I'm not sure quite what you are asking for. Are you asking for the Fedora spec to require support for RDF collections (or containers, or both)?

Why are hash URIs problematic for you?

**Comment by tpendragon** [comment]
I'm asking for support for RDF Collections, yes.

Hash URIs work, but I think it needs to be recognized that they're a burden on the implementor. The assumptions are built into the common serializations, and you'd have to bypass that (and maybe end up losing out on some efficiencies upstream because of it.) If Hash URIs are "THE" solution, then I think it should be called out.

**Comment by ajs6f** [comment]
I don't think we can prescribe a particular solution for ordering in the spec (especially because it is quite clear that there is _no_ universal solution for all use cases), but others may certainly disagree.

**Comment by ajs6f** [comment]
@acoburn Does this make sense with an implementation that journals out triple events (a la RDF Patch) like yours? It's not clear to me that you have a way to match up blank nodes generated during deserialization with those that have been recorded in the journal.

**Comment by birkland** [comment]
Right - I don't think the spec needs to delve into this; it's in the realm of common/best/accepted practices.  As far as LDP is concerned, RDF is RDF.  Most LDP servers wouldn't care one way or another.   At least LDP provides a mechanism for implementations to make their constraints known if they choose to disallow certain RDF constructs, as the modeshape impl does.

One of our (JHU's) motivations for API-X is that it would allow us to compensate for differences between implementations by inserting shims that do X, Y, or Z -- skolemizing blank nodes into hash URIs and vice versa is one example.  That way we'd present a resource representation to clients that looks and feels like it handles blank nodes & rdf lists in the usual way, without requiring us choose an implementation with native support for everything we need out of the box (and allowing us to quickly adapt if our needs change, or if the implementation changes underneath us)

**Comment by acoburn** [comment]
My implementation relies significantly on the ability to _stream_ data to clients. If the implementation would need to sort triples into collections (or any sort of sorting for that matter), it will really affect performance, and pretty much undermine the entire architecture that I've built up so far.

**Comment by acoburn** [comment]
@ajs6f re blank nodes, I haven't written that part yet, but I was planning to skolemize those bnodes internally and then re-map them back to bnodes on output. I would know which bnode referred to which, so I'm not too concerned about managing the internal mapping; that said, it may end up being more difficult that I think, and that's without needing to guarantee any sort of order to the output.

**Comment by tpendragon** [comment]
@acoburn I should note I don't think the triples should BE in order, I'm saying rdf:List or some sort of ordering mechanism of values should be possible across implementations.

@birkland I worry some about best practice being adding shims, and API-X is pretty explicitly not part of the specification yeah?

**Comment by barmintor** [comment]
I think @tpendragon is less concerned about RDF Collections per se than just the ability to use the json-ld or ttl list constructions without worrying about what the repository will do with them on the other end. EDIT: Or maybe I will see that I am wrong a few comments later.

**Comment by barmintor** [comment]
I'm honestly not sure what the LDP stance on list directives was, tho it's worth observing that the two required serializations have one.

**Comment by ajs6f** [comment]
@barmintor Managing RDF Collections using _bnodes specifically_ is what @tpendragon is asking for (please correct me if I am wrong there, @tpendragon).

**Comment by tpendragon** [comment]
@ajs6f Sorry, wasn't clear. The n-triples serialization USUALLY has b-nodes in that place, but really it's support for the TTL/JSON-LD constructions.

**Comment by ajs6f** [comment]
@tpendragon Okay, that is a little different. In that case, give @barmintor's point about supported serializations, I have to ask again what is missing from the spec?

**Comment by acoburn** [comment]
@tpendragon trellis will support rdf:List constructions. The basic idea is this: you give it RDF, it gives you that same RDF back; there are very few constraints with this, except for those mandated by LDP. So if you give it an rdf:List, you'll get that rdf:List back whether you use hashURIs or BNodes.

**Comment by tpendragon** [comment]
@ajs6f Basically whatever we have to add to prevent Fedora's current behavior:
```
#ttl.ttl
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix dc: <http://purl.org/dc/elements/1.1/> .
@prefix ex: <http://example.org/stuff/1.0/> .

<>
  dc:title "RDF/XML Syntax Specification (Revised)" ;
  ex:editor [
    ex:fullname "Dave Beckett";
    ex:homePage <http://purl.org/net/dajobe/>
  ] .
```
```
curl -H "content-Type: text/turtle" -X POST -d @ttl.ttl http://localhost:8984/rest/dev

curl -H "Accept: text/turtle" http://localhost:8984/rest/dev/bd/24/2d/b2/bd242db2-8908-4ae4-a282-1fb626921015
@prefix premis: <http://www.loc.gov/premis/rdf/v1#> .
@prefix nt: <http://www.jcp.org/jcr/nt/1.0> .
@prefix ns022: <http://example.org/stuff/1.0/> .
@prefix ns021: <http://www.iana.org/assignments/relation/> .
@prefix ns020: <http://www.openarchives.org/ore/terms/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix ns004: <http://pcdm.org/models#> .
@prefix ns003: <http://purl.org/dc/terms/> .
@prefix ns002: <http://www.w3.org/ns/auth/acl#> .
@prefix ns001: <info:fedora/fedora-system:def/model#> .
@prefix xsi: <http://www.w3.org/2001/XMLSchema-instance> .
@prefix ns008: <http://library.princeton.edu/terms/> .
@prefix mode: <http://www.modeshape.org/1.0> .
@prefix ns007: <http://www.w3.org/2004/02/skos/core#> .
@prefix ns006: <http://projecthydra.org/works/models#> .
@prefix ns005: <http://bibframe.org/vocab/> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix ns009: <http://id.loc.gov/vocabulary/relators/> .
@prefix jcr: <http://www.jcp.org/jcr/1.0> .
@prefix fedoraconfig: <http://fedora.info/definitions/v4/config#> .
@prefix mix: <http://www.jcp.org/jcr/mix/1.0> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix image: <http://www.modeshape.org/images/1.0> .
@prefix sv: <http://www.jcp.org/jcr/sv/1.0> .
@prefix test: <info:fedora/test/> .
@prefix ns011: <http://iiif.io/api/presentation/2#> .
@prefix ns010: <http://www.europeana.eu/schemas/edm/> .
@prefix ns015: <http://www.w3.org/2003/12/exif/ns#> .
@prefix ns014: <http://test.com/> .
@prefix ns013: <http://pcdm.org/use#> .
@prefix ns012: <http://fedora.info/definitions/1/0/access/ObjState#> .
@prefix ns019: <http://projecthydra.org/ns/mix/> .
@prefix ns018: <http://sweet.jpl.nasa.gov/2.2/reprDataFormat.owl#> .
@prefix ns017: <http://projecthydra.org/ns/fits/> .
@prefix ns016: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix fedora: <http://fedora.info/definitions/v4/repository#> .
@prefix ebucore: <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#> .
@prefix ldp: <http://www.w3.org/ns/ldp#> .
@prefix xs: <http://www.w3.org/2001/XMLSchema> .
@prefix dc: <http://purl.org/dc/elements/1.1/> .


<http://localhost:8984/rest/dev/bd/24/2d/b2/bd242db2-8908-4ae4-a282-1fb626921015> a fedora:Container , fedora:Resource ;
        dc:title "RDF/XML Syntax Specification (Revised)"^^<http://www.w3.org/2001/XMLSchema#string> ;
        fedora:lastModifiedBy "bypassAdmin"^^<http://www.w3.org/2001/XMLSchema#string> ;
        fedora:createdBy "bypassAdmin"^^<http://www.w3.org/2001/XMLSchema#string> ;
        fedora:created "2017-04-04T16:27:18.47Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        fedora:lastModified "2017-04-04T16:27:18.47Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        ns022:editor <http://localhost:8984/rest/.well-known/genid/c1/da/88/e2/c1da88e2-534c-4b11-bba6-d5e9d4fc3968> .

<http://localhost:8984/rest/.well-known/genid/c1/da/88/e2/c1da88e2-534c-4b11-bba6-d5e9d4fc3968> a fedora:Skolem ;
        ns022:fullname "Dave Beckett"^^<http://www.w3.org/2001/XMLSchema#string> ;
        ns022:homePage <http://purl.org/net/dajobe/> .

<http://localhost:8984/rest/dev/bd/24/2d/b2/bd242db2-8908-4ae4-a282-1fb626921015> a ldp:RDFSource , ldp:Container ;
        fedora:writable "true"^^<http://www.w3.org/2001/XMLSchema#boolean> ;
        fedora:hasParent <http://localhost:8984/rest/dev> .
```

**Comment by birkland** [comment]
@barmintor I believe LDP has no stance on lists, they're just a dance between data models (rdf:next, rdf:nil et al) and serializations

@tpendragon Right, API-X isn't part of the spec, nor should it.  You're simply trying to use lists in a standard way, but the constraints of the modeshape impl are getting in the way.  API-X allows a way to get around these constraints by installing an extension on the server-side when necessary; placing no burden on the client, but placing an operational burden on the administrator who chose to deploy a repository having such constraints in the first place.  On the flip side, you can code your client so that it's compatible with every Fedora implementation - placing the burden on you.  Either way is fine.    The spec won't provide guidance, but knowing the particular constraints of the various fedora impls will help.

**Comment by barmintor** [comment]
@birkland what I mean is what the LDP stance on e.g. `@list` is: I'm not sure what FCR4 does if you send it such a document.

**Comment by tpendragon** [comment]
FCR4 skolemizes them into `.well-known` URIs and makes them child resources which return with the representation. They're no longer in a short-hand TTL syntax for lists. When that happens I basically can't PUT on that resource anymore. I can't take the time to debug a lot, but Valkyrie gives me things like `STATUS: 403 http://localhost:8988/rest/.well-known/genid/d5/26/7f/a4/d5267fa4-9e2b-469b-adee-2e159759b510 is not in the topic of this RDF, which is http://localhost:8988/rest/testing/48cbeead-4f7a-44fc-9434-dffe348333fd/cb/4d/60/d9/cb4d60d9-bd52-4b0e-9958-df881a76cb0b...`

For the spec, basically whatever's necessary to make readings like ^ recommended against.

**Comment by escowles** [comment]
I think a lot of this issue could be resolved (in the Modeshape impl) by skolemizing blank nodes to hash URIs instead of the `.well-known` URIs.  That would allow treating the triples originally supplied with blank nodes to be acted on as part of the parent resource (which is what blank nodes are often used for).

**Comment by acoburn** [comment]
I completely agree with @escowles. To my mind, the question is whether that is simply a bug in the Modeshape impl -- see: [FCREPO-2108](https://jira.duraspace.org/browse/FCREPO-2108) -- or whether that is something that the spec needs to weigh in on.

**Comment by barmintor** [comment]
I'm not sure: for my part, I'd think that a client that uses a list directive doesn't want to deal with a decomposed List construction at all.

**Comment by acoburn** [comment]
@barmintor that's fair, but the way the Modeshape impl skolemizes BNodes is just bizarre, and it creates all sorts of problems for clients.

**Comment by barmintor** [comment]
@acoburn I 100% agree.

**Comment by ajs6f** [comment]
I have never heard anyone disagree with the suggestion @escowles makes. It just wants doing. G-dspeed to the doer! As for @tpendragon's original aim (and I understand it the same way @barmintor does three comments above) I will have to strongly disagree with putting anything about that in the spec, for two reasons:

1. For my money, it's not the spec's place to restrict serializations.
2. That would preclude pure-streaming, and the marginal costs there are very real. (It would also require tracing the links to order any resources in a `List`, but that cost would be restricted to the actual use of `List`s.)

**Comment by awoods** [comment]
Resolved with: https://jira.duraspace.org/browse/FCREPO-2108

**Comment by birkland** [comment]
@awoods Not to be pedantic, but can you confirm that the resolution to this was that "the spec shall not address serializations"?  The issue related to how fcrepo4 handles blank nodes got intermingled in this issue, and I just wanted to make sure that the issue was being closed due do consensus around the spec's silence on the matter, rather than the choice of fcrepo4 to implement them in a different way.

**Comment by awoods** [comment]
@birkland : Yes, this issue was a combination of a Fedora4 bug report and request for specification guidance.
This ticket is being closed with:
1. [Fix of the bug](https://github.com/fcrepo4/fcrepo4/commit/d804293c06ce11c27ff0946fa95a225166dbc4e4)
2. Continued silence in the specification related to how blank nodes are handled

..However, @tpendragon, if you have additional suggestions, please let them be known.
