### ISSUE TITLE
Support for proxied content (related to `Content-Type: message/external-body`)

### ISSUE THREAD

**Issue by kefo** [fcrepo/fcrepo-specification#83]
This issue is to focus and capture the debate around supporting a use case for proxied content. Substantial conversation on this topic happened as part of this issue - beginning at https://github.com/fcrepo/fcrepo-specification/issues/37#issuecomment-290537966 - after it had been closed.

With respect to proxying @escowles [noted](https://github.com/fcrepo/fcrepo-specification/issues/37#issuecomment-290721251):

> Proxying seems like it would potentially address situations where Fedora could access the content but the client could not (either because of auth, private network, etc.).

> Proxying would also make access-type=local-file make sense for some implementations, but not all [as noted].

@barmintor will likely follow with additional details and use case.

**Comment by barmintor** [comment]
@kefo I think the latest changes to the draft spec would allow closing this issue, can you confirm?

**Comment by awoods** [comment]
@kefo : I believe this issue has been resolved with: https://github.com/fcrepo/fcrepo-specification/pull/121
If you agree, would you please close this issue?

**Comment by awoods** [comment]
Resolved with https://github.com/fcrepo/fcrepo-specification/pull/121
