### ISSUE TITLE
Improve clarity of persistence fixity section for unsupported expectations and external-body content

### ISSUE THREAD

**Issue by zimeon** [fcrepo/fcrepo-specification#86]
There is language "hidden" in [3.5.2.1 Expect: 202-digest](http://fcrepo.github.io/fcrepo-specification/#httpGETLDPNR-fixity-expectation) that I think should be linked, moved or copied to [5. Binary Resource Fixity](http://fcrepo.github.io/fcrepo-specification/#binary-fixity). The key part is:

> Implementations that do not support one of these expectations must reject 202-digest requests for the expectation with a 417 Expectation Failed. If the LDP-NR is of Content-Type: message/external-body, the server must respond with a 3xx.

Issues: 
  1. [3.5.2.1 Expect: 202-digest](http://fcrepo.github.io/fcrepo-specification/#httpGETLDPNR-fixity-expectation) applies only to GET whereas I think the language should apply to HEAD also
  2. If reading [5. Binary Resource Fixity](http://fcrepo.github.io/fcrepo-specification/#binary-fixity) it is not clear what the expected response is if the implementation does not support one of the 202-digest expectations (=> 417) or if external-body (=>3xx) without reference to the prior section

(Extracted from bullet 2 of https://github.com/fcrepo/fcrepo-specification/issues/33#issuecomment-292253971 for clarity)

**Comment by awoods** [comment]
@zimeon : I believe this issue can now be closed as OBE since https://github.com/fcrepo/fcrepo-specification/commit/49c557a36319d2f93f4e89bc9ff5c77afe5c8d1c, no?

**Comment by zimeon** [comment]
Agreed, the sections this applied to have been removed. Closing.
