### ISSUE TITLE
Clarification: RSS for messaging?

### ISSUE THREAD

**Issue by ajs6f** [fcrepo/fcrepo-specification#92]
My read of the [current spec](https://fcrepo.github.io/fcrepo-specification/#message-serialization) leads me to suppose that an RSS feed in which the `/item/description` elements contains appropriate AS serializations of events would be a perfectly fine Fedora messaging feed. Am I missing anything or does this seem correct to those who have put more thought into that part of the spec than I?

**Comment by birkland** [comment]
It's agnostic on transport-level details, so to me an RSS feed would be fine.  [Server sent events](http://www.w3.org/TR/eventsource/) might also be a good choice as well, especially for situations involving consuming lots of messages, reacting to them in a browser, consuming infinite streams of messages, etc.

**Comment by ajs6f** [comment]
In the absence of further comment in the next few days, I'll close this issue with the herein-recorded understanding that RSS publication or server-side events would be a fine way of fulfilling the Fedora messaging service, amongst many others.

**Comment by acoburn** [comment]
The one thing I would mention is that the messaging section currently uses the word "emit", which could be construed to be in conflict with how RSS publishes messages. I would like to see the word "emit" replaced with something more appropriate, so that RSS publication of events is entirely possible.

**Comment by acoburn** [comment]
With #106 now merged, is it sufficiently clear that RSS-based notifications would be acceptable?

**Comment by ajs6f** [comment]
I think so.
