### ISSUE TITLE
Should the specification say something about the connectedness of RDF behind multiple resources?

### ISSUE THREAD

**Issue by zimeon** [fcrepo/fcrepo-specification#93]
One of the most striking features of the LPD specification is that it is silent on whether or not LDP-RSs are separate buckets of data (e.g. files, named graphs), or views into a shared dataset (e.g. a triplestore with one graph). Fedora4 effectively sidesteps this distinction through the subject restriction on triples in a LDP-RS: the subject of each triple must be either the resource or a fragment of the resource it is in.

Should the new specification restrict implementations to a particular approach? Should it say anything about this? I raised this issue at the [LDCX17 Standardizing Fedora session](https://docs.google.com/document/d/1m9QwMimrUqFVBH8ZEx79tpYFSczQPgUT8BNemsIk5P0/edit) because it seems to tie with core questions about what sort of interoperability the specification is designed to provide.

I suspect the consensus will be that the specification should not impose restrictions in this area. If that is the case then we should be clear that "swappable" (e.g. as discussed [2017-03-23](https://wiki.duraspace.org/x/3Qv2B)) is not a goal of this specification (though could be combined with others for such purposes), and such understanding might help us think about other issues.

**Comment by birkland** [comment]
It's striking how many topics LDP is silent on, and how much flexibility it allows implementers on a whole host of topics.  I don't think implementations of the Fedora spec will realistically be swappable (at least not easily).

For us (at JHU), this is one of the reasons we intend to leverage API-X as a mechanism of reducing risk.  We can define the features/capabilities that are essential to us, and essentially extend or amend the capability of an existing repository as necessary, without implementing a repository from scratch.  This affords some agility if/when we need to change implementations.

**Comment by dannylamb** [comment]
@zimeon I'm also predicting that the consensus will be not to specify, and I think it would be in good form to explicitly state that being swappable is not the goal.  As someone who is tasked with integrating with Fedora, it would be good to be firm about that upfront.  I would like to quell the expectation that Islandora will work with every Fedora implementation possible.

**Comment by escowles** [comment]
Can we create a vocabulary, akin to the LDP interaction models, that would at least allow implementations to advertise what they support in this area?  So you could at least say that an application should work with any Fedora implementation that supports `<http://example.org/#SingleSubjectGraph>` or `<http://example.org/#ArbitraryGraph>` or whatever?

**Comment by ajs6f** [comment]
@escowles Is it better to advertise capabilities or restrictions? LDP already provides some ways to advertise the latter.

**Comment by escowles** [comment]
@ajs6f Advertising restrictions sounds like a good way to go — having a way to advertise the single-subject restriction in particular would be good.

**Comment by acoburn** [comment]
LDP already gives us this: `Link: <http://fedora.info/definitions/repository#InvalidSubject>; rel="http://www.w3.org/ns/ldp#constrainedBy"`

The question for the Fedora spec is whether the spec defines a minimal set of constraints or whether they are defined by implementations. For example, Trellis defines its own constraints: http://acdc.amherst.edu/ns/trellis.

**Comment by ajs6f** [comment]
In a world of linked data, it's not really possible (or a good idea) for Fedora to try to "constrain the constraints". In other words, any given implementation should always be free to ignore Fedora's suggestions or develop its own constraints. But I think that a few obvious examples have popped up (e.g. SSR). I'd prefer that instead of putting them in the spec, where they get rather "fixed", we put them in the accompanying ontology, which should be able to respond to corrections and additions a bit faster.

**Comment by acoburn** [comment]
👍  on defining a set of "standard constraints" in a `fedora` ontology. 

Perhaps it would be good to include some language in the specification indicating that implementations `SHOULD` use those constraint definitions, where possible. This could be done without actually enumerating the existing constraints.

This addition would go a long way toward improving "swappability" between implementations.

**Comment by escowles** [comment]
👍  to defining common constraints in the fedora ontology — I hope that will help clients negotiate the differences between implementations much more easily.

**Comment by ajs6f** [comment]
In that case, I'm not sure whether we even need to call out that chunk of ontology in the spec, or just let it be a matter of practice...?

**Comment by acoburn** [comment]
@ajs6f I'm fine with leaving the spec silent on the matter. I can say that from my perspective as an implementer, I would absolutely use those common constraint IRIs if they are defined in a publicly accessible vocabulary.

**Comment by ajs6f** [comment]
Rocktacular, @acoburn. @zimeon, would this kind of approach resolve the issue for you?

**Comment by zimeon** [comment]
There seems clear consensus in this thread that the specification should not attempt to constrain the possible implementation patterns around the connectedness or otherwise of RDF resources in Fedora.

There seems to be support for the idea of maintaining some taxonomy of constraints outside of the API specification. A central server-constrains document would be the ideal place to express this. But, as it stands, the only way to get a constraints document is from a [link header in response to a failed request](https://www.w3.org/TR/ldp/#ldpr-gen-pubclireqs) and this is may vary based on the context resource (LDP sensibly has a very limited notion of "server"). So, while I like the idea of providing a way for clients the help negotiate the differences between, I'm not sure how best we could do it. Ideas?

For now, I propose adding a note explaining the "unconstrainedness" of the storage model along these lines:

> Non-normative note: Neither [LDP] nor this specification constrains the underlying storage model for RDF data. Each LDP-RS may be entirely independent RDF content, may be a portion of a shared RDF store, or follow some other arrangement. Implementation constraints that result in failure to complete client requests are expressed in a constraints document (\[LDP] [4.2.1.6](https://www.w3.org/TR/ldp/#ldpr-gen-pubclireqs)) as noted in the appropriate sections of [LDP] and below.

**Comment by awoods** [comment]
Sounds reasonable, @zimeon .

**Comment by ajs6f** [comment]
That's good wording, @zimeon, but I'm not quite clear on why constraints for this kind of thing couldn't be provided via a `Link` header?

**Comment by zimeon** [comment]
@ajs6f - We could add another link header (though I'm loathe to invent one and mandate(?) it). I was thinking that putting the information in the normal constraints document would be ideal except that there is no guaranteed way to get its location except by creating an error, and then it might be specific to the context resource and/or error.

**Comment by ajs6f** [comment]
Hm. So the question is: what if a client would like to discover the limits of interaction without just punching the server until something goes wrong?

**Comment by zimeon** [comment]
Yup

**Comment by ajs6f** [comment]
That's a good point. Referring to the link you gave above to LDP 4.2.1.6, I read:

> The same Link header MAY be provided on other responses.

Might strengthening that to `SHOULD` and clarifying which responses are meant ameliorate your concern?

**Comment by acoburn** [comment]
There was some earlier discussion about the possibility of using [HydraCG](http://www.hydra-cg.com/spec/latest/core/) or [Swagger](https://swagger.io/) with Fedora4. The concern at the time was that much of that would simply recapitulate LDP, which didn't seem to add much value, but I wonder if it might be worth revisiting that discussion. As it is, a Fedora implementation is not prohibited from implementing a Hydra or Swagger API description, and those API documents are specifically designed to allow clients to discover what a server can do (without having to resort to wait until something goes wrong).
