### ISSUE TITLE
Add a motivation/intent section

### ISSUE THREAD

**Issue by osmandin** [fcrepo/fcrepo-specification#95]
At some point, it would be helpful to have a section covering the intent of the specification. 

In other words, expanding on the Abstract section:

"This specification refines the semantics and interaction patterns of [LDP] in order to better serve the specific needs of those interested in implementing repositories for durable access to digital data"

**Comment by ajs6f** [comment]
We've discussed this very point before, @osmandin, and it wasn't possible at the time to develop such a statement with which every stakeholder could agree. Are you able to participate in the ongoing discussions of exactly this issue?
