### ISSUE TITLE
Too many cooks in the kitchen

### ISSUE THREAD

**Issue by acoburn** [fcrepo/fcrepo-specification#97]

**Comment by escowles** [comment]
👍  I think it would be good to create a contributors section and move most of the current editors (including myself) there.

Do we have any volunteers to be editor(s)?

**Comment by ajs6f** [comment]
:raised_hand:

**Comment by ajs6f** [comment]
@barmintor, @zimeon, there should be some strong representation from every community within Fedora. Would one of you be available on behalf of Hydra, or would someone else be appropriate?

**Comment by barmintor** [comment]
I am 👍 to separating contributors and editors, I am 👍 to the specification effort, I am 👎  to it being assembled from volunteers in a github issue. There's a leadership group for this project, it represents paying member institutions, and it should be responsible for:

1. chartering the editorial effort
2. identifying their constituencies, and 
3. nominating the editors.

I've seen to date how much work this is, and the leadership group needs to make it part of the editors' jobs. Dialogue about this spec is increasingly stressful, enough to have made me reluctant to write up proxied content proposals despite the fact that my employer (and some Hydra partners) needs it, and far too much so for me to deal with as a spare time task at work (and I'm an enthusiastic proponent of the specification!). I take that to mean we need structural support and a mandate from the FLG.

**Comment by ajs6f** [comment]
Those are very fair points, @barmintor, and in no way did I intend to assemble a complete complement of editors here in this issue. My concern was (and is) only to discover interest as expediently as possible. There is a public commitment on the part of the project to having a first version of the spec available in May. Given @barmintor's points above, does that actually make any sense?

**Comment by awoods** [comment]
@barmintor : Those are my feelings exactly. The process is in-motion regarding getting Fedora Leadership engaged in specification editor nominations.

**Comment by declanfleming** [comment]
Thanks!  We're on it.
