### ISSUE TITLE
Appropriateness of message/external-body

### ISSUE THREAD

**Issue by acoburn** [fcrepo/fcrepo-specification#99]

**Comment by barmintor** [comment]
In the case of Columbia, having a way for some clients to indicate content that should be proxied, but is not appropriate to offer as a link to a client, is an important use case. Further, when seeking feedback on binary storage in Cavendish, I've received more feedback about having C be able to negotiate local files than about storing binaries "natively". So I think that there is a case for `access-type=local-file`, but the more general case of `access-type=url` is less clear to me.

**Comment by ajs6f** [comment]
What does `access-type=local-file` mean in the case of a distributed implementation that shards data?

**Comment by barmintor** [comment]
the way that I read the RFC is that the `message/external-body` MIME is to be used in conjunction with another Content-Type value and is relevant to the recipient on that interaction. So in the case of any implementation, I'd suggest it mean `act like my message body is at the path indicated in the name parameter`. I don't think it's appropriate if the server is the sender, for example.

**Comment by ajs6f** [comment]
So for some distributed implementation, it might be that some nodes will successfully answer the request and some won't? I'm not raising that as an instantly insuperable objection (although it doesn't sound ideal)-- just trying to make sure the consequences are clear. I guess I'm wondering if this the use case for `access-type=local-file` is one of these things where folks who need that will end up needing to select an impl that actually guarantees to do it, _whether or not_ `message/external-body` is in the spec.

**Comment by barmintor** [comment]
These are good questions, @ajs6f. Just as context: I think something that has to be reckoned with is that presenting as a file system is a frequent integration mechanism- URL protocols might have taken the place of this once upon a time, but I've never seen e.g. the Java url-IO mechanisms be enthusiastically received. So now we see networked storage interfaces on private networks instead.

**Comment by ajs6f** [comment]
That's very true. To be clear, I'm not arguing that ` message/external-body` doesn't have utility-- it clearly does. The question I'm raising (and I _think_ the question that @acoburn raised) is whether that utility is both so large and so impossible to substitute that it demands inclusion in the spec, from which it would follow that _every_ impl (including those for which the kind of integration to which you just pointed makes no sense or is impossible) would have to reckon with it.

**Comment by acoburn** [comment]
Yes, this is exactly the point I am raising here.

**Comment by barmintor** [comment]
Good points. I'm trying to write something up, but maybe the right thing to do here is at least initially write it up as an auxiliary. I have to defer the question of largeness (my opinion is distorted by the centrality of the use case for MPOW). "impossible to substitute" is an intriguing thing to consider, as (I hope obviously) the function here is more important to me than the mechanism, but this does seem like a natural fit to me (worth noting that @acoburn read the same specs with somewhat different conclusions). I'd be lying if I said I haven't been looking for alternatives, though.

**Comment by acoburn** [comment]
I was sort of hoping that the Content-Location header would be a good substitute, but I don't think it quite fits. The new HTTP spec has some additional verbiage about what the header means for PUT and POST, but I found it really hard to understand. It _seems_ as though the content payload would still need to be included, (unlike external-body) which seems to defeat the purpose of referring to external content, but maybe someone else has a better understanding of its use.

**Comment by barmintor** [comment]
There is a tempting read of `Content-Location` as documenting an original location (keep a reference) and `Content-Type:message/external-body` as documenting a transient location (copy it), but the admonitions about `PUT` and `POST` make me uncomfortable.

**Comment by barmintor** [comment]
The stored-reference models don't completely address the concerns about `Want-Digest`, either. Local file references, meh sure, but proxied URL content is a kettle of fish.

*edit: I don't allay other people's concerns 😳 *

**Comment by ajs6f** [comment]
Yeah, the fixity thing is a whole 'nuther story for this kind of function. I think it's fair to say (without meaning to tangle threads) that if the fixity functions don't land in the spec, that other story would be resolved. But it would leave the basic question that @acoburn raised.

**Comment by awoods** [comment]
@acoburn : I believe this issue has been resolved with: https://github.com/fcrepo/fcrepo-specification/pull/121
If you agree, would you please close this issue?

**Comment by awoods** [comment]
Resolved with https://github.com/fcrepo/fcrepo-specification/pull/121
